### ISSUE TITLE
[dados] Atualizar dados de Inflação no <br_ibge_ipca>

### ISSUE THREAD

**Issue by agorenstin** [basedosdados/mais#1007]
**Metadados da base**

O Dataset diz respeito aos números oficiais de inflação divulgados pelo IBGE mensalmente. 

2. Qual o nome do conjunto? `dataset_id`
br_ibge_ipca

3. Problemas:
1.As 4 tabelas do conjunto estão atualizadas apenas até setembro/21, quando já poderiam estar atualizadas até outubro/21 e nos próximos dias o índice de Novembro também será divulgado. 

2.Além disso, na tabela basedosdados.br_ibge_ipca.mes_categoria_municipio identifiquei que nela constam dados de apenas de seis munícipios (Rio Branco, São Luis, Aracaju, Campo Grande, Goiania, Brasilia) sendo que no site do IBGE, é dito que a pesquisa é feita nos seguintes municípios: 
"Atualmente, a população-objetivo do IPCA abrange as famílias com rendimentos de 1 a 40 salários mínimos, qualquer que seja a fonte, residentes nas áreas urbanas das regiões de abrangência do SNIPC, as quais são: regiões metropolitanas de Belém, Fortaleza, Recife, Salvador, Belo Horizonte, Vitória, Rio de Janeiro, São Paulo, Curitiba, Porto Alegre, além do Distrito Federal e dos municípios de Goiânia, Campo Grande, Rio Branco, São Luís e Aracaju."
https://www.ibge.gov.br/estatisticas/economicas/precos-e-custos/9256-indice-nacional-de-precos-ao-consumidor-amplo.html?=&t=o-que-e

**Comment by rdahis** [comment]
@gustavoairestiago eu acabei dando merge no PR mas notei que de fato tem tabelas faltando dados.

Exemplo:
```sql
SELECT distinct(id_municipio) as id_municipio
FROM `basedosdados.br_ibge_ipca.mes_categoria_municipio`
order by id_municipio asc
```

Aqui era pra ter mais municípios, e não só 6, como apontou o @agorenstin.

**Comment by laura-l-amaral** [comment]
Já está rodando em pipelines
