### ISSUE TITLE
[dados] Erro Censo Escolar - Nº de Matriculas estados do Sudeste

### ISSUE THREAD

**Issue by gustavoairestiago** [basedosdados/mais#1044]
Nº de matriculas por estados (foi testado estados do sudeste) estão aparentemente errados. Aparentemente houve uma troca entre RJ e SP e dados errados em ES e MG (com filtros de rede da escola). Existe uma quebra dos dados antes de 2014 e após

query: `SELECT ano, sigla_uf, COUNT(DISTINCT id_matricula) as matriculas FROM `basedosdados.br_inep_censo_escolar.matricula`
WHERE rede = "estadual" or rede = "federal" or rede = "municipal"
GROUP BY ano, sigla_uf`

query para SP sem filtro de rede: `SELECT ano, sigla_uf, COUNT(DISTINCT id_matricula) as matriculas FROM `basedosdados.br_inep_censo_escolar.matricula`
WHERE sigla_uf= "SP"
GROUP BY ano, sigla_uf`

Evolução das matriculas por ano em SP (com filtro de rede):
![WhatsApp Image 2022-01-04 at 15 23 06](https://user-images.githubusercontent.com/36206956/148106839-38131f50-582f-4e39-a86c-c3c76a9a6c83.jpeg)

Evolução das matriculas por ano em RJ (com filtro de rede):
![WhatsApp Image 2022-01-04 at 15 21 41](https://user-images.githubusercontent.com/36206956/148106846-92e3b9fc-445f-4735-8011-1324c6853c44.jpeg)

**Comment by mavalentim** [comment]
A base era muito grande pra fazer todos os anos no mesmo script sem crashar o Stata. Quebrei o script em dois e devo ter invertido no loop os nomes dos estados. Desculpa gente, melhor subir essa base de novo pois ela ta com uns errinhos.

**Comment by mavalentim** [comment]
ok, estranho os códigos no stata estão fazendo sentido: eu pensei que tinha colocado em uma ordem errada, mas mesmo em ordens diferentes os exports de csv dariam certo pois estão sendo nomeados certo. Acho que o problema foi em subir os dados na plataforma da bd e não a geração deles. Algum assistente pode conversar comigo nessa semana pra ver isso?

**Comment by mavalentim** [comment]
Baixei os dados de SP e RJ e vou invertê-los. @gustavoairestiago pode especificar o erro que voce falo em MG e ES? Nao ficou claro pra mim desculpa!

**Comment by mavalentim** [comment]
Então gente, os dados tão certinhos, o problema mesmo é que eu troquei os ids das ufs brasileiras. No código gerador tá escrito:

gen sigla_uf = "SP" if id_uf == "31"
replace sigla_uf = "MG" if id_uf == "33"
replace sigla_uf = "ES" if id_uf == "34"
replace sigla_uf = "RJ" if id_uf == "35"

Ou seja, eu simplesmente me confundi completamente. Menos mal, já to baixando e consertando.

O problema maior, acho é como a gente comunica esses erros pros usuários. Pessoas que já usaram essa base podem ter sido comprometidas. Peço enorme perdão gente, foi uma bobeira minha. 

Com autorização do @rdahis ou do @d116626 queria pedir permissão para tirar as bases do sudeste de matricular do cloud para reorganizar elas

**Comment by rdahis** [comment]
Ótimo achado @gustavoairestiago @mavalentim!

Lá no Discord tamos conversando de só renomear pastas, ao invés de deletar e subir de novo. Vê o que prefere?

**Comment by rdahis** [comment]
Em princípio resolvido porque subimos os dados com nomes de UFs ajustados fornecidos pelo @mavalentim.
