### ISSUE TITLE
[infra] (1) renomear '/bases' para '/datasets', (2) criar pasta '/tables' dentro de '/datasets'

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#105]

**Comment by JoaoCarabetta** [comment]
Isso parece uma mudança gigante, porém interessante. A estrutura seria:

```
datasets
   |- br_censo
       |- code
       |- tables
           |- microdado
               |- table_config.yaml
               |- publish.sql
       |- dataset_config.yaml      
 ```
 
 @d116626 @Hellcassius 
 
Eu de fato acho que assim fica mais organizado, mas isso deve quebrar basicamente tudo. Temos que ver se realmente vale a pena.

**Comment by rdahis** [comment]
Para registrar aqui o que subi no Discord, no limite teríamos toda a estrutura do banco como na figura abaixo. Mas dado a discussão de no futuro ter toda a estrutura de proposta e revisão no site, não faria sentido fazer aqui no Github.

![Screen_Shot_2021-02-18_at_2 55 32_PM](https://user-images.githubusercontent.com/6617207/111041013-f1f6c780-83ea-11eb-91f2-add833c52df9.png)

**Comment by d116626** [comment]
Metadados migrados para o ckan
