### ISSUE TITLE
[infra] `Metadata.create` não preserva metadados de colunas já existentes quando `force_columns` é `True` no pacote de Python

### ISSUE THREAD

**Issue by vmussa** [basedosdados/mais#1055]
**Descrição**
Ao passar um valor para o argumento `columns` do método `Metadata.create`, o esperado era que o `table_config.yaml` fosse sobrescrito, de forma que as colunas locais preponderassem sobre as colunas do CKAN na hora de formar o YAML, só que preservando os metadados de colunas já existentes no CKAN. O que acontece hoje, no entanto, é que o YAML é gerado com as colunas locais e metadados vazios. Isso prejudica o workflow da subida de dados, provocando um passo manual a mais de preenchimento de metadados de colunas já existentes. 

**Reproduzir**
Basta utilizar o seguinte código:

```python
import basedosdados as bd
from basedosdados.upload.metadata import Metadata
import shutil
from pathlib import Path

# cria caminho para o diretório onde estarão os metadados
metadata_path = (Path().resolve() / "tmp_bases")

# deleta se já houver algo
shutil.rmtree(metadata_path, ignore_errors=True)

# cria nova pasta
metadata_path.mkdir(exist_ok=True)

br_ibge_pib_municipio = Metadata(dataset_id='br_ibge_pib', table_id='municipio', metadata_path=metadata_path)
br_ibge_pib_municipio.create(
    if_exists="replace",
    columns=[
        'id_municipio',
        'b'
    ],
    force_columns=True,
)
```
Em seguida, é só abrir o `table_config.yaml` gerado em `./tmp_bases/br_ibge_pib/`.

**Comportamento esperado**
O esperado era que o `table_config.yaml` fosse sobrescrito, de forma que as colunas locais preponderassem sobre as colunas do CKAN na hora de formar o YAML, só que preservando os metadados de colunas já existentes no CKAN.

**Capturas de tela**
Criação da tabela:
![image](https://user-images.githubusercontent.com/4412998/149242315-b00adf62-4732-4e89-9d6f-23e4cfee25fb.png)
YAML resultante sem metadados preenchidos, embora sobrescrito:
![image](https://user-images.githubusercontent.com/4412998/149242372-8c5daada-2e6e-4e13-8416-3f69c8831210.png)

**Versão do pacote**
`basedosdados==1.6.1`

**Comment by laura-l-amaral** [comment]
não faz mais sentido no pacote novo
