### ISSUE TITLE
[infra] No pacote de Python, ao passar um `path` para o `Table.create`, o `Metadata.create` deveria sobrescrever os metadados de colunas caso haja diferenças com relação ao CKAN

### ISSUE THREAD

**Issue by vmussa** [basedosdados/mais#1057]
**Descrição**
Antes da versão `v1.6.0`, o `Table.create` era capaz de gerar arquivos de configuração baseado nas colunas de um CSV, quando passávamos um `path` para ele. Agora, ele mantêm as colunas do CKAN e ignora as do CSV, dificultando oprocesso de atualização de tabelas.

**Reproduzir**
Rode o seguinte código Python:
```python
import basedosdados as bd
from basedosdados.upload.table import Table
import shutil
from pathlib import Path

# cria caminho para o diretório onde estarão os metadados
metadata_path = (Path().resolve() / "tmp_bases")

# deleta se já houver algo
shutil.rmtree(metadata_path, ignore_errors=True)

# cria nova pasta
metadata_path.mkdir(exist_ok=True)

tb = Table("br_ibge_pib", "municipio", metadata_path=metadata_path)
tb.create(
    path="municipio.csv",
    if_table_config_exists="replace",
    if_table_exists="pass",
    if_storage_data_exists="pass",
)
```

Assumindo que haja, no mesmo diretório, um CSV chamando `municipio.csv` com o seguinte conteúdo:
```
id_municipio,b
1,2
```

Em seguida, basta olhar o arquivo YAML localizado em `./tmp_bases/br_ibge_pib/municipio/table_config.yaml`, que estará preenchido com as colunas do CKAN, em vez dessas do CSV.

**Comportamento esperado**
Assim como descrito em #1055, era esperado que o YAML sobrescrevesse as colunas do CKAN, mantendo preenchidos metadados de colunas já existentes.

**Capturas de tela**
Geração da tabela:
![image](https://user-images.githubusercontent.com/4412998/149245294-52412303-4b31-4e25-9c72-916cadc81429.png)
CSV de base:
![image](https://user-images.githubusercontent.com/4412998/149245335-ab67382d-0eef-4f6d-93ce-ba982ddf947a.png)
Resultado inconsistente:
![image](https://user-images.githubusercontent.com/4412998/149245388-feeab783-c508-4a91-964c-5feacb5b85cc.png)

**Versão do pacote**
`basedosdados==1.6.1`

**Contexto adicional**
Provavelmente essa integração será fácil de fazer, porque já existe um motor de identificação das colunas do CSV no `Table`. Dessa forma, basta passar as colunas identificadas para o `Metadata.create` com o argumento `force_columns=True`, que força a sobrescritura das colunas do CKAN pelas locais.

**Comment by laura-l-amaral** [comment]
parou de fazer sentido com a mudança para v2.0
