### ISSUE TITLE
Adicionar vA.B no yaml do dataset.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#106]

**Comment by JoaoCarabetta** [comment]
Acho melhor colocar a versão por tabela, não?

**Comment by rdahis** [comment]
Eu tinha pensado que muitas vezes a mudança no código pode afetar múltiplas tabelas, e aí fica chato de ficar mudando e atualizando cada uma. Mas sem grandes preferências.

**Comment by rdahis** [comment]
@JoaoCarabetta Adicionei `version` ao `table_config.yaml` no commit 3ffde7f. Não sabia se precisava mudar também o table_description.txt.

**Comment by rdahis** [comment]
Fechando porque acho que está resolvido, pelo menos no `table_config.yaml` template. Depois o @JoaoCarabetta confirma se precisa mudar o `table_description.txt` e como atualizar as tabelas já geradas no BQ.
