### ISSUE TITLE
[dados-qualidade] Geralzona nos dados, metadados, arquivos auxiliares, etc.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#1061]
Acompanhamento: https://docs.google.com/spreadsheets/d/1_ItYdWWOK8qhgHuCaZIXzvne5KJP9uUFD3NrG1GyKcU/edit?usp=sharing

**Comment by fernandascovino** [comment]
@basedosdados/dados aí, para adicionarmos o novo recurso de "Tratemento dos dados" aos conjuntos, pensamos em ter um `README` padrão na pasta `code` que reune toda a metodologia de tratamento assim como os hyperlinks para códigos, etc (ao invés de puxarmos um código direto do Github). Podem adicionar essa tarefa de criar o esqueleto aqui?

![image](https://user-images.githubusercontent.com/20743819/150030585-a6e655b7-6c14-46a1-8990-0f49ac455113.png)

**Comment by fernandascovino** [comment]
such as: https://github.com/fernandascovino/tcc_emap

**Comment by rdahis** [comment]
Será feito o tracking de qualidade de dados via nosso painel no metabase.
