### ISSUE TITLE
[infra] Não deveria ter apenas tabelas na chave 'resources' na resposta da API do CKAN?

### ISSUE THREAD

**Issue by lucascr91** [basedosdados/mais#1064]
**Descrição**
Para acessar informações das tabelas de um dataset, o usuário puxa uma lista de dicionários contida em `response['result']['datasets']['resources']`. Ocorre que, normalmente, nessa lista existem outras informações, além das tabelas. É comum aparecer informações como "Baixar" e "Visualizar", cujo significado não é muito claro para mim.

**Reprodução**
Por exemplo, nos dados da ALESP, a primeira entrada de resource é "Baixar". A entrada tem informações como se trata-se de uma tabela de dados, como cobertura temporal e `update_frequency`:

```python
import requests
url = 'https://basedosdados.org/api/3/action/bd_dataset_search?&resource_type=bdm_table'
response = requests.get(url)
json_response = response.json()
datasets = json_response["result"]["datasets"]
print(datasets[3]['resources'][0])
```
Retorna:

```
{'id': 'c0cd1d4d-1f22-49e8-b8a0-61bc1483b8bd',
 'name': 'Baixar',
 'description': '',
 'position': 0,
 'url': 'https://www.al.sp.gov.br/dados-abertos/',
 'cache_last_updated': None,
 'cache_url': None,
 'created': '2020-11-02T17:40:56.533253',
 'datastore_active': False,
 'format': '',
 'hash': '',
 'last_modified': None,
 'metadata_modified': '2022-01-14T22:21:24.978812',
 'mimetype': None,
 'mimetype_inner': None,
 'package_id': '930e3443-6854-4842-aa0d-82c2c8dfd23b',
 'size': None,
 'state': 'active',
 'url_type': None,
 'resource_type': 'external_link',
 'dataset_id': 'br_sp_alesp',
 'language': ['portuguese'],
 'has_structured_data': 'yes',
 'has_api': 'no',
 'is_free': 'yes',
 'requires_registration': 'no',
 'availability': 'online',
 'country_ip_address_required': None,
 'license': 'mit',
 'spatial_coverage': {'continent': ['south_america'],
  'country': ['bra'],
  'admin1': ['id_uf_35']},
 'temporal_coverage': [2011,
  2012,
  2013,
  2014,
  2015,
  2016,
  2017,
  2018,
  2019,
  2020],
 'update_frequency': 'recurring',
 'entity': ['person', 'law'],
 'formato': ''}
```

**Comportamento esperado**

As outras entradas de `resource` nesse caso apresentam o comportamento esperado, parecendo de fato se tratar de tabelas:

```python
for i in range(5):
    print(datasets[3]['resources'][i]['name'])
```
Retorna:
```
Baixar
despesas_gabinete
despesas_gabinete_atual
assessores_parlamentares
assessores_lideranca
```
Minha dúvida é: eram para esse termos "Baixar", "Visualizar" estarem aparecendo em `resources`? Se sim, existe uma chave que contém exclusivamente informação das tabelas do `dataset`?

**Comment by d116626** [comment]
Opa, isso acontece por conta do campo `resource_type`. Temos alguns tipos de resources diferentes, sendo `bdm_table`e `external_link` os que estão em funcionamento agora, `bdm_table` é referente as tabelas que possuem `dataset_id.table_id` e estão no datalake, já `external_link` possui informações gerais sobre um conjunto. Essa parte do `name` aparecer "Baixar", "Visualizar" é algo que o @rdahis  tem que corrigir nos metadados, colocando um nome mais decente kkkk
