### ISSUE TITLE
[dados] br_ans_beneficiario.informacao_consolidada

### ISSUE THREAD

**Issue by guissalustiano** [basedosdados/mais#1078]
**Metadados da base**

1. Descrição: `O conjunto contém Informações consolidadas de beneficiários por competência. Este será alterado para inclusão de dados acima de 5 anos e melhorias na qualidade dos dados`

2. Qual o nome do conjunto? `br_ans_beneficiario`

3. Qual o nome da(s) tabela(s)? `informacao_consolidada` 

4. Fonte original dos dados: [https://dadosabertos.ans.gov.br/FTP/PDA/informacoes_consolidadas_de_beneficiarios/](https://dadosabertos.ans.gov.br/FTP/PDA/informacoes_consolidadas_de_beneficiarios/).
[Tambem disponível no portal de dados abertos](https://dados.gov.br/dados/conjuntos-dados/informacoes-consolidadas-de-beneficiarios)

5. Cobertura espacial: `br`

6. Cobertura temporal: de `2014/05 a 2022/12` (atualizado mensalmente)

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template
- [x] Preencher as tabelas de arquitetura
- [x] Escrever código de captura
- [X] Escrever [codigo](https://github.com/guissalustiano/mais/tree/data/br_ans/bases/br_ans/code) de limpeza de dados.
- [x] Organizar arquivos auxiliares, se necessário.
- [x] Criar tabela dicionário, se necessário.
- [X] Subir [arquiteturas](https://docs.google.com/spreadsheets/d/11hTzsBQja-bpM9dac9NkmGvSI39xqiW7TC8amQUUvzc/edit#gid=0), dados e arquivos auxiliares no Google Cloud.
- [x] Enviar tudo para [revisão](https://github.com/basedosdados/mais/pull/1582).
  - [X] Subir dados no [BigQuery](https://console.cloud.google.com/bigquery?referrer=search&project=basedosdados-staging-379403&supportedpurview=project&ws=!1m4!1m3!3m2!1sbasedosdados-staging-379403!2sbr_ans_beneficiario_staging)

**Comment by lucasnascm** [comment]
Fala @guissalustiano! Mto bom saber que tu tem o código. Eu comecei a subir os dados, tem a issue #930  e o PR #1042 com os microdados a nível do município. Bora juntar forças. Tu usa o Discord? Me chama lá @lucasmoreira#8573

**Comment by guissalustiano** [comment]
Topp @lucasnascm vou te chamar por la!

eu procurei por ANS e nao listou a sua issue
