### ISSUE TITLE
[infra] Inconsistência no padrão de dataset_id nos endpoints do CKAN

### ISSUE THREAD

**Issue by lucascr91** [basedosdados/mais#1079]
O padrão de `dataset_id` na resposta do endpoint `bd_dataset_search` usa hífen como separador, enquanto nas urls dos endpoints que especificam o parâmetro`dataset_id` o separador usado é _underline_.

Ver exemplo abaixo:
```python
import requests
url= 'https://basedosdados.org/api/3/action/bd_dataset_search?&resource_type=bdm_table'
response = requests.get(url)
json_response = response.json()
datasets = json_response["result"]["datasets"]
print(datasets[3]['name'])
```

Retorna:
```
br-ibge-ipca15
```
Mas a url que dá acesso a esse dataset usa `br_ibge_ipca15` no parâmetro `dataset_id`. Usar `br-ibge-ipca15` gera um erro:

```python
url = 'https://basedosdados.org/api/3/action/bd_bdm_dataset_show?dataset_id=br-ibge-ipca15'
response = requests.get(url)
assert response.status_code==200 #Asserton Error
```

O problema disso é que o usuário pode listar os dataset_ids usando o endpoint `bd_dataset_search`e depois não consegui usar os endpoints que usam o parâmetro `dataset_id`, pois o valor de `dataset_id` estará errado.

**Comment by rdahis** [comment]
Temos um campo `name` (com `-`) e outro `dataset_id` (com `_`, para uso no BigQuery). Então não entendi se de fato é um bug ou só uma confusão com nossa arquitetura.

**Comment by d116626** [comment]
Revisei o dataset aqui e tá tudo normal, parece que é o que o @rdahis  já respondeu
