### ISSUE TITLE
[infra] Suporte a parquet

### ISSUE THREAD

**Issue by guissalustiano** [basedosdados/mais#1082]
**Sua solicitação de recurso está relacionada a um problema? Por favor descreva.**
Suporte a arquivos parquet para o bigquery. Atualmente não há nenhuma documentação sobre como subir arquivos em parquet e [não há suporte da cli em python](https://github.com/basedosdados/mais/blob/1775a8469e34f5cb5f9b289fc7546a26a4c04113/python-package/basedosdados/upload/table.py#L560)

**Descreva a solução que você gostaria**
Dar suporte a parquet no cli e recomenda-lo pelo menos para grandes datasets

**Descreva alternativas que você considerou**

**Contexto adicional**
O [parquet](https://blog.openbridge.com/how-to-be-a-hero-with-powerful-parquet-google-and-amazon-f2ae0f35ee04) é um formato de armazenamento colunar muito usado no ecossistema hadoop.
Ele armazena os valores em formato binario garantindo que o mesmo tipo escrito seja lido, além disso por ser armazenado por coluna tem a leitura de poucas colunas muito mais rapido (oque é o caso da maioria de consultas analiticas) e seu esquema de [_encoding_](https://github.com/apache/parquet-format/blob/master/Encodings.md) cria dicionarios para colunas [com menos de 10^15](https://stackoverflow.com/questions/45488227/how-to-set-parquet-file-encoding-in-spark#answer-45541741) oque contribui muito para diminuir seu tamanho e cria uma duvida sobre a ultilização de dicionarios externos.
Ele [é suportado](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-parquet) pelo big query sem nenhum contra limitação, [em comparação ao csv que é dado essa ressalva](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-csv#limitations).

Estou tentando importar dados da ANS (#1078 ) que dariam algo perto de 300GB em CSV.  Ao armazena-los em parquet gastaria menos 10GB, facilitando o tratamento local e diminuindo os gastos de banda e armazenamento da cloud.
![image](https://user-images.githubusercontent.com/32439070/150693471-baa6c515-9d14-43f9-8bef-2f002c0c9f19.png)

**Comment by guissalustiano** [comment]
Eu estou tentando aprender um pouco mais de GCP e a infra de vocês para poder ajudar aqui

**Comment by JoaoCarabetta** [comment]
- [ ] Adicionar parquet nas funções do seguinte arquivo https://github.com/basedosdados/mais/blob/master/python-package/basedosdados/upload/datatypes.py\
- [ ] Atualizar documentação de funções que tenham alguma flag com o tipo de arquivo
- [ ] Criar testes com arquivos parquet
