### ISSUE TITLE
[infra] In Table.create() allow to pass a csv file in parameter columns_config_url - currently it is only compatible with Google Sheets only

### ISSUE THREAD

**Issue by mfagundes** [basedosdados/mais#1084]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem, but it makes difficult to work with a centralized branch in the forked repository. In the [collaboration page](https://basedosdados.github.io/mais/colab_data/) it is suggested to create a tree structure that should be, as my point of view, in the branch created on the fork by the user (I suggest the Collaboration Page must me reversed, first creating the new branch in the forked project and, after that, creating the suggested structure inside the fork, in the ``bases`` folder, using <DATASET_ID> as its name). The architecture files must be in extra/architecture and, as far as I know, it is impossible to commit a gsheet file there (as it is just a pointer to a web file on Google Drive). 

**Describe the solution you'd like**
The Google Sheet should be used to request approval and, after that, collaborators must be oriented to download a csv copy to the extra/architecture folder. 

This procedure, then, should be accomplished by accepting both formats. [Here](https://github.com/mfagundes/mais/blob/05b055d8a8694a8122dcca1c2cfbde8dd535d924/python-package/basedosdados/upload/table.py#L531) the package checks if a Google Sheet path is passed and, if so, executes the method ``self.update_colums()``. This method checks if it is a valid Google Sheet file and proceeds to  ``self._sheet_to_df()``. 

**Describe alternatives you've considered**
My alternative would be to ``self.update_columns()`` checks also if its a valid csv file (in the url passed as a path to the architecture file and, if so, execute a new method, like ``self._csv_to_df()``, using the path provided by the user, like ``extra/architecture/<table_id>.csv`` (see below)

**Additional context**
In my opinion it would be much easier to those, like me, prefer to work with IDEs, centralizing all the process of creating a new dataset with the tables. The way it is working now, if the user doesn't pass the parameter ``columns_config_url`` it becomes a duplicate work, as we must create the architecture in a Google Sheet and, once the publish.sql file(s) is(are) generated, they must be edited to reflect the correct formats already determined by the architecture files (without ``columns_config_url`` all fields are created as STRING).

**Observation**
The name of the parameter, ``columns_config_url`` can be cofusing in this case, as if it could be, in this case, a url or a path. However, for legacy compatibility, pehaps it could be maintained

**Finally**
The collaboration page could, then, orient to include the (non mandatory) parameter ``--columns_config_path`` pointing to the csv file with the columns already submitted for approval.

**Comment by d116626** [comment]
Já implementado!
