### ISSUE TITLE
[infra] BaseDosDadosAccessDeniedException:  Are you sure you are using the right `billing_project_id`? (Python)

### ISSUE THREAD

**Issue by marlon-shiftone** [basedosdados/mais#1101]
**Descrição**
Segui todas as instruções e não consigo usar a API. Sempre obtenho o mesmo erro.

GenericGBQException: Reason: 403 Access Denied: Table basedosdados:br_me_socio.empresa: User does not have permission to query table basedosdados:br_me_socio.empresa.

(job ID: 96d452d9-02eb-43c7-bd41-2f159fd8fa52)

**Reproduzir**
df = bd.read_table(dataset_id='br_me_socio', 
table_id='empresa',
billing_project_id="project_id", reauth=True)

**Comment by lucascr91** [comment]
Você passou o nome correto do projeto no GCP? Se ainda tiver dúvida, nos procure no discord.
