### ISSUE TITLE
[dados] Tabelas de `br_inep_enem` não aparecendo em prod

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#1103]
### Descrição

O conjunto `basedosdados.br_inep_enem` não está aparecendo em produção. As tabelas existem em `basedosdados-dev`, mas deve ter tido algum problema no PR que levou para produção.

Rodar isso dá problema:

```SQL
SELECT * FROM `basedosdados.br_inep_enem.escola` LIMIT 1000
```

**Comment by lucasnascm** [comment]
Mas acho que é pq o PR da base tá aberto ainda aqui (PR #941). A gnt tirou de prioridade porque comunicação não usaria, além de subir junto com os microdados pra evitar  confusão.

**Comment by d116626** [comment]
tem que ficar de olho nos outputs da action pra evita de acontecer isso
