### ISSUE TITLE
[dados] Padronizar coluna `br_inep_censo_escolar.matricula.zona_residencial` para 0/1.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#1105]
**Descrição**
Hoje há valores 1/2 para alguns anos (e.g. 2008). Além disso essa coluna está publicada como INT64 e parece que está tudo nu Precisa vasculhar e padronizar.

```sql
SELECT DISTINCT zona_residencial
FROM `basedosdados.br_inep_censo_escolar.matricula`
where ano = 2007 and sigla_uf = 'AC'
```

**Comment by crislanealves** [comment]
- [ ] Conferir todos os dicionário e verificar se existe outras inconsistências para essa variável. 
- [ ] Adicionar todos os dicionários no drive.
- [ ] Enviar e-mail para o INEP.
