### ISSUE TITLE
[dados] `br_dieese_icv` não aparece em produção

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/mais#1107]
`br_dieese_icv` não aparece no site e as tabelas não aparecem em produção.

**Comment by d116626** [comment]
Aqui o PR que subiu esses dados: #918
Teria que ver o que rolou na action desse PR. Acho mais fácil só republicar, no estilo do que fiz pro diretorio de municipio

**Comment by crislanealves** [comment]
Resolvido no PR #1127
