### ISSUE TITLE
[infra] Adaptar o datacheck de % único para o novo formato de `observation_level`.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#1113]
Mudei o campo `identifying_columns` para dentro de `observation_level`, que agora é uma lista de dicts.

**Comment by lucascr91** [comment]
A Action de data-check foi descontinuada, então a issue perdeu sentido.

**Comment by rdahis** [comment]
> A Action de data-check foi descontinuada, então a issue perdeu sentido.

Foi descontinuada?? =( que momento
