### ISSUE TITLE
[dados] Ajustes das bases do inep

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/mais#1121]
- [x] Atualizar dados de 2021
- [x] Atualizar dados de 2007-2009
- [x] Criar partição de sigla_uf 
- [x] Excluir os dados de escola_inse e AFD do conjunto de indicadores_inep storage, bq e site

**Comment by laura-l-amaral** [comment]
@lucasnascm a tabela do inse não tá no site, eu excluo [esse conjunto](https://basedosdados.org/dataset/br-inep-indicador-nivel-socioeconomico?bdm_table=dicionario) do site ou incluo os metadados da tabela lá?
