### ISSUE TITLE
[dados] `br_ibge_censo_agropecuario.municipio`

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#1147]
**Metadados da base**

1. Descrição: Dados do Censo Agropecuário a nível de município-ano. Em parceria com o @arthurbraganca7.

2. Qual o nome do conjunto? `br_ibge_censo_agropecuario`

3. Qual o nome da(s) tabela(s)? `municipio`

4. Fonte original dos dados: IBGE

5. Cobertura espacial: Brasil

6. Cobertura temporal: 1985, 1995, 2006, 2017

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Checagem de qualidade dos dados de 1985.
- [x] Decidir como lidar com zeros vs nulos. (aparentemente nos dados originais ambos vem como zeros)
- [x] Baixar a pasta template
- [x] Preencher as tabelas de arquitetura
- [x] Escrever código de captura e limpeza de dados.
- [x] Organizar arquivos auxiliares, se necessário.
- [x] Criar tabela dicionário, se necessário.
- [x] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [x] Enviar tudo para revisão.

**Comment by rdahis** [comment]
Como estamos indo? Qual é o status atual? Posso ajudar?

**Comment by gustavoalcantara** [comment]
@rdahis essa semana a gente sobe. Semana passada foi corrida pra Cris e pro Lucas, aí seguramos um pouco. Tabela de arquitetura tá pronta e o código de ETL tb. 
Meu prompt tá configurado e é só subir...

**Comment by arthurbraganca7** [comment]
Oi @gustavoalcantara, estou curioso para ver a crítica dos dados. O @rdahis tinha achado algumas inconsistências nos dados tratados. Vocês conseguiram checar algo disso?

**Comment by gustavoalcantara** [comment]
oi @arthurbraganca7 conseguimos checar, sim. Na verdade, alguns dados precisam de detalhamento nas descrições... Fiquei meio perdido quanto ao que o dado se refere nesse sentido, só.
Fiz um trabalho de checar variável por variável no sidra, em nível de UF, pra ver se tava ok e estava. Baita de uma base de dados esse Censo. Gostei demais de trabalhar nele. Vamos marcar um dia pra conversar? Se cuida!

**Comment by arthurbraganca7** [comment]
Vamos falar sim! Para mim o mais relevante é entender a qualidade dos dados das planilhas de Excel que o IBGE disponibiliza (que foram a base do trabalho que eu fiz). Quero entender se esses dados tem consistência interna e se tem alguma diferença entre eles e o que está disponibilizado no SIDRA.

**Comment by gustavoalcantara** [comment]
Beleza! Quer deixar marcado algum dia? Posso todos, menos terça-feira até às 18h. Depois tô livre.
