### ISSUE TITLE
[infra] Erro ModuleNotFoundError: No module named 'loguru' ao importar basedosdados - Python

### ISSUE THREAD

**Issue by phgmacedo** [basedosdados/mais#1156]
**Descrição**
Seguindo o tutorial do link https://basedosdados.github.io/mais/access_data_packages/, ao tentar importar o pacote `basedosdados recebo` a mensagem de erro: 

```ModuleNotFoundError: No module named 'loguru'```

**Reproduzir**
Passos para reproduzir o comportamento:

1. Instale o pacote base de dados ```pip install basedosdados```
2. Importe o pacote base dos dados ```import basedosdados as bd```

**Comportamento esperado**
O pacote deveria ser importado sem erro. Talvez esteja faltando a dependencia 'loguru'

**Desktop (preencha as seguintes informações):**
  - SO: Windows 11

**Comment by phgmacedo** [comment]
Ao instalar manualmente a dependencia `loguru` o erro desaparece.

**Comment by d116626** [comment]
Fix in #1166
