### ISSUE TITLE
[infra] Table-aprove: google.api_core.exceptions.BadRequest 

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/mais#1165]
**Descrição:**

```
google.api_core.exceptions.BadRequest: 400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/***staging/datasets/br_inep_saeb_staging/tables/aluno_ef_9ano?prettyPrint=false: Partition keys modification is not allowed. The update will add or remove partition keys. Current partitions are: [ano, sigla_uf], updated partitions are: []. Please try updating the table with all the partition keys with correct types.
```

Exemplos:

[br_inep_saeb.aluno_ef_9ano](https://github.com/basedosdados/mais/runs/5632702442?check_suite_focus=true)

[br_inep_saeb.proficiencia](https://github.com/basedosdados/mais/runs/5632976846?check_suite_focus=true)

Erro parecido aqui. 

[br_inep_saeb.dicionario](https://github.com/basedosdados/mais/runs/5578255609?check_suite_focus=true)

**Comment by d116626** [comment]
Fix in #1166
