### ISSUE TITLE
[infra] Erro de credentials no Colab

### ISSUE THREAD

**Issue by lucasnascm** [basedosdados/mais#1172]
**Descrição**

Utilizando a API no Colab, dps de rodar 
```
!pip install basedosdados
import basedosdados as bd
query = 'SELECT id_municipio, nome FROM basedosdados.br_bd_diretorios_brasil.municipio WHERE sigla_uf = "SP"'
sp_municipio = bd.read_sql(query, billing_project_id='PROJECT')
sp = pd.merge(sp, sp_municipio, how='left', left_on='ds_municipio', right_on='nome')
```

No link de autorização, o resultado é essa [página](http://localhost:8081/?state=PGrsPjQOATUq5MnbcHKKKwJEu02ocZ&code=4/0AX4XfWin1Cf_YdA3mwBkN3eb9JCg1d2ZZMF7W_8H8UR0E2F0HfC3MI3d_wQoxbebPIrP3A&scope=https://www.googleapis.com/auth/cloud-platform)

Não acredito que seja necessariamente problema nosso, talvez instabilidade do Cloud, mas...

**Comment by lucascr91** [comment]
Questão resolvida no PR #1288. Use versão `1.6.5-b3` para a autenticação funcionar corretamente.
