### ISSUE TITLE
python-client: permitir que download exporte diretamente para disco

### ISSUE THREAD

**Issue by aguiarandre** [basedosdados/mais#119]
Pelo que entendi a função `.download()` carrega a query/table para a memória (`job.to_dataframe()`) e a seguir salva em disco (`dataframe.to_csv()`). 

Para bases de dados muito grandes, seria mais rápido (e, por vezes, a única saída) exportar o dado em algum formato (csv, avro, etc) e fazer o download diretamente para o disco (sem passar por um dataframe em memória).

Talvez eu precise entender melhor como estão organizando em termos de buckets, design e aí posso contribuir... mas, só pra deixar registrado, acredito que a estratégia para fazer isso seria [exportar a base para um bucket](https://cloud.google.com/bigquery/docs/exporting-data#exporting_table_data) e depois fazer o [download do arquivo desse bucket](https://cloud.google.com/storage/docs/downloading-objects#storage-download-object-python).

**Comment by JoaoCarabetta** [comment]
De fato é um problema que a gente não tinha considerado.

Gostei da estratégia de baixar para um bucket e depois baixar do bucket. 

Mas, idealmente, o usuário baixaria para um bucket próprio. Por duas razões: (1) não queremos dar acesso de escrita no nosso bucket para qualquer um; (2) não queremos arcar com o custo de armazenamento e acesso do resultado da query.

Dito isso, acho que é possível implementar essa pipeline direto na função [download](https://github.com/basedosdados/mais/blob/3b642871de54740b9a84a869e61778d9f8951b65/basedosdados/download.py#L5)

Para desenvolver local basta rodar

```
make create-env
. .mais/bin/activate
python setup.py develop
```

**Comment by JoaoCarabetta** [comment]
Tu acha que consegue fazer esse PR? Se precisar de alguma ajuda chega no grupo do Whatsapp

**Comment by aguiarandre** [comment]
Boa, faz todo sentido todos os pontos sobre os buckets! 

Acho que consigo. Seria até bom pra eu ver como contribuir de maneira efetiva por aqui.

Fiz um mvp por aqui e deu certo (em termos de código). A forma como pensei foi criar um bucket temporário, um arquivo temporário (ambos no próprio usuário) pra depois deletar. Algo como: 

```python
hash_id = str(hash(time.time()))
tmp_file_name = table_id + '_' + hash_id
tmp_bucket_name = dataset_id + '_' + hash_id

# create temporary bucket
create_bucket_class_location(tmp_bucket_name)

# move table to bucket 
move_table(project, dataset_id, table_id, destination_uri)

# download file from bucket to disk
download_blob(tmp_bucket_name, tmp_file_name, file_path)

# delete temporary bucket
delete_bucket(tmp_bucket_name)
```

Vou entrar no grupo de whatsapp sim! Acho que as maiores questões são no sentido de design ou se faz sentido em termos de autenticação (porque talvez isso traga um pouco mais de dificuldade pro usuário né?). 

Depois testo também um pouco a performance com bases maiores e coloco aqui.

**Comment by JoaoCarabetta** [comment]
Muito bom!

A gente está repensando deixar o processo de autenticação o mais fácil possível. A maneira como está agora é ruim para usuários sem muito domínio de python/bash. Então, acho que vamos implementar aquela autenticação via browser como default, e deixar a autenticação via json para usuários avançados.

Acho que a ideia de bucket temporário é uma boa. Talvez poderíamos adicionar a opção de baixar para um bucket não temporário do usuário também. Assim ele pode ter o resultado da query salvo.

**Comment by JoaoCarabetta** [comment]
Acho que já pode aproveitar e fechar o issue #68 também

**Comment by rdahis** [comment]
Fechando porque a #123 já matou o issue.
