### ISSUE TITLE
[dados] Falta o `id_municipio` de alguns municípios, independente do turno.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#1205]
Para reproduzir:
```R
bdplyr("br_tse_eleicoes.resultados_candidato_secao") %>% 
  filter(ano == 2018,
         cargo == "presidente",
         turno == 1,
         is.na(id_municipio)) %>% 
  select(ano,turno, cargo, zona, secao,id_municipio, id_municipio_tse, sigla_partido, votos) %>%
  distinct(id_municipio_tse)
```

Apontado por @brunomioto.

**Comment by brunomioto** [comment]
Não testei opções além de `ano == 2018` e `cargo == presidente`. Talvez seja algo independente desses termos

**Comment by rdahis** [comment]
Pela discussão no Discord, parece que não é um bug. A questão é que o TSE tem ID próprio para países e municípios de fora do Brasil. Portanto não cruzam com o diretório de municípios brasileiros.
