### ISSUE TITLE
[infra] Cliente poder ler um csv/excel com descrições de variáveis direto pro table_config.yaml

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#121]
Vai poupar muito tempo para tabelas com muitas colunas (ex. Censo, Atlas do Desenvolvimento Humano, etc).

**Comment by JoaoCarabetta** [comment]
Tem uma proposta da estrutura do documento?


Talvez essa:
```
column_name, description
bla, ble
```

**Comment by rdahis** [comment]
Estrutura pode ser essa. Um csv simples com duas colunas.

No CLI pode ser

`basedosdados table init[create] --column_descriptions 'path/to/file'`

Idealmente ele seria inteligente pra checar que todas as colunas do `descriptions.csv` estão no header da tabela. A outra direção não precisa valer (pode ter colunas na tabela sem descrição em `descriptions.csv`.
