### ISSUE TITLE
project_id não está sendo considerado na função read_table

### ISSUE THREAD

**Issue by aguiarandre** [basedosdados/mais#122]
Apesar de existir o argumento `project_id` na função `read_table`, ele não está sendo utilizado ao 

```python
table = read_table(dataset_id, table_id, limit=limit)
```

Acredito que basta alterar para:
```python
table = read_table(dataset_id, table_id, project_id, limit=limit)
```
já que a função `read_table` tem o argumento `project_id` como opcional, com valor default `project_id='basedosdados'`.

**Comment by fernandascovino** [comment]
@aguiarandre o que seria exatamente não estar sendo utilizado? quando você passa  `table = read_table(dataset_id, table_id, limit=limit)` ele não puxa a tabela?

aqui está funcionando!

<img width="985" alt="Screen Shot 2020-10-22 at 00 00 27" src="https://user-images.githubusercontent.com/20743819/96819380-d2d6a980-13f9-11eb-8b96-f110f072a9c0.png">

**Comment by fernandascovino** [comment]
lendo aqui no PR https://github.com/basedosdados/mais/pull/123 , já encaminhado ne? :)

**Comment by aguiarandre** [comment]
Oi Fernanda! Bom dia.

Sim, acho que já está encaminhado por ali. Se não me engano `project_id` era um argumento de `read_table`, mas não era passado dentro de `read_sql`. Mas como já estava mexendo já no `download`, acabei abrindo essa issue só pra ficar registrado que estava corrigindo :)

**Comment by fernandascovino** [comment]
closed by #123
