### ISSUE TITLE
Base: SAEB/Inep

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#124]
Abrindo um issue pra coordenar subir dados do Inep. Vamos começar com o SAEB de teste?

Marcando @paeselhz por enquanto. Estão rolando conversas e podemos coordenar um "time Inep".

Dataset: `br_inep_saeb`
Tabelas: `microdados`

Dados: http://inep.gov.br/web/guest/microdados
Anos SAEB: 1995, 1997, 1999, 2001, 2003, 2005, 2011, 2013, 2015, 2017
Anos Prova Brasil: 2007, 2009, 2011

Nossa documentação para tratar e subir dados ainda está incompleta, então vou apontar algumas direções:
- Temos padrões de nomeação de variáveis, tratamento de strings, números, datas e valores nulos. Vou estruturar na documentação e já ligo aqui.
- Idealmente teríamos uma grande base com todos os anos e colunas compatibilizadas. Se não for possível (por exemplo se tiverem muitas colunas mudando entre anos), a 2a opção é subir tabelas diferentes (ex. microdados_1995, microdados_1997, etc).
- Objetivo é só modificar os dados originais para limpeza e integração.
- Normalizamos as bases para ter sempre um conjunto de colunas que identifique unicamente cada linha e sem valores nulos.

@paeselhz pode dar um resumo do que você já tem pronto de código? Se tiver link para tudo é ainda melhor. Tem código para todos os anos já? Caso não, é mais fácil limpar alguns anos do que outros?

**Comment by paeselhz** [comment]
Pessoal, embora tenhamos combinado que a prioridade é o Censo Escolar (e por estar mais padronizado seria mais fácil a ingestão), gostaria de deixar aqui um repositório onde faço (em R) o download e a leitura dos microdados do SAEB para os anos de 1997 a 2005. É bem dificil encontrar um padrão neles, mas podemos pensar em algo a ser feito. (os TXT são delimitados por tamanho de cada variável, por isso existe um "dicionário de tamanhos").
https://github.com/paeselhz/microdados_saeb_ate_2005
Por enquanto só tem códigos até 2001, mas pretendo ainda hoje adicionar os de 2003 e 2005 que estão faltando.

**Comment by rdahis** [comment]
Fechando esse issue por enquanto para priorizarmos o Censo Escolar.
