### ISSUE TITLE
Base: Censo Escolar / Inep

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#125]
(Repetindo +/- o texto do issue #124)

Dataset: `br_inep_censo_escolar`
Tabelas: `microdados`

Dados: http://inep.gov.br/web/guest/microdados
Anos: 1995-2019

Nossa documentação para tratar e subir dados ainda está incompleta, então vou apontar algumas direções:

- Temos padrões de nomeação de variáveis, tratamento de strings, números, datas e valores nulos. Vou estruturar na documentação e já ligo aqui.
- Idealmente teríamos uma grande base com todos os anos e colunas compatibilizadas. Se não for possível (por exemplo se tiverem muitas colunas mudando entre anos), a 2a opção é subir tabelas diferentes (ex. microdados_1995, microdados_1997, etc).
- Objetivo é só modificar os dados originais para limpeza e integração.
- Normalizamos as bases para ter sempre um conjunto de colunas que identifique unicamente cada linha e sem valores nulos.

@paeselhz pode dar um resumo do que você já tem pronto de código? Se tiver link para tudo é ainda melhor. Tem código para todos os anos já? Caso não, é mais fácil limpar alguns anos do que outros?

**Comment by fernandascovino** [comment]
Boa! As bases parecem mudar de variáveis com frequência entre os anos. Mesmo sendo indicado quais saíram/entraram, talvez valha deixar separado. Pelo que o @paeselhz falou e o Adriano também, a partir de 2007/2009 as bases são mais padronizadas - dependendo do quão complexo for antes, é mais fácil começarmos por aí.

**Comment by paeselhz** [comment]
Isso aí! Antes de 2007 os dados vêm agrupados por unidade escolar, não tem os microdados para cada aluno individualmente... Até podemos pensar em carregar os dados anteriores a isso, mas deixamos claro a divisão que existe entre os dados pré-2007 e pós-2007.
Estou montando um dicionário com os tipos de cada coluna nos CSVs, pra gente carregar o dado conforme é esperado. E com isso depois podemos construir um "de-para" das variáveis ao longo dos anos.

**Comment by paeselhz** [comment]
Pessoal, estou terminando de realizar a leitura dos dados originais e salvando eles em Parquet em um bucket no Google Cloud Storage... O repositório com os dados (e o dicionário das variáveis) está aqui: https://github.com/paeselhz/microdados_censo_escolar

Ainda não fiz nenhum processamento dos dados para padronizar coisas como nome das variáveis ao longo dos anos... Não sei também se é essa a intenção

**Comment by fernandascovino** [comment]
@paeselhz quer conversar para organizarmos as bases? lembro que algumas colunas mudam de nomenclatura ao longo do tempo, entram novas colunas e alguns códigos também né?

posso ajudar montar esse de-para das colunas, vamos colocar numa tabela? se vermos que algum ano tem muita mudança podemos quebrar a partir dele também. se não, podemos padronizar para a nomenclatura + recente :)

**Comment by rdahis** [comment]
Fechando por enquanto.
