### ISSUE TITLE
[dados] fundacao_lemann_imagens_dashboards

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/mais#1251]
Issue para subir as imagens a serem adicionadas nos dashboards da Fundação Lemann

**Comment by laura-l-amaral** [comment]
![Liderancas_do_Setor_Publico](https://user-images.githubusercontent.com/100051996/176585308-340c92a8-6128-4d1f-8b56-628f88a1e9df.png)

**Comment by nayaramrsc** [comment]
![Mais Líderes](https://user-images.githubusercontent.com/88157499/183140931-bd5bd2aa-d36c-4b76-bad0-44258248a7f0.svg)
![Ensino Fundamental II](https://user-images.githubusercontent.com/88157499/183140147-f37540ff-df58-4e26-9273-185e2ddcd736.svg)
![Lideranças do Setor Público](https://user-images.githubusercontent.com/88157499/183140696-290aea11-11e2-426a-b924-52c46903acb8.svg)
