### ISSUE TITLE
[infra] Erro ao usar o código do R para dados do DOU ( R)

### ISSUE THREAD

**Issue by JaquelineB06** [basedosdados/mais#1254]
Ao tentar realizar a consulta diretamente no R, dá o erro colocado abaixo.
```
query <- bdplyr("br_imprensa_nacional_dou.secao_1")
df <- bd_collect(query)

Error in `bdplyr()`:
! The table basedosdados.br_imprensa_nacional_dou.secao_1 doesn't have a valid name or was not found at basedosdados.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by pedrocava** [comment]
@JaquelineB06, posso te pedir alguns sanity checks para a gente entender melhor o que aconteceu?

- Roda o mesmo código, se receber o mesmo erro rode `rlang::last_trace()` e traz o resultado aqui por favor?
- Rodar:

```r
basedosdados::query("SELECT * FROM br_imprensa_nacional_dou.secao_1")
```

Caso dê erro, traga o resultado de `rlang::last_trace()` também. 
- Instalar o pacote `sessioninfo`, rodar `sessioninfo::session_info()` e trazer o resultado.

**Comment by pedrocava** [comment]
Posso te pedir para autenticar e tentar de novo o mesmo processo? Meu palpite é que sua conta google tá em outro projeto. O nome da tabela tá certo e como não está acessível nem com `query` nem com `bdplyr`, me resta pensar que tá no schema/dados disponíveis para sua conta. O [gargle](https://gargle.r-lib.org/index.html) tem ferramentas para autenticar na API do google. Na próxima versão vamos ter funções dentro do `basedosdados` para isso.

**Comment by pedrocava** [comment]
Notei um problema que não acredito que esteja relacionado com essa issue, mas só para cobrir toda possibilidade vale conferir. Sua instalação do `rJava` está corrompida. Tenta reinstalar.

**Comment by JaquelineB06** [comment]
De fato, o problema estava na conta google, de permitir acesso ao projeto. Consegui aqui. Muito obrigada ;)
