### ISSUE TITLE
Documentação de referência da API Python

### ISSUE THREAD

**Issue by fernandascovino** [basedosdados/mais#126]
- [ ] Criar estrutura de organização
- [ ] Verificar docstrings para documentação automatica no mkdocs
- [ ] Adicionar comandos, funções e descrições: https://pandas.pydata.org/pandas-docs/stable/reference/io.html
- [ ] Incorporar minitutorial do @aguiarandre

**Comment by JoaoCarabetta** [comment]
- google style. https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html
- mkdocstrings https://pawamoy.github.io/mkdocstrings/
