### ISSUE TITLE
Adicionar contribuidor@s no README! 💚✨

### ISSUE THREAD

**Issue by fernandascovino** [basedosdados/mais#128]
- [x] Ver: https://allcontributors.org/docs/en/overview
- [x] Add core team
- [ ] Criar regras de contribuição para badges! @rdahis --> podemos montar um .md aqui com as missões para ganhar cada emoji hahha

**Comment by fernandascovino** [comment]
@all-contributors please add @JoaoCarabetta for ideas, code, review and data

@all-contributors please add @rdahis for ideas, blog, review and data

@all-contributors please add @JoaoCarabetta for ideas, docs, review and data

@all-contributors please add @polvoazul for ideas, code, review and infrastructure

**Comment by fernandascovino** [comment]
@all-contributors please add @JoaoCarabetta for ideas, code, review and data; please add @rdahis for ideas, blog, review and data; please add @JoaoCarabetta for ideas, docs, review and data; please add @polvoazul for ideas, code, review and infrastructure

**Comment by fernandascovino** [comment]
@all-contributors please add @JoaoCarabetta for ideas, code, review and data

**Comment by fernandascovino** [comment]
@all-contributors please add @rdahis for ideas, blog, review and data

**Comment by fernandascovino** [comment]
@all-contributors please add @fernandascovino  for ideas, docs, review and data

**Comment by fernandascovino** [comment]
@all-contributors please add @polvoazul for ideas, code, review and infrastructure

**Comment by fernandascovino** [comment]
@all-contributors please add @rdahis for ideas, blog, review and data

**Comment by fernandascovino** [comment]
@all-contributors please add @fernandascovino for ideas, docs, review and data

**Comment by fernandascovino** [comment]
@all-contributors please add @JoaoCarabetta for ideas, code, review and data

**Comment by fernandascovino** [comment]
@all-contributors please add @polvoazul for ideas, code, review and infrastructure

**Comment by rdahis** [comment]
Coders:
🐣  PRs auxiliares, bugs
🐥  novas funções, documentação
🐓  código core

Daters:
🌱  1 base
🌿  2-5 bases
☘️  6-10 bases
🌴  11-20 bases
🌳  21+ bases

Fundadores do Mais (cada um escolhe um): 🐙  🦑  🦐  🦀  🐡  🐬  🐋  🐳  🦈

**Comment by fernandascovino** [comment]
boa! sobre daters, base = tabela ou dataset? essa pessoa seria a mantenedora?

eu quero o 🐬 , obviamente @polvoazul é 🦑 , @JoaoCarabetta vai de que ? e @rdahis vai querer 🐋 ?

**Comment by JoaoCarabetta** [comment]
Eu quero  🐡

**Comment by rdahis** [comment]
base = dataset completo (vida dura aqui...)

Sim eu vou de 🐋  !

**Comment by rdahis** [comment]
@all-contributors please add @rdahis for projectManagement, ideas, bug, maintenance, question, blog, review and data

**Comment by d116626** [comment]
@all-contributors please add @d116626 for ideas, code and userTesting

**Comment by JoaoCarabetta** [comment]
@all-contributors please add @JoaoCarabetta for projectManagement, ideas, bug, maintenance, question, review and data

**Comment by d116626** [comment]
@all-contributors please add @d116626 for ideas, review, code, userTesting and bug
