### ISSUE TITLE
[dados] br_bcb_sicor

### ISSUE THREAD

**Issue by folhesgabriel** [basedosdados/mais#1292]
**Metadados da base**

1. Descrição: Microdados do Sistema de Operações do Crédito Rural e do Proagro (Sicor)

2. Qual o nome do conjunto? `br_bcb_sicor`

3. Qual o nome da(s) tabela(s)? `microdados_operacao`  `microdados_saldo` `microdados_liberacao`  `empreendimentos`

4. Fonte original dos dados: <https://www.bcb.gov.br/estabilidadefinanceira/creditorural?modalAberto=tabelas_sicor>

5. Cobertura espacial: Brasil

6. Cobertura temporal: de 2013 a 2022

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template
- [x] Preencher as tabelas de arquitetura
- [x] Escrever código de captura e limpeza de dados.
- [x] Organizar arquivos auxiliares, se necessário.
- [x] Criar tabela dicionário, se necessário.
- [x] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [x] Enviar tudo para revisão.

**Comment by IngridSRabelo** [comment]
O nome do conjunto em `2.` deve ser igual ao nome do seu issue, que é `br_bcb_sicor`. Geralmente, microdados é uma tabela do seu conjunto de dados. As tabelas do ponto `3.` a gente coloca o nome das tabelas mesmo, `br_bcb_sicor_microdados.operacao` sem ser nesse formato. No caso, sugiro que no ponto `3` colocar o nome das suas tabelas `microdados_operacao` ou `operacao`; `microdados_saldo` ou `saldo`; `microdados_liberacao` ou ` liberacao`

**Comment by IngridSRabelo** [comment]
@folhesgabriel

**Comment by folhesgabriel** [comment]
@IngridSRabelo Acabei de realizar as alterações sugeridas! Obg
