### ISSUE TITLE
[dados] br_ms_sivep_gripe

### ISSUE THREAD

**Issue by gabrielcaser** [basedosdados/mais#1295]
**Metadados da base**

1. Descrição: O Ministério da Saúde (MS), por meio da Secretaria de Vigilância em Saúde (SVS), desenvolve a vigilância da Síndrome Respiratória Aguda Grave (SRAG) no Brasil, desde a pandemia de Influenza A(H1N1) desde 2009. A partir disso, a vigilância de SRAG foi implantada na rede de vigilância de Influenza e outros vírus respiratórios, que anteriormente atuava exclusivamente com a vigilância sentinela de Síndrome Gripal (SG). De 2009 até 2018, o sistema oficial para o registo dos casos e óbitos por SRAG era o Sistema de Informação de Agravos de Notificação – Sinan Web Influenza. A partir de 2019, o sistema oficial passou a ser o Sistema de Informação da Vigilância Epidemiológica da Gripe (SIVEP-Gripe).

2. Qual o nome do conjunto? `br_ms_sinan`

3. Qual o nome da(s) tabela(s)? `sivep_gripe`,  `influenza`

4. Fonte original dos dados: [link](https://opendatasus.saude.gov.br/dataset)

5. Cobertura espacial: `br`

6. Cobertura temporal: 2009(1)2022

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template
- [x] Preencher as tabelas de arquitetura
- [x] Escrever código de captura e limpeza de dados.
- [x] Organizar arquivos auxiliares, se necessário.
- [x] Criar tabela dicionário, se necessário.
- [x] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [x] Enviar tudo para revisão.

**Comment by laura-l-amaral** [comment]
closed by basedosdados/queries-basedosdados#158
