### ISSUE TITLE
[dados] world_fifa_womens_world_cup

### ISSUE THREAD

**Issue by gabrielle-carv** [basedosdados/mais#1298]
**Metadados da base**

1. Descrição: A Copa do Mundo de Futebol Feminino da FIFA é um campeonato de futebol feminino realizado a cada quatro anos pela Fédération Internationale de Football Association - FIFA, no qual reúne 32 nações que irão competir no cenário internacional, com vias de qualificação continentais levando a um emocionante evento final.

2. Qual o nome do conjunto? `world_fifa_womens_world_cup`

3. Qual o nome da(s) tabela(s)? `matches`

4. Fonte original dos dados: [FIFA](https://www.fifa.com/tournaments/womens/womensworldcup)

5. Cobertura espacial: World

6. Cobertura temporal: de 1991 a 2019

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template
- [x] Preencher as tabelas de arquitetura
- [x] Escrever código de captura e limpeza de dados.
- [x] Organizar arquivos auxiliares, se necessário.
- [x] Criar tabela dicionário, se necessário.
- [x] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [x] Enviar tudo para revisão.

**Comment by IngridSRabelo** [comment]
Sugiro colocar a descrição em português, mesmo a base sendo em inglês, só para facilitar o entendimento

**Comment by IngridSRabelo** [comment]
@gabrielle-carv
