### ISSUE TITLE
[dados] world_fao

### ISSUE THREAD

**Issue by folhesgabriel** [basedosdados/mais#1324]
**Metadados da base**

1. Descrição: a base é elaborada pela Food Agriculture Organization (FAO) e apresenta dados sobre a produção agropecuária mundial.

2. Qual o nome do conjunto? `world_fao_production`

3. Qual o nome da(s) tabela(s)? `crop_livestock`  `production_indices` `value_agricultural_production` `element` `item` `item_group` `country_group` 

4. Fonte original dos dados: https://www.fao.org/faostat/en/#data/QCL

5. Cobertura espacial: mundial

6. Cobertura temporal: de 1961 a 2020

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template
- [x] Preencher as tabelas de arquitetura
- [x] Escrever código de captura e limpeza de dados.
- [x] Organizar arquivos auxiliares, se necessário.
- [x] Criar tabela dicionário, se necessário.
- [x] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [x] Enviar tudo para revisão.

**Comment by folhesgabriel** [comment]
@gustavoalcantara inclui mais duas tabelas: world_fao_production_indices; world_fao_value_agricultural_production
Seria o caso de trocar o nome da issue para world_fao?

**Comment by gustavoalcantara** [comment]
> @gustavoalcantara inclui mais duas tabelas: world_fao_production_indices; world_fao_value_agricultural_production Seria o caso de trocar o nome da issue para world_fao?

bem colocado. Alterei. 
Lembrando que se você achar melhor, pode abrir um PR pra cada table_id
