### ISSUE TITLE
[dados] Problema com `sequencial`

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#1327]
`resultados_candidato_municipio`: (em outras tabelas de resultado também?)
2000: tudo nulo 
2004 pra frente: foi passado um destring ==> está sem zeros a esquerda

`candidatos`:
tem zeros à esquerda

correto: deixar com zeros a esquerda porque a partir de 2012 muda o length

**Comment by mfagundes** [comment]
A única forma de manter um campo numérico com zeros à esquerda é usá-lo como `string`. No caso do Python, a melhor forma é fazer a conversão de `number` para `string` usando o `zfill`.
