### ISSUE TITLE
[infra] Opção de escolha de credencial

### ISSUE THREAD

**Issue by fernandascovino** [basedosdados/mais#1343]
**Sua solicitação de recurso está relacionada a um problema? Por favor descreva.**
Uso mais de um projeto (dev/staging e de multiplas organizacoes) e preciso mexer manualmente no `config.toml`para setar qual credencial estou usando toda vez que troco de projeto.

**Descreva a solução que você gostaria**
Uma função such as `bd.config.billing_project_id = "rj-smtr-dev"`:

```py
bd.config.<config/runner>_project_id = "rj-smtr-dev"
```

**Descreva alternativas que você considerou**
Nenhuma

**Contexto adicional**
N/A

**Comment by lucascr91** [comment]
feature adicionada na versão 1.6.8
