### ISSUE TITLE
[dados] br_tse_eleicoes

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/mais#1401]
- [ ] Remover ou consertar id_candidato_bd das tabelas de receitas e despesas de produção
- [ ] incluir nome do candidato nas tabelas de resultado ou encontrar uma maneira de fazer chave única entre resultados e candidatos

**Comment by laura-l-amaral** [comment]
Então, testei com o id_candidato do Bolsonaro e ele não puxou nenhuma receita

`SELECT * FROM basedosdados.br_tse_eleicoes.receitas_candidato WHERE ano = 2022 AND id_candidato_bd = '226196'`

Mas realmente com o sequencial funciona bem!
Se não funcionar, tem que tirar o `id_candidato_bd` dessa tabela

**Comment by laura-l-amaral** [comment]
Ah! acabei de perceber que 2022 não tem id_candidato mesmo pq ainda ta com a pipeline ligada

**Comment by laura-l-amaral** [comment]
Chequei aqui sem o `WHERE ano = 2022` e tbm nao ta funcionando :/ Só puxa 4 linhas de receita para esse id_candidato

**Comment by laura-l-amaral** [comment]
Fiz essa query

`SELECT * FROM basedosdados-dev.br_tse_eleicoes.receitas_candidato WHERE ano < 2018  AND nome_candidato  = 'JAIR MESSIAS BOLSONARO'`

Não achei nenhum erro, mas o id_candidato não tá aparecendo pra alguns anos, pelo jeito a tabela original vem com muita informação faltando

**Comment by rdahis** [comment]
É isso mesmo. Não tem o `id_candidato_bd` pra todos os anos nesses dados.
