### ISSUE TITLE
br-me-siconfi Dados com unidades incorretas em 1990, 1991, 1992 e 1993

### ISSUE THREAD

**Issue by cristiano1br** [basedosdados/mais#1426]
Prezados,

Informo que os dados referentes aos anos 1990, 1991, 1992 e 1993, das despesas e receitas foram originalmente fornecidos em milhares sendo necessário a multiplicação dos valores desses anos por mil. 

Vejam o gráfico da evolução anual de um município com e sem a transformação:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/7329551/203087782-45d2f1ba-291e-415e-ae58-21f17824919f.png">

<img width="503" alt="image" src="https://user-images.githubusercontent.com/7329551/203087880-0c13df8e-4114-4599-946d-d3012e720c66.png">

Fonte: [Séries Temporais para Estudos Históricos da Execução Orçamentária Municipal pós-1989](https://repositorio.enap.gov.br/bitstream/1/6925/1/2.6.%20XI%20Pr%C3%AAmio%20SOF.pdf)   pag 33

**Comment by rdahis** [comment]
@laura-l-amaral pode sempre alocar a issue às pessoas mais responsáveis. Nesse caso a @crislanealves e eu!

**Comment by rdahis** [comment]
Já resolvemos isso? @crislanealves

**Comment by rdahis** [comment]
@cristiano1br tem a query que rodou para gerar esse gráfico? O problema se aplica a todas as tabelas de SICONFI municipal?

**Comment by rdahis** [comment]
Subidos hoje os arquivos fazendo essa correção entre 1990 e 1993.
