### ISSUE TITLE
[dados] world_ti_cpi

### ISSUE THREAD

**Issue by gustavoalcantara** [basedosdados/mais#1441]
**Metadados da base**

1. Descrição: <descrição da base e suas tabelas>
Corruption Perception Index.

2. Qual o nome do conjunto? `dataset_id`
world_ti

3. Qual o nome da(s) tabela(s)? `table_id`
cpi

4. Fonte original dos dados: <link>
https://www.transparency.org/en/cpi/2021

5. Cobertura espacial: <país/sigla_uf>
world

6. Cobertura temporal: de XXXX a YYYY
2010 a 2021

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template e os dados originais
- [x] Preencher as tabelas de arquitetura - Marcar a equipe de dados na issue avisando quando finalizar
- [x] Escrever código de captura e limpeza de dados
- [x] Organizar arquivos auxiliares, se necessário
- [x] Criar tabela dicionário, se necessário
- [x] Subir tabelas no BigQuery
- [x] Criar e preencher table_config e dataset_config
- [x] Fazer uma revisão seguindo o [nosso guia](https://github.com/basedosdados/.github/wiki/Dados#como-fazer-code-review)
- [x] Abrir o PR

**Comment by gustavoalcantara** [comment]
tabela de arquitetura: https://docs.google.com/spreadsheets/d/1sSnlkog9el1--WZQwNHv9TW8G_M73cfB/edit#gid=1139321926

**Comment by laura-l-amaral** [comment]
@gustavoalcantara coloca uma amostra dos dados junto com a arquitetura querido?

**Comment by laura-l-amaral** [comment]
closed by #1460
