### ISSUE TITLE
[dados] br_ibge_estadic

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/mais#1443]
**Metadados da base**

1. Descrição: Levantamento pormenorizado de informações sobre a estrutura, a dinâmica e o funcionamento das instituições públicas estaduais.

2. Qual o nome do conjunto? `br_ibge_estadic`

3. Qual o nome da(s) tabela(s)? 
* `recursos_humanos`
* `comunicacao_informatica`
* `governanca`
* `politica_mulher`

4. Fonte original dos dados: <https://www.ibge.gov.br/estatisticas/sociais/protecao-social/16770-pesquisa-de-informacoes-basicas-estaduais.html?edicao=25509&t=downloads>

5. Cobertura espacial: <sigla_uf>

6. Cobertura temporal: de 2012 a 2020

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template e os dados originais
- [x] Preencher as tabelas de arquitetura - Marcar a equipe de dados na issue avisando quando finalizar
- [ ] Escrever código de captura e limpeza de dados
- [ ] Organizar arquivos auxiliares, se necessário
- [x] Criar tabela dicionário, se necessário
- [x] Subir tabelas no BigQuery
- [x] Criar e preencher table_config e dataset_config
- [x] Fazer uma revisão seguindo o [nosso guia](https://github.com/basedosdados/.github/wiki/Dados#como-fazer-code-review)
- [x] Abrir o PR

**Comment by gabrielle-carv** [comment]
As tabelas de arquitetura:
`recursos_humanos` : https://docs.google.com/spreadsheets/d/1ahUtS9wvB-dGSMjjWiCggoMdjZmrLwoS/edit?usp=sharing&ouid=112833062792973352311&rtpof=true&sd=true
`comunicacao_informatica` : https://docs.google.com/spreadsheets/d/19AYtFaJfcDJdQl_g36bYK3xv-ZV-T1fH/edit?usp=sharing&ouid=112833062792973352311&rtpof=true&sd=true
`governanca` : https://docs.google.com/spreadsheets/d/1G0LAZkJqNnDVBdvZKMPrWQjza09dKV-hR1oeTSsesFY/edit?usp=sharing
`politica_mulher` : https://docs.google.com/spreadsheets/d/1V2LH3nAkdd5UbUW7BuGkijnMZMygvdPJ5PObh0nac54/edit?usp=sharing

**Comment by gabrielle-carv** [comment]
`recursos_humanos` : https://docs.google.com/spreadsheets/d/1ahUtS9wvB-dGSMjjWiCggoMdjZmrLwoS/edit?usp=sharing&ouid=112833062792973352311&rtpof=true&sd=true
`comunicacao_informatica` : https://docs.google.com/spreadsheets/d/19AYtFaJfcDJdQl_g36bYK3xv-ZV-T1fH/edit?usp=sharing&ouid=112833062792973352311&rtpof=true&sd=true
`governanca`: https://docs.google.com/spreadsheets/d/1G0LAZkJqNnDVBdvZKMPrWQjza09dKV-hR1oeTSsesFY/edit?usp=sharing
`politica_mulher`: https://docs.google.com/spreadsheets/d/1V2LH3nAkdd5UbUW7BuGkijnMZMygvdPJ5PObh0nac54/edit?usp=sharing
