### ISSUE TITLE
[dados] br_cnj_estatisticas_poder_judiciario

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/mais#1446]
**Metadados da base**

1. Descrição: <descrição da base e suas tabelas>

2. Qual o nome do conjunto? ` br_cnj_estatisticas_poder_judiciario`

3. Qual o nome da(s) tabela(s)? `recursos_financeiros`

4. Fonte original dos dados: <[link](https://www.cnj.jus.br/pesquisas-judiciarias/justica-em-numeros/base-de-dados/)>

5. Cobertura espacial: <país/sigla_uf>

6. Cobertura temporal: de 2009 a 2021

7. Arquitetura: https://docs.google.com/spreadsheets/d/1RqfdiMjPfRWRGWEhlkRv9Lb9Bocjlspe/edit#gid=884186114 

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template e os dados originais
- [x] Preencher as tabelas de arquitetura - Marcar a equipe de dados na issue avisando quando finalizar
- [x] Escrever código de captura e limpeza de dados
- [x] Organizar arquivos auxiliares, se necessário
- [x] Criar tabela dicionário, se necessário
- [x] Subir tabelas no BigQuery
- [x] Criar e preencher table_config e dataset_config
- [x] Fazer uma revisão seguindo o [nosso guia](https://github.com/basedosdados/.github/wiki/Dados#como-fazer-code-review)
- [x] Abrir o PR

**Comment by arthurfg** [comment]
Tabela de arquitetura pessoal: [(https://docs.google.com/spreadsheets/d/1RqfdiMjPfRWRGWEhlkRv9Lb9Bocjlspe/edit#gid=884186114)](url)
@basedosdados/dados

**Comment by arthurfg** [comment]
> Qual a fonte original desses dados? Tem o link?

Têm sim: https://www.cnj.jus.br/pesquisas-judiciarias/justica-em-numeros/base-de-dados/
Essa base será usada na parceria com a república. A fonte original tem cerca de 2000 colunas, pq cobre todos os indicadores do sistema de estatística do poder judiciário. A idéia é dividir o dataset em tabelas, por área, seguindo essa metodologia: https://atos.cnj.jus.br/files/Anexo_Justica_Federal.pdf

Então seria uma tabela de `recursos_financeiros`, outra de `recursos_humanos` e etc..
Para o projeto da república a Gabs só vai precisar dos indicadores que estão nessa parte de recursos financeiros, então demos prioridade p/ ela.

**Comment by laura-l-amaral** [comment]
@arthurfg e @gabrielle-carv se quiserem rever o nome do conjunto eu dei esse nome sem pensar muito, pra entregar o board antes da reunião de BD core. Pensei em algumas alternativas, só queria jogar aqui pra vcs verem se acham alguma delas melhor do que `br-cnj-estatisticas`:
- `br-cnj-justica-numeros`
- `br-cnj-poder-judiciario`
