### ISSUE TITLE
[dados] br_rj_tce_iegm

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/mais#1447]
**Metadados da base**

1. Descrição: Índice de Efetividade da Gestão Municipal

2. Qual o nome do conjunto? `br_rj_tce_iegm`

3. Qual o nome da(s) tabela(s)? `microdados`

4. Fonte original dos dados: <[link](https://www.tcerj.tc.br/portalnovo/pagina/f387dc97-eeea-4077-ab43-08d63dc9a888)>

5. Cobertura espacial: <sigla_uf>

6. Cobertura temporal: 2019

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template e os dados originais
- [x] Preencher as tabelas de arquitetura - Marcar a equipe de dados na issue avisando quando finalizar
- [x] Escrever código de captura e limpeza de dados
- [x] Organizar arquivos auxiliares, se necessário
- [x] Criar tabela dicionário, se necessário
- [x] Subir tabelas no BigQuery
- [x] Criar e preencher table_config e dataset_config
- [x] Fazer uma revisão seguindo o [nosso guia](https://github.com/basedosdados/.github/wiki/Dados#como-fazer-code-review)
- [x] Abrir o PR

**Comment by gabrielle-carv** [comment]
[Arquitetura](https://docs.google.com/spreadsheets/d/1Bzjzcb6jM-wNcEoHNdDLIm562PU5fuVpnVpSjXYRSlY/edit#gid=0)
