### ISSUE TITLE
[infra] dúvida sobre  funcionamento do table_approve

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/mais#1480]
Pelo que eu entendi do funcionamento do nosso github, quando fechamos o PR e roda o `tabble_approve `ele monta o schema da tabela de `basedosdados-staging` e o schema da tabela que vai pro `basedosdados` em cima do arquivo do `table_config`. 

Assim, o arquivo que subimos no storage que monta a tabela de staging em `basedosdados-dev` tem que ter um cabeçalho idêntico ao `table_config`  para que o `tabble_approve` rode sem problemas, caso o contrario o schema da tabela de staging ou de prod quebra e o dado não vai para produção. 

Por conta disso não podemos mexer em nada as colunas no arquivo de `publish.sql`, nem renomear nem reordenar, apenas mudamos os tipos do BQ. 

Percebi que anteriormente não era assim que o nosso projeto funcionava pois os arquivos de `publish.sql` faziam alterações nas tabelas.

Existem algumas vantagens importantes em poder fazer alterações na ordem ou nome das colunas no arquivo de `publish.sql`. 

Como exemplo, semana passada a ingrid precisou subir novamente o censo escolar inteiro por que havia errado o nome de uma coluna e ele demora algumas horas para subir. Se pudessemos alterar o `publish.sql` o problema seria solucionado em minutos

Outro exemplo que tive de dificuldade por conta dessa estrutura foi na atualização da tabela de local de votação do tse que o joão me pediu pra fazer. Não foi possível subir ela pelo fluxo normal uma vez que os tipos geográficos da tabela eram feitos combinando colunas no arquivo `publish.sql`.

Não sei se quando o `table_approve` foi montado ele tinha esse objetivo de garantir que os arquivos em csv do storage fossem idênticos as tabelas finais no BQ. 
Se não foi o caso, gostaria que pudéssemos rever os códigos do `table_approve` para ajustar isso. 
Se foi, gostaria de reabrir essa discussão pq me parece útil que a gente possa mexer nas tabelas no `publish.sql`

Obrigada pela atenção e desculpa o textão hehe

**Comment by d116626** [comment]
O problema com o `table_approve` é que ele n consegue rodar apenas a etapa do `basedosdados.upload.table.publish` teria que fazer outra action ou via materialização. Prefiro a segunda opção e é relativamente simples, da pra rodar modelos (publish.sql) via interfacie gráfica do prefect, é rapido, fácil e da pra fazer a qualquer hora.
