### ISSUE TITLE
Error in `basedosdados::bdplyr()` R

### ISSUE THREAD

**Issue by isabellameyer** [basedosdados/mais#1493]
Olá, sou nova usando o pacote. 
Quando rodo:

> id_projeto <- "id"
> basedosdados::set_billing_id(id_projeto)
Recebo:
Project keys set successfully

Porém, quando rodo:
> tabela_db <- "br_ibge_ppm.efetivo_rebanhos"
> rebanho_tbl <- basedosdados::bdplyr(tabela_db)
Recebo: 
Error in `basedosdados::bdplyr()`:
! The table basedosdados.br_ibge_ppm.efetivo_rebanhos doesn't have a valid name or was not found at basedosdados.

Não sei o que pode estar acontecendo. Já realizei o downgrade do dbplyr.

**Comment by arthurfg** [comment]
Oi @isabellameyer, tudo bem? Você fixou o projeto da BD no seu BigQuery? Aqui um gif mostrando como fazer: https://basedosdados.github.io/mais/images/bq_access_project_new.gif

**Comment by gustavoalcantara** [comment]
Além disso @isabellameyer, verifique essa documentação: https://basedosdados.github.io/mais/api_reference_r/
