### ISSUE TITLE
[infra] <Pacote R - Expected OAuth 2 access token, login cookie or other valid authentication credential

### ISSUE THREAD

**Issue by tallysfeldens** [basedosdados/mais#1496]
Olá pessoal, obrigada desde já por essa ferramenta que vocês desenvolveram.

Estou com um problema de credenciais. Já tive o erro de autenticação e o erro da versão do pacote R, e os dois foram solucionados.
Eu gerei minha query, e ao dar o comando bd_collect, ele começa a rodar e depois para por ter identificado este erro aqui:

install.packages("basedosdados")
library(basedosdados)
# Defina o seu projeto no Google Cloud
set_billing_id("pharma-pricing")
> # Para carregar o dado direto no R
> query <- bdplyr("br_ms_cnes.estabelecimento")
Successfully connected to table `basedosdados.br_ms_cnes.estabelecimento`.
> df <- bd_collect(query)
Running job 'pharma-pricing.job_xhF9hPnhVlvgXEumfc979qj1KJvp.US' [\] 23s
Complete
Billed: 22.36 GB
Downloading first chunk of data.
Received 10,183 rows in the first chunk.
Downloading the remaining 47,926,222 rows in 6276 chunks of (up to) 7,637 rows.
Downloading data [=====>-------------------------------------------------]  11% ETA:  5h Error in `signal_reason()`:
! Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project. [authError] 
Run `rlang::last_error()` to see where the error occurred.

Alguém tem alguma pista do que posso fazer?

**Comment by gustavoalcantara** [comment]
oi 
envia o que aparece no console usando `rlang::last_error()` , por favor
valeu!

**Comment by tallysfeldens** [comment]
Error in `signal_reason()`:
! Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project. [authError] 
---
Backtrace:
 1. basedosdados::bd_collect(query)
 7. bigrquery (local) `<fn>`(`<named list>`)
 8. bigrquery:::bq_check_response(...)
 9. bigrquery:::signal_reason(json$error$errors[[1L]]$reason, json$error$message)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/bigrquery_authError>
Error in `signal_reason()`:
! Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project. [authError] 
---
Backtrace:
     x
  1. +-basedosdados::bd_collect(query)
  2. | \-.lazy_tbl %>% dplyr::select(dplyr::everything()) %>% dplyr::collect()
  3. +-dplyr::collect(.)
  4. +-bigrquery:::collect.tbl_BigQueryConnection(.)
  5. | \-bigrquery::bq_table_download(...)
  6. |   \-curl::multi_run(pool = pool)
  7. \-bigrquery (local) `<fn>`(`<named list>`)
  8.   \-bigrquery:::bq_check_response(...)
  9.     \-bigrquery:::signal_reason(json$error$errors[[1L]]$reason, json$error$message)
 10.       \-rlang::abort(message, class = paste0("bigrquery_", reason))

**Comment by gustavoalcantara** [comment]
Oi Tallys. Desculpe a demora. Estava de recesso do final de ano e voltei agora. A gente tá no processo de corrigir algumas coisas no pacote... Você está rodando localmente o pacote, né? Se possível, veja essa documentação: https://basedosdados.github.io/mais/api_reference_r/
Além disso, tente utilizar o pacote no Rcloud, se possível. 
Como o erro é de autenticação aparentemente, fico na dúvida se pode ser algo além do nosso pacote (rbigquery/afins...)
Muito obrigado!
