### ISSUE TITLE
Mudar argumento `partitions` para `is_partition` em Dataset.upload

### ISSUE THREAD

**Issue by fernandascovino** [basedosdados/mais#151]
O nome está dando um entendimento errado do argumento de que devem ser passadas as partições para upload do arquivo.
Porém, o parâmetro serve somente para indicar qual partição no storage a pessoa quer subir um único arquivo.

**Comment by JoaoCarabetta** [comment]
@Hellcassius isso deve ser fácil. Veja aí

**Comment by Hellcassius** [comment]
É no Storage.upload, certo?

**Comment by JoaoCarabetta** [comment]
Isso!
