### ISSUE TITLE
[dados] br_inep_sinopse_estatistica_educacao_basica. municipio_matricula_rede_serie

### ISSUE THREAD

**Issue by IngridSRabelo** [basedosdados/mais#1515]
**Metadados da base**

1. Descrição: Quantidade de matrículas por município, etapa de ensino, rede e série.

2. Qual o nome do conjunto? #1513 

3. Qual o nome da(s) tabela(s)? `municipio_matricula_rede_serie`

4. Fonte original dos dados: [Inep](https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/sinopses-estatisticas)

5. Cobertura espacial: Brasil

6. Cobertura temporal: de 2010 a 2021

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template e os dados originais
- [x] Preencher as tabelas de arquitetura - Marcar a equipe de dados na issue avisando quando finalizar
- [ ] Escrever código de captura e limpeza de dados
- [ ] Organizar arquivos auxiliares, se necessário
- [ ] Criar tabela dicionário, se necessário
- [ ] Subir tabelas no BigQuery
- [ ] Criar e preencher table_config e dataset_config
- [ ] Fazer uma revisão seguindo o [nosso guia](https://github.com/basedosdados/.github/wiki/Dados#como-fazer-code-review)
- [ ] Abrir o PR

**Comment by laura-l-amaral** [comment]
#1639
