### ISSUE TITLE
Migrar features do pacote python

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/mais#1519]
# Overview
- [ ]  Mapear features dependentes (download, validation, metadata)
- [ ] Migrar features
- [ ] Checar se pipelines não estão quebrando

Métodos a serem migrados (os marcados com X não fazem requisições ao banco, mas precisam ser revistos em função do novo formato de metadados)

PR da migração: #1400 

## Download (existem muitas urls hard-coded)

- [ ]  `_dict_from_page` (X)
- [ ]  `list_datasets`
- [ ]  `list_dataset_tables`
- [ ]  `get_dataset_description`
- [ ]  `get_table_description`
- [ ]  `get_table_columns`
- [ ]  `get_table_size`
- [ ]  `search`

## Upload

- [x]  `columns_schema` 
  - https://basedosdados.org/api/3/action/bd_bdm_columns_schema
- [x]  `metadata_schema` (do dataset ou tabela, conforme a requisição)
  - Datasets: https://basedosdados.org/api/3/action/bd_dataset_schema
  - Tabelas: https://basedosdados.org/api/3/action/bd_bdm_table_schema
- [x]  `exists_in_ckan`
  - Tabela: https://basedosdados.org/api/3/action/bd_bdm_table_show?dataset_id=br_sp_alesp&table_id=deputado
  - Dataset: https://basedosdados.org/api/3/action/package_show?id=br-sp-alesp
- [x]  `ckan_metadata_extended`
- [x]  `ckan_metadata` (apenas recebe os metadados do dataset ou, se essa existir, da tabela)
- [x]  `owner_org`
  - https://basedosdados.org/api/3/action/organization_show?id=br-bd
- [x]  `ckan_data_dict`
- [x]  `is_updated` (compara o resultado local com o retornado em `ckan_metadata`)
- [x]  `create`
- [ ]  `validate` (apenas usuário logado)
- [ ]  `publish` (usa o endpoint público `exists_in_ckan` e endpoints privados para criação/atualização)
- [ ]  `local_metadata` (X)
- [x]  `handle_data` (X)
- [x]  `handle_complex_fields` (X)
- [x]  `add_yaml_property`(X)
- [x]  `build_yaml_object` (X)

**Comment by mfagundes** [comment]
- Métodos para autenticação
- Método para buscar a ID de um dataset a partir do slug

Obs: nos testes da classe `Base` optei por inicializá-la em outra pasta de configuração (`.basedosdados_teste`, que deve ser copiada de `.basedosdados`)

**Comment by mfagundes** [comment]
- Alterados os métodos de autenticação para usar GraphQL.

**Comment by mfagundes** [comment]
- criados métodos para buscar dados da api (antigo `ckan_metadata`, agora `api_metadata`
- adicionados alguns campos em `ckan_data_dict`, agora `api_data_dict` [1]
- adicionado método `exists_in_api` (antigo `exists_in_ckan`)
- adicionado método `is_updated` (mantive o nome e deixei comentado o método antigo) 

[1] como o modelo mudou bastante, vários campos precisam de um tratamento especial para se adaptar ao novo modelo e, principalmente, ao GraphQL

**Comment by mfagundes** [comment]
-Método `create()` iniciado, para adiantar a escrita dos `yaml`, ainda que o modelo esteja sendo mudado
- Para manter a similaridade com o CKAN, usei arquivos estáticos com os schemas de dataset, table e column
- Os campos com nomes compostos (em `snake_case` precisam ser trocados para `CamelCase`.
- Será necessário inverter o processo para as Mutations

**Comment by mfagundes** [comment]
Criei um pequeno helper para mudar de `snake_case` para `camelCase` e vice-versa, pois o GraphQL converte os nomes dos campos.

**Comment by mfagundes** [comment]
- criado método para eliminar `edges` e `nodes` da resposta do GraphQL
- refatoradas alguns campos (ainda faltam detalhes no modelo)
- arquivo `yaml` é gerado na atualização, porém na criação os slugs gerados não estão sendo preenchidos

**Comment by mfagundes** [comment]
Observações sobre o commit de 12/02/2023:
- separação das queries em arquivos `.graphql` - deveriam vir do backend?
- erro em query apaga o arquivo local
- trocado, em `dataset_schema` o termo `groups` por `themes`. Isso poderá quebrar os datasets antigos?
- remoção dos hacks para limpar `edges` e `node` em `handle_data`e em `handle_complex_fields`

**Comment by JoaoCarabetta** [comment]
Prioridade: Focar em subir yaml

**Comment by mfagundes** [comment]
- escrita do yaml de datasets está feita (apenas gera a mutation, não toca no banco)
- tabelas e colunas ainda tem complexidades que ainda não consegui resolver, pelas novas formas de relacionamento, a atomicidade necessária para gravar no banco e a mudança de `temporal_coverage`, que deverá incluir a área para cada um.
- criei testes unitários, porém eles não estão determinísticos e ainda precisam de uma instância do Django rodando num endereço local. neles, o processo de gerar, verificar, fazer o "refresh" e solicitar um novo login (usando variáveis de ambiente) estão funcionando)

**Comment by rdahis** [comment]
Podemos fechar?
