### ISSUE TITLE
objeto vazio nos microdados da RAIS, R

### ISSUE THREAD

**Issue by matheco93** [basedosdados/mais#1554]
**Descrição**
O objeto "query" do script que compila os dados da RAIS está vindo vazio

**Reproduzir**
Passos para reproduzir o comportamento:
library("basedosdados")
set_billing_id("ibre012023") # minha billing ID
query <- bdplyr("br_me_rais.microdados_vinculos")
df <- bd_collect(query)

O resultado gerará um tibble 0 x 66.

**Comportamento esperado**
Eu esperava que o script disponibilizado gerasse a tabela com os microdados da RAIS

**Capturas de tela**
<img width="952" alt="image" src="https://user-images.githubusercontent.com/124048994/215756725-982c678a-c8ea-475d-abb9-8cb0cecf4647.png">

**Desktop (preencha as seguintes informações):**
  - SO: Windows 10
  - RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

**Contexto adicional**
Tentei resolver o problema fazendo o downgrade da versão do pacote "dbplyr" para a 2.1.1 conforme sugerido no site de vocês, mas mesmo assim não funcionou.

**Comment by gustavoalcantara** [comment]
Olá. Tudo bem? Se possível, rode o comando
`df<-basedosdados::read_sql('SELECT * FROM br_me_rais.microdados_vinculos LIMIT 100')`  após setar seu billing id.
O `query<-...` tem apresentado problemas. Você pode verificar no PR de número https://github.com/basedosdados/mais/pull/1491
Nos retorne quando possível. Abraços!

**Comment by matheco93** [comment]
Oi, @gustavoalcantara desculpa a minha ignorância, mas era pra eu copiar _ipsis litteris_ , certo? continua crashando... segue print do erro:
<img width="516" alt="image" src="https://user-images.githubusercontent.com/124048994/215855734-cf01a68e-9a8b-47bb-a61f-7ee299f0c706.png">

**Comment by arthurfg** [comment]
@matheco93 fala meu caro, o certo é `df<-basedosdados::read_sql("SELECT * FROM basedosdados.br_me_rais.microdados_vinculos LIMIT 100")`. O gustavo deve ter esquecido

**Comment by matheco93** [comment]
@arthurfg agora sim, meu patrão, muito obrigado! Você trabalha aqui no IBRE com o Considera, ne? se vier ao IBRE terça ou quinta eu te agradeço pessoalmente rsrs

**Comment by arthurfg** [comment]
@matheco93 Como o gustavo disse, estamos com alguns problemas com o `bdplyr()` ultimamente, mas já estamos no processo de resolver. 

O legal do bdplyr() é que  você pode aplicar as manipulações que quiser com verbos do  `dplyr`  ao objeto .lazzy_tbl criado, e os dados só serão carregados na sua sua memória ou disco se você precisar.

Uma maneira de "burlar" o bug é rodar a query com algum filtro ou seleção, como: 

```
query<-bdplyr("br_me_rais.microdados_vinculos") |>
  dplyr::filter(ano == 2013, sigla_uf == "RJ") |>
  dplyr::select(ano, sigla_uf, tipo_vinculo ) |>
  utils::head() ## a rais é pesadinha, por isso o head
  
df <- bd_collect(query) 
```
Outra é com a função read_sql(): 

`df<-basedosdados::read_sql("SELECT * FROM basedosdados.br_me_rais.microdados_vinculos LIMIT 100")`

**Comment by arthurfg** [comment]
> @arthurfg agora sim, meu patrão, muito obrigado! Você trabalha aqui no IBRE com o Considera, ne? se vier ao IBRE terça ou quinta eu te agradeço pessoalmente rsrs


Opa! Trabalho sim! Terça que vem estarei ai
