### ISSUE TITLE
[infra] Descrição dos conjuntos não sobe pro site

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/mais#1556]
**Descrição**
Ao fecharmos os PR's a descrição dos conjuntos não aparece no site

**Reproduzir**
1. Criar um PR com um conjunto que não existe ainda na BD
2. Mergear

**Comportamento esperado**
Que a descrição do conjunto aparecesse no site

**Capturas de tela**
O último conjunto que subimos foi esse aqui 
![image](https://user-images.githubusercontent.com/100051996/215894152-6a55f86f-faca-4e07-8ed1-824a69185449.png)

**Comment by rdahis** [comment]
Podemos fechar, certo?
