### ISSUE TITLE
[dados] br_ans_beneficiario.informacao_consolidada

### ISSUE THREAD

**Issue by tricktx** [basedosdados/mais#1558]
**Metadados da base**

1. Descrição: `O conjunto contém Informações consolidadas de beneficiários por competência. Este será alterado para inclusão de dados acima de 5 anos e melhorias na qualidade dos dados.`

2. Qual o nome do conjunto? `br_ans_beneficiario.informacao_consolidada`

3. Qual o nome da(s) tabela(s)? `dados`

4. Fonte original dos dados: `(https://dadosabertos.ans.gov.br/FTP/PDA/informacoes_consolidadas_de_beneficiarios/201405/)`

5. Cobertura espacial: `br`

6. Cobertura temporal: de `2014-05 a 2022-12`

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template e os dados originais
- [x] Preencher as tabelas de arquitetura - Marcar a equipe de dados na issue avisando quando finalizar
- [ ] Escrever código de captura e limpeza de dados
- [ ] Organizar arquivos auxiliares, se necessário
- [ ] Criar tabela dicionário, se necessário
- [ ] Subir tabelas no BigQuery
- [ ] Criar e preencher table_config e dataset_config
- [ ] Fazer uma revisão seguindo o [nosso guia](https://github.com/basedosdados/.github/wiki/Dados#como-fazer-code-review)
- [ ] Abrir o PR

**Comment by tricktx** [comment]
Segue a arquitetura e o dicionário: 

[arquitetura] https://docs.google.com/spreadsheets/d/1XcmoCjGLEQwLrYA2QmHaqeaqeZeDpjW66Dnl1UnwSM4/edit#gid=0

[dicionário] https://docs.google.com/spreadsheets/d/1MhCtA-qX1dwb2DOk048jRfhxE-TeceY49I4CDXS4-kk/edit#gid=0

**Comment by guissalustiano** [comment]
Eu [tinha um código](https://github.com/guissalustiano/mais/blob/data/br_ans/bases/br_ans/code/informacoes_consolidadas_de_beneficiarios.py#L45) que baixava esses dados no antigo dominio, é só atualizar
Eu quase implementei tudo [aqui](https://github.com/basedosdados/mais/issues/1078) mas acabei ficando sem tempo na época, agora to voltando e vou tentar subir uns dados

**Comment by guissalustiano** [comment]
Subi o PR em #1582 
Acabei aproveitando sua tabela de arquitetura, só dei uma leve mudada
