### ISSUE TITLE
Diferença entre dados descritos no git e encontrados no dataframe

### ISSUE THREAD

**Issue by thalesgodoy** [basedosdados/mais#1562]
Usaria o dataset pra ter acesso aos eleitos, porém essa coluna aparenta não estar nos queries disponibilizados. São mais colunas que as descritas e com nomes diferentes, além de estarem completamente vazias

**Comment by gustavoalcantara** [comment]
Oi @thalesgodoy. A qual dataframe você se refere? Qual Coluna? Se possível, descreva melhor essas características para que possamos ajudá-lo. Att.

**Comment by gustavoalcantara** [comment]
@thalesgodoy, qual ano você está analisando? Qual método está fazendo a consulta? Via Bigquery/Pacote em R/Python?
Pela query abaixo, eu consegui acessar a coluna normalmente. 
![image](https://user-images.githubusercontent.com/26544494/217303771-641db45a-6ab9-416f-b941-a970808647c0.png)

**Comment by thalesgodoy** [comment]
Estou usando o R, com o seguinte método 
![image](https://user-images.githubusercontent.com/81503632/217332190-8b9d7b0b-6e09-4b8a-8479-e68bcc526c24.png)

**Comment by gustavoalcantara** [comment]
mas verifique: você está usando o `br_tse_eleicoes.candidatos` na `query<-`
tem que ser a mesma do `df`
concorda?

**Comment by gustavoalcantara** [comment]
e se possível, retira as aspas simples do `'basedosdados.br_tse_eleicoes.resultados'` da query

**Comment by thalesgodoy** [comment]
você está correto. irei testar daqui a pouco suas recomendações. Havia copiado e colado o que estava dentro. Obrigado pela paciência!

**Comment by gustavoalcantara** [comment]
fique tranquilo, Thales. Estamos aqui pra isso. Por favor, nos retorne se deu certo! Abraços!
