### ISSUE TITLE
[infra] Table doesn't have a valid name - R

### ISSUE THREAD

**Issue by gdocesp** [basedosdados/mais#1575]
A base de microdados ainda estão disponíveis? Encontro o seguinte erro ao rodar função indicada no site

library("basedosdados")

# Defina o seu projeto no Google Cloud
set_billing_id("XXXXXX")

# Para carregar o dado direto no R
query <- bdplyr("br_ibge_censo_demografico.microdados_domicilio_1970")
df <- bd_collect(query)

**The table basedosdados.br_ibge_censo_demografico.microdados_domicilio_1970 doesn't have a valid name or was not found at basedosdados.**

**Comment by gdocesp** [comment]
Como aplicar pesos amostrais ?

**Comment by gustavoalcantara** [comment]
Olá @gdocesp, esse erro está atrelado ao [PR 1563](https://github.com/basedosdados/mais/pull/1563). Te aconselho a ler nossa [documentação](https://basedosdados.github.io/mais/api_reference_r/) e nos retornar após seguir os passos daqui. 
Sobre pesos amostrais, é melhor verificar na documentação do IBGE.

**Comment by folhesgabriel** [comment]
> Olá @gdocesp, esse erro está atrelado ao [PR 1563](https://github.com/basedosdados/mais/pull/1563). Te aconselho a ler nossa [documentação](https://basedosdados.github.io/mais/api_reference_r/) e nos retornar após seguir os passos daqui. Sobre pesos amostrais, é melhor verificar na documentação do IBGE.

**Comment by folhesgabriel** [comment]
#

**Comment by folhesgabriel** [comment]
Caros perdão, fechei por engano. 
@gdocesp sugiro que use o pacote survey para lidar com dados amostrais complexos.
Esse guia do Gabriel Assunção, servidor do IBGE, é ótimo: https://rpubs.com/gabriel-assuncao-ibge/pnadc
