### ISSUE TITLE
Navegador não abre para autenticação no R

### ISSUE THREAD

**Issue by danielsantos86** [basedosdados/mais#1590]
**Descrição**
Ontem eu fiz em notebook uma conta no Google Cloud e um id de projeto para utilizar o pacote basedosdados no R. No entanto, ao tentar autenticar no meu computador pessoal de trabalho, não abre a janela de autenticação no navegador conforme abaixo:

```r
basedosdados::set_billing_id(id_projeto) 
Project keys set successfully 
 rais <- basedosdados::read_sql('SELECT * FROM basedosdados.br_me_rais.microdados_vinculos LIMIT 1000') 

Waiting for authentication in browser... Press Esc/Ctrl + C to abort  
```

Ao tentar rodar rlang aparece abaixo:
```r
 rlang::last_error() Error: Can't show last error because no error was recorded yet 

> rlang::last_trace 
function (drop = NULL)  
{     
err <- last_error()     
drop <- drop %\|\|% use_tree_display()     
err$rlang$internal$trace_simplify <- "none"     
err$rlang$internal$trace_drop <- drop     
err } 
<bytecode: 0x56099c0381d8> 
<environment: namespace:rlang>
--
 
> | >
>
```
**Comportamento esperado**
Que a autenticação desse certo assim como no notebook

**Desktop (preencha as seguintes informações):**
  - SO: Linux Mint 21.1 Vera
  - Navegadores
Brave Browser Version 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)]
Firefox Browser 110.0.1 (64-bit)

obrigado!

  - 
  - Versão [por exemplo 22]

**Smartphone (preencha as seguintes informações):**
  - Dispositivo: [por exemplo iPhone6]
  - SO: [por exemplo iOS8.1]
  - Navegador [por exemplo navegador de ações, safari]
  - Versão [por exemplo 22]

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by gustavoalcantara** [comment]
quando funcionou, você tava usando que navegador e qual SO?

**Comment by gustavoalcantara** [comment]
Oi @danielsantos86, pode testar utilizando o rcloud, por favor?
Como o SO é Linux, já tivemos outro usuário que relatou a mesma consideração... Será que não é configuração do próprio SO? 
Abs.

**Comment by gustavoalcantara** [comment]
ele libera a opção de você escolher o e-mail cadastrado? Ou nem chega nessa parte?

**Comment by danielsantos86** [comment]
Não, nem chega. Fica sempre:

Waiting for authentication in browser...
Press Esc/Ctrl + C to abort

**Comment by gustavoalcantara** [comment]
tu ja tentou para outras autenticações? funcionaram normal?

**Comment by danielsantos86** [comment]
Já tentei. Nenhuma funcionou no RStudio do meu PC. Sempre trava nisso.

**Comment by pedrocava** [comment]
https://github.com/tidyverse/googledrive/issues/415

Achei esse erro similar em outro cliente do `googleAuthR`, essa funcionalidade é 100% fora do nosso pacote. Tenta de novo e usa o `sessioninfo` para trazer as suas infos de sessão por favor.
