### ISSUE TITLE
[dados] br_me_operacoes_credito_pvl

### ISSUE THREAD

**Issue by andrealvguim** [basedosdados/mais#1595]
**Metadados da base**

1. Descrição: Base que conta com informações sobre operações de crédito contratadas por Estados, Distrito Federal e Municípios, incluindo suas autarquias e empresas estatais dependentes por meio de pedidos de verificações de limites e condições (PVL) .

2. Qual o nome do conjunto? br_me_operacoes_credito_pvl

4. Qual o nome da(s) tabela(s)? microdados

5. Fonte original dos dados: [https://www.tesourotransparente.gov.br/ckan/dataset/operacoes-copem](https://www.tesourotransparente.gov.br/ckan/dataset/operacoes-copem)

6. Cobertura espacial: Brasil

7. Cobertura temporal: de 2002 a 2023

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template e os dados originais
- [x] Preencher as tabelas de arquitetura - Marcar a equipe de dados na issue avisando quando finalizar
- [x] Escrever código de captura e limpeza de dados
- [x] Organizar arquivos auxiliares, se necessário
- [x] Criar tabela dicionário, se necessário
- [ ] Subir tabelas no BigQuery
- [x] Criar e preencher table_config e dataset_config
- [ ] Fazer uma revisão seguindo o [nosso guia](https://github.com/basedosdados/.github/wiki/Dados#como-fazer-code-review)
- [x] Abrir o PR

**Comment by folhesgabriel** [comment]
Boa noite André! Não usamos conectores no `dataset_id`. Trocar `br_me_operacoes_de_credito_pvl` por `br_me_operacoes_credito_pvl` :)
