### ISSUE TITLE
`br_me_siconfi`: informações de estágio pra 2009-12

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#1607]
Aparentemente nossos dados de município não incluem informações de `estagio` para os anos 2009-12, mas estes estão disponíveis nos arquivos originais. Precisamos checar e preencher em `estagio_bd`.

Fonte original: https://www.tesourotransparente.gov.br/publicacoes/finbra-dados-contabeis-dos-municipios-1989-a-2012/2012/26

**Comment by crislanealves** [comment]
👀

**Comment by crislanealves** [comment]
Antes não tinha, eles podem ter revisado recentemente e adicionado.

**Comment by rdahis** [comment]
> Antes não tinha, eles podem ter revisado recentemente e adicionado.

Minha memória é também que não tinha quando limpamos esses dados.

**Comment by rdahis** [comment]
Corrigido em produção.
