### ISSUE TITLE
[dados] 2º Turno em 2022 na basedosdados.br_tse_eleicoes.detalhes_votacao_municipio não aparece

### ISSUE THREAD

**Issue by gustavoalcantara** [basedosdados/mais#1609]
**Descrição**
Na query 
SELECT COUNT(DISTINCT turno) as qtde_turno, ano
FROM basedosdados.br_tse_eleicoes.detalhes_votacao_municipio 
WHERE ano IN (2022, 2018, 2014, 2010, 2006, 2002) 
group by ano
order by ano desc 

O ano de 2022 possui somente o primeiro turno. É necessário inserir o segundo. 
Bug relatado pelo usuário Guguizg#3039 no Discord.

**Comment by rdahis** [comment]
Resolvido em prod!

**Comment by gustavoalcantara** [comment]
esse é meu patrão
