### ISSUE TITLE
[wiki] Adicionar descrição detalhada métodos Metadata

### ISSUE THREAD

**Issue by folhesgabriel** [basedosdados/mais#1612]
- Incrementar a página de upload da wiki da BD com o funcionamento  da classe Metadata

**Comment by laura-l-amaral** [comment]
@lucascr91 tava conversando com o pisa, ce acha que com a migração do ckan ainda faz sentido a gente fazer essa documentação? Será que ela não vai ficar obsoleta muito rápida?
