### ISSUE TITLE
[data-quality] `br_ibge_pnadc`

### ISSUE THREAD

**Issue by arthurfg** [basedosdados/mais#1619]
**Metadados da base**

1. Qual o nome do conjunto? `br_ibge_pnadc`

2. Qual o nome da(s) tabela(s)? `microdados`

**Tarefas** (seguindo os passos da documentação que está sendo feita [aqui](#1616 ))

1. **Qualidade**
- [x] Checar o tipo das colunas no BigQuery e comparar com a arquitetura e os metadados do CKAN
- [x] Checar a existência de colunas nulas, assim como a frequência de nulos por coluna e por ano.
- [x] Checar se a quantidade de linhas da tabela no BigQuery é igual à quantidade de linhas da fonte original.
- [x] Checar se as colunas com link em diretórios não estão com o preenchimento errado dos metadados.
- [ ] Materializar as tabelas.

2. **Atualização**
- [x] Atualizar os dados para o último release disponível.
- [ ] Checar e, caso haja a necessidade, atualizar o dicionário.

3. **Documentação**
- [ ] Disponibilizar arquitetura ao usuário.
- [ ] Incluir `auxiliary_files` para todos os conjuntos
- [x] Revisar e comentar código de tratamento.
- [x] Revisar `README` do conjunto.

**Comment by rdahis** [comment]
Podemos fechar?
