### ISSUE TITLE
[dados] Banco Central (BCB)

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#1630]
**Metadados da base**

1. Descrição: Dados do Banco Central (BCB).

Fontes:
https://dadosabertos.bcb.gov.br/dataset/dolar-americano-usd-todos-os-boletins-diarios
https://dadosabertos.bcb.gov.br/dataset/taxas-de-cambio-todos-os-boletins-diarios
https://dadosabertos.bcb.gov.br/dataset/expectativas-mercado
https://dadosabertos.bcb.gov.br/dataset/11-taxa-de-juros---selic
https://dadosabertos.bcb.gov.br/dataset/scr_data

2. Fonte original dos dados
    * Tem API? sim
    * É grátis? sim
    * Cobertura espacial: `sa_br`
    * Cobertura temporal: de `1984-11-28` a hoje.
    * Frequência de atualização: `day`

3. Raspagem
    * Nível de dificuldade: baixo
    * Existe código semi-pronto? não
    * Dificuldades de big data (alta frequência, alto volume)? não

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Mapear dados e validar [arquitetura](https://drive.google.com/drive/folders/1ejFpkzr7F9p6yDy4T-8pufAOxL05e3A6?lfhs=2)
- [x] Escrever código de captura e limpeza de dados
- [ ] Organizar arquivos brutos, se necessário
- [ ] Organizar arquivos auxiliares, se necessário
- [ ] Criar tabela dicionário, se necessário
- [ ] Subir tabelas no BigQuery
- [ ] Fazer uma revisão seguindo o [nosso guia](https://github.com/basedosdados/.github/wiki/Dados#como-fazer-code-review)
- [ ] Abrir o PR
- [ ] Escrever a pipeline

-----

Informações relevantes
`taxa_cambio`:
- A tabela de dólar americano está incluída na tabela taxa de câmbio
- As moedas são separadas em: 
    - Moedas tipo A: Paridade é definida pela quantidade da moeda por uma unidade de dólar americano (USD)
    - Moedas tipo B: Paridade é definida pela quantidade de dólar americano (USD) por uma unidade da moeda

**Comment by laura-l-amaral** [comment]
@rdahis pelo que eu tava vendo a primeira tabela de dolar está contida na segunda tabela de taxa de cambio, tem algum motivo que faz vc achar que vale fazer 2 tabelas separadas?

**Comment by rdahis** [comment]
> @rdahis pelo que eu tava vendo a primeira tabela de dolar está contida na segunda tabela de taxa de cambio, tem algum motivo que faz vc achar que vale fazer 2 tabelas separadas?

De fato, não precisa ser separado não. Esse vai ser o trabalho de arquitetura de dados que teremos que fazer antes de sair escrevendo as pipelines.

**Comment by tricktx** [comment]
A tabela de dólar americano está incluída na tabela taxa de câmbio. As outras precisam montar arquiteturas.

**Comment by laura-l-amaral** [comment]
closed by basedosdados/pipelines#331
