### ISSUE TITLE
[dados] CVM

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#1631]
**Metadados da base**

1. Descrição: Dados da CVM.

Fontes:
https://dados.cvm.gov.br/dataset/fi-doc-cda
https://dados.cvm.gov.br/dataset/fi-doc-inf_diario
https://dados.cvm.gov.br/dataset/fi-doc-extrato
https://dados.cvm.gov.br/dataset/fi-cad
https://dados.cvm.gov.br/dataset/fi-doc-balancete
https://dados.cvm.gov.br/dataset/fi-doc-perfil_mensal
https://dados.cvm.gov.br/dataset/cia_aberta-cad
https://dados.cvm.gov.br/dataset/cia_aberta-doc-dfp
https://dados.cvm.gov.br/dataset/cia_aberta-doc-ipe
https://dados.cvm.gov.br/dataset/cia_aberta-doc-fre

2. Fonte original dos dados
    * Tem API? não
    * É grátis? sim
    * Cobertura espacial: `sa_br`
    * Cobertura temporal:
    * Frequência de atualização: `day`

3. Raspagem
    * Nível de dificuldade: baixo
    * Existe código semi-pronto? não
    * Dificuldades de big data (alta frequência, alto volume)? não

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] #1635
- [x] Baixar a pasta template e os dados originais
- [x] Preencher as tabelas de arquitetura - Marcar a equipe de dados na issue avisando quando finalizar
- [x] Escrever código de captura e limpeza de dados
- [x] Organizar arquivos brutos, se necessário
- [x] Organizar arquivos auxiliares, se necessário
- [ ] Criar tabela dicionário, se necessário
- [x] Subir tabelas no BigQuery
- [x] Fazer uma revisão seguindo o [nosso guia](https://github.com/basedosdados/.github/wiki/Dados#como-fazer-code-review)
- [x] Abrir o PR
- [x] Escrever a pipeline

**Comment by arthurfg** [comment]
Pessoal, criei a issue #1635 para acompanhar o mapeamento dos dados e as arquiteturas. 
Fiz as arquiteturas das duas primeiras tabelas e coloquei lá. O nome das tabelas/conjunto eu não sei se ficou o melhor, aguardo o feedback. Abraços, bom feriado! @rdahis @lucascr91
