### ISSUE TITLE
[dados] `br_b3_cotacoes`

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#1632]
**Metadados da base**

1. Descrição: Cotações de ações em bolsa

2. Qual o nome do conjunto? `br_b3_cotacoes`

3. Qual o nome da(s) tabela(s)? `dia`

4. Fonte original dos dados
    * Endereço: https://www.b3.com.br/pt_br/market-data-e-indices/servicos-de-dados/market-data/cotacoes/cotacoes/
    * Tem API? não
    * É grátis? sim
    * Cobertura espacial: `sa_br`
    * Cobertura temporal:
    * Frequência de atualização: `day`

5. Raspagem
    * Nível de dificuldade: baixo
    * Existe código semi-pronto? não
    * Dificuldades de big data (alta frequência, alto volume)? não

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template e os dados originais
- [x] Preencher as tabelas de arquitetura - Marcar a equipe de dados na issue avisando quando finalizar
- [ ] Escrever código de captura e limpeza de dados
- [ ] Organizar arquivos brutos, se necessário
- [ ] Organizar arquivos auxiliares, se necessário
- [ ] Criar tabela dicionário, se necessário
- [ ] Subir tabelas no BigQuery
- [ ] Fazer uma revisão seguindo o [nosso guia](https://github.com/basedosdados/.github/wiki/Dados#como-fazer-code-review)
- [ ] Abrir o PR
- [ ] Escrever a pipeline

**Comment by lucascr91** [comment]
Pessoal, precisei sair dessa tarefa para assumir outra. Havia feito a tabela de arquitetura. Segue link: https://docs.google.com/spreadsheets/d/1-93qwOEqhafjZyy0KfH5XjBuGgPUjAKq/edit#gid=1045172528

**Comment by tricktx** [comment]
@rdahis @laura-l-amaral estou tratando os dados da b3. Não há um nível de complexidade grande, mas ocorre que não consegui encontrar os dados históricos completo (apesar de eu não ter focado nisso, apenas olhei por alto). Dessa forma, o site cobre apenas os últimos 20 dias de cotações, sendo que todo dia o último arquivo some e é acrescentado um novo arquivo. Ainda tenho que pesquisar com calma sobre os dados históricos, apenas salientando e documentando na issue. 
Abraços!
