### ISSUE TITLE
Mapear dados e validar arquitetura.

### ISSUE THREAD

**Issue by arthurfg** [basedosdados/mais#1635]
#### Mapeando os dados e validando a arquitetura do conjunto `br_cvm_documentos`:

- [x] https://dados.cvm.gov.br/dataset/fi-doc-cda
- [x] https://dados.cvm.gov.br/dataset/fi-doc-inf_diario 
- [x] https://dados.cvm.gov.br/dataset/fi-doc-extrato
- [x] https://dados.cvm.gov.br/dataset/fi-cad
- [x] https://dados.cvm.gov.br/dataset/fi-doc-balancete
- [x] https://dados.cvm.gov.br/dataset/fi-doc-perfil_mensal
- [x] https://dados.cvm.gov.br/dataset/cia_aberta-cad
- [x] https://dados.cvm.gov.br/dataset/cia_aberta-doc-dfp
- [x] https://dados.cvm.gov.br/dataset/cia_aberta-doc-ipe
- [x] https://dados.cvm.gov.br/dataset/cia_aberta-doc-fre

#### Arquiteturas:
- `documentos_informe_diario`: [link](https://docs.google.com/spreadsheets/d/1W739_mLZNBPYhBqGyjsuuWFBOqCrhrDl/edit?usp=share_link&ouid=103222913060268158773&rtpof=true&sd=true)
- `documentos_extratos_informacoes`: [link](https://docs.google.com/spreadsheets/d/1b94RdASfwXMgJuVMhFeY6Xbph4n4_MVt/edit?usp=share_link&ouid=103222913060268158773&rtpof=true&sd=true)
- `documentos_situacao_cadastral`: [link](https://docs.google.com/spreadsheets/d/1b94RdASfwXMgJuVMhFeY6Xbph4n4_MVt/edit#gid=1045172528)
- `documentos_balancete`: [link](https://docs.google.com/spreadsheets/d/1eIMo_hYHy89oh6kHRN9Kh0NytUZzr8__/edit#gid=1045172528)
- `documentos_eventuais_periodicos_ipe`: [link](https://docs.google.com/spreadsheets/d/13Q3Le5J4JyBmf-mYiqcLJJIkodf5_Al_/edit#gid=1045172528)
- `documentos_perfil_mensal`: [link](https://docs.google.com/spreadsheets/d/1IN7enHe6K-StD_sDfCaqhJ7XfUNXe-W8/edit#gid=1045172528)
- `br_cvm_cia_aberta.documentos_informacao_cadastral`: [link](https://docs.google.com/spreadsheets/d/1olnQ-6Wm1hpEdoSAXK--Wf8yHcCl00b6/edit#gid=1045172528)
- `br_cvm_cia_aberta_dfp`: [link](https://docs.google.com/spreadsheets/d/1Ef_vdEnQp7itONpX5Fw6tsOKJsT_QEKy/edit?usp=sharing&ouid=103222913060268158773&rtpof=true&sd=true)
   1. `balanco_patrimonial_ativo`: [link](https://docs.google.com/spreadsheets/d/14dmboCyZnfg5rivewTpJpXpXYYYcb2rx/edit#gid=1045172528)
   2.  `balanço_patrimonial_passivo`: [link](https://docs.google.com/spreadsheets/d/17ML3rhPqKkzeWUrJeUuam4HF7DT2i8eS/edit?usp=share_link&ouid=103222913060268158773&rtpof=true&sd=true) 
   3. `demonstracao_fluxo_caixa_metodo_direto`: [link](https://docs.google.com/spreadsheets/d/1gDKIAAmP4STTeBeC7tQAYkhF0HSxG0Ii/edit?usp=share_link&ouid=103222913060268158773&rtpof=true&sd=true)
   4. `demonstracao_fluxo_caixa_metodo_indireto`: [link](https://docs.google.com/spreadsheets/d/1MLTR5LDOocJNwQwJcGF3S2n8hSw-tYov/edit?usp=share_link&ouid=103222913060268158773&rtpof=true&sd=true)
   5. `demonstracao_mutacoes_patrimonio_liquido`: [link](https://docs.google.com/spreadsheets/d/1dyXnh2vPHyqy6kbCd6ZxZCvnS5RQueiI/edit?usp=share_link&ouid=103222913060268158773&rtpof=true&sd=true)
   6. `demonstracao_resultado_abrangente`: [link](https://docs.google.com/spreadsheets/d/11w8bygfj3kTOA8zuzUQhn7wYQfin06Po/edit?usp=share_link&ouid=103222913060268158773&rtpof=true&sd=true)
   7. `demonstracao_resultado`: [link](https://docs.google.com/spreadsheets/d/1mSJLbQ7BZQuqEEv92-VTIgpAz_jJbr9g/edit?usp=share_link&ouid=103222913060268158773&rtpof=true&sd=true)
   8. `demonstracao_valor_adicionado`: [link](https://docs.google.com/spreadsheets/d/1obXpThTgHN-CRmAZAnf8X-0q2QPfuIY5/edit?usp=share_link&ouid=103222913060268158773&rtpof=true&sd=true)

**Comment by arthurfg** [comment]
@laura-amaral

**Comment by arthurfg** [comment]
Uma observação: 
O conjunto  Formulário de Referência (FRE)  é disponibilizado em um formato um pouco peculiar:
- Uma tabela "mãe" com os links para download dos FRE entregues nos últimos cinco anos. 
- 40 tabelas com o conteúdo estruturado do Formulário, com dados divididos do tipo: identificação  responsáveis, informações financeiras, distribuição de dividendos, enfim, todos os campos do formulário.

**As tabelas:**
<img width="390" alt="Captura_de_Tela_2023-04-26_as_17 14 27" src="https://user-images.githubusercontent.com/62671380/235012428-4aed50ae-d148-4db9-855d-1cdfd6d0364c.png">

E ai as colunas das tabelas vão mudando de tabela em tabela e tal, então não consegui pensar em um jeito de _appendar_ todas em um único df. Fiquei um pouco em dúvida do que fazer, faço a arquitetura dessas tabelas? Seleciono apenas algumas infos? Se alguém tiver alguma ideia, tamo junto!

**Comment by rdahis** [comment]
Vamos reunir sobre isso na segunda? Preciso entender melhor se vale o esforço antes de vc gastar todo esse tempo nessa arquitetura.

**Comment by arthurfg** [comment]
> Vamos reunir sobre isso na segunda? Preciso entender melhor se vale o esforço antes de vc gastar todo esse tempo nessa arquitetura.

Vamos sim! Pode ser lá pelas 11h?
