### ISSUE TITLE
[dados] br_bd_diretorios_brasil.empresa

### ISSUE THREAD

**Issue by gabrielle-carv** [basedosdados/mais#1636]
**Metadados da base**

1. Descrição: A tabela apresenta informações do Cadastro Nacional da Pessoa Jurídica (CNPJ), que é um banco de dados administrado pela Secretaria Especial da Receita Federal do Brasil (RFB). Esse cadastro armazena detalhes cadastrais de pessoas jurídicas e outras entidades relevantes para as administrações tributárias do governo federal, dos estados, do Distrito Federal e dos municípios.

2. Qual o nome do conjunto? `br_bd_diretorios_brasil`

3. Qual o nome da(s) tabela(s)? `empresa`

4. Fonte original dos dados
    * Endereço: [url](https://dados.gov.br/dados/conjuntos-dados/cadastro-nacional-da-pessoa-juridica---cnpj)
    * Tem API?  não
    * É grátis? sim 
    * Cobertura espacial: sa.br
    * Cobertura temporal: 
    * Frequência de atualização: month

5. Raspagem
    * Nível de dificuldade: médio
    * Existe código semi-pronto? não
    * Dificuldades de big data (alta frequência, alto volume)? sim

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template e os dados originais
- [x] Preencher as tabelas de arquitetura - Marcar a equipe de dados na issue avisando quando finalizar
- [x] Escrever código de captura e limpeza de dados
- [ ] Organizar arquivos brutos, se necessário
- [x] Organizar arquivos auxiliares, se necessário
- [ ] Criar tabela dicionário, se necessário
- [x] Subir tabelas no BigQuery
- [ ] Fazer uma revisão seguindo o [nosso guia](https://github.com/basedosdados/.github/wiki/Dados#como-fazer-code-review)
- [ ] Abrir o PR
- [ ] Escrever a pipeline

**Comment by rdahis** [comment]
Detalhezinho: tabela se chamar `empresa`, no singular =)

**Comment by rdahis** [comment]
Podemos fechar?
