### ISSUE TITLE
[dados] Dados imobiliários

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#1643]
### Dados imobiliários no Brasil

- [ ] Mapear o que existe de dados disponíveis para grandes cidades no Brasil. @gustavoalcantara 

* IPTU
    * `observation_level`: domicílio, endereço
    * Fontes: prefeituras (começar pelas maiores, capitais, RJ, SP)
    * SP: https://geosampa.prefeitura.sp.gov.br/
* Preços de imóveis
    * Fontes: dados administrativos, ZAP, Quinto Andar, etc.

**Comment by lucascr91** [comment]
Para SP, seguir a seguinte estrutura:

br_sp_3305423_prefeitura_geosampa
    edificacao
    cadastro_iptu
    economia_estabelecimentos
    economia_rais

**Comment by rdahis** [comment]
@gustavoalcantara decidimos mover o @lucascr91 para uma tarefa de raspagem, e deixamos você como responsável por essa issue :-)

**Comment by gustavoalcantara** [comment]
@rdahis excelente! Bora

**Comment by rdahis** [comment]
Boa isso aí
