### ISSUE TITLE
[dados] `br_anp_producao`

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#1645]
**Metadados da base**

1. Descrição: Produção de petróleo e gás natural.

2. Qual o nome do conjunto? `br_anp_producao`

3. Qual o nome da(s) tabela(s)? É preciso montar a arquitetura com um pouco de cuidado, dado que há várias tabelas sobre produção (diferentes produtos, em diferentes níveis de observação)

4. Fonte original dos dados
    * Endereço:
        * https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos
        * https://basedosdados.org/dataset/producao-de-petroleo-e-gas-natural-nacional-dados-historicos
    * Tem API? `false`
    * É grátis? `true`
    * Cobertura espacial: `sa_br`
    * Cobertura temporal:
    * Frequência de atualização: varia. Entre `year`, `month`, `week`

5. Raspagem
    * Nível de dificuldade: baixo
    * Existe código semi-pronto? não
    * Dificuldades de big data (alta frequência, alto volume)? não

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template e os dados originais
- [x] Preencher as tabelas de arquitetura - Marcar a equipe de dados na issue avisando quando finalizar
- [x] Escrever código de captura e limpeza de dados
- [x] Organizar arquivos brutos, se necessário
- [x] Organizar arquivos auxiliares, se necessário
- [x] Criar tabela dicionário, se necessário
- [x] Subir tabelas no BigQuery
- [x] Fazer uma revisão seguindo o [nosso guia](https://github.com/basedosdados/.github/wiki/Dados#como-fazer-code-review)
- [x] Abrir o PR
- [x] Escrever a pipeline

**Comment by tricktx** [comment]
Dados atualizados no nosso bq: `2022-12`
Subir: `Janeiro`, `Fevereiro`, `Março`, `Abril`, `Maio`, `Junho`
