### ISSUE TITLE
[dados] `br_fipe_veiculos`

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#1649]
**Metadados da base**

1. Descrição: Tabela FIPE

2. Qual o nome do conjunto? `br_fipe_veiculos`

3. Qual o nome da(s) tabela(s)? `mes`

4. Fonte original dos dados
    * Endereço
        * https://veiculos.fipe.org.br/
        * https://brasilapi.com.br/docs#tag/FIPE
    * Tem API? `false`
    * É grátis? `true`
    * Cobertura espacial: `sa_br`
    * Cobertura temporal: 2001-01 a atual
    * Frequência de atualização: `month`

5. Raspagem
    * Nível de dificuldade: `high`
    * Existe código semi-pronto? `false`
    * Dificuldades de big data (alta frequência, alto volume)? `false`

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [ ] Baixar a pasta template e os dados originais
- [ ] Preencher as tabelas de arquitetura - Marcar a equipe de dados na issue avisando quando finalizar
- [ ] Escrever código de captura e limpeza de dados
- [ ] Organizar arquivos brutos, se necessário
- [ ] Organizar arquivos auxiliares, se necessário
- [ ] Criar tabela dicionário, se necessário
- [ ] Subir tabelas no BigQuery
- [ ] Fazer uma revisão seguindo o [nosso guia](https://github.com/basedosdados/.github/wiki/Dados#como-fazer-code-review)
- [ ] Abrir o PR
- [ ] Escrever a pipeline

**Comment by gustavoalcantara** [comment]
@rdahis eu ACHO que o pacote getFipeData utiliza dessa API e tem código pronto. Veja: https://github.com/BaruqueRodrigues/getfipedata
