### ISSUE TITLE
Error in `bdplyr()`: ! The table basedosdados.br_me_rais.microdados_vinculos doesn't have a valid name or was not found at basedosdados.

### ISSUE THREAD

**Issue by pauloarpo** [basedosdados/mais#1662]
Bom dia,

Estou tentando baixar alguns dados da RAIS com o seguinte código:

library(basedosdados)

#query <- bdplyr("br_me_rais.microdados_vinculos")

id_projeto <- "rais-372915"

basedosdados::set_billing_id(id_projeto)

tabela_db <- ("br_me_rais.microdados_vinculos")

rais_tbl <- bdplyr("br_me_rais.microdados_vinculos")

Entretanto, sempre retorno com a mesma mensagem de erro: 

Error in `bdplyr()`: ! The table basedosdados.br_me_rais.microdados_vinculos doesn't have a valid name or was not found at basedosdados.

![image](https://github.com/basedosdados/mais/assets/135226848/5c0d1eab-44c0-478a-ac22-c72090abd706)

Alguém poderia me orientar o que está acontecendo de errado?

**Comment by gustavoalcantara** [comment]
Oi @pauloarpo. Tudo bem? É bem provável que esse erro seja de autenticação. Você pode conferir a documentação do pacote [aqui](https://basedosdados.github.io/mais/api_reference_r/).
Além disso, te aconselho a realizar preteritamente alguns filtros de UF ou limitar a consulta. Desse jeito que você está fazendo, irá realizar o download de toda a RAIS (+ de 250gb) e talvez não seja viável, concorda? 
Nos informe se conseguiu. Abraços.

**Comment by pauloarpo** [comment]
Faço os filtros logo em seguida, com o bdcollect()

**Comment by pauloarpo** [comment]
Faço os filtros logo em seguida, com o bdcollect()
![image](https://github.com/basedosdados/mais/assets/135226848/1e8d0cdd-3641-46ef-9bf5-6024fefd6ff6)

A autenticação pode ser impedida pelo antivirus??
