### ISSUE TITLE
[infra-cloud] | Adicionar labels às tabelas do GCP

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/mais#1663]
**Sua solicitação de recurso está relacionada a um problema? Por favor descreva.**

Atualmente, não temos muitas formas de fazer a rastreabilidade de custos no nosso no DL de forma mais granular. Daí a dificuldade de entender o aumento de custos quando temos um processo de ingestão incorreto ou algo do tipo. Exemplo:

![image](https://github.com/basedosdados/mais/assets/58278652/3e410953-a791-4304-a6b5-f0de68b99e35)

**Descreva a solução que você gostaria**

Uma forma de melhorar a rastreabilidade no DL, é a utilização de `labels`. A ideia é adicionar `labels` via DBT para todas as tabelas que já existem e que serão adicionadas no futuro. Isso vai nos ajudar com a rastreabilidade de custos e com uma governança melhor nos nossos dados. 

**Descreva alternativas que você considerou**

Processo de implementação via DBT é muito simples, com apenas uma linha de código.

Por exemplo:
`labels = {'project_id': 'basedosdados', 'tema': 'economia'})`

Código completo:
[br_ibge_pnadc.microdados](https://github.com/basedosdados/queries-basedosdados-dev/blob/cb4fe6db8398ee9004361c255f877560d75e88c0/models/br_ibge_pnadc/br_ibge_pnadc__microdados.sql)

Resultado:
![image](https://github.com/basedosdados/mais/assets/58278652/0d44db66-d2ab-4adf-bb0b-2b2e951ed1f2)

**Contexto adicional**
O ideal é ter uma padrão já definido, alguns rótulos que podemos utilizar são:

`project_id`: basedosdados, basedosdados-dev [...]
`owner`: engenharia, bi, arquitetura [...]
`data_source`: bd_pro, bd_mais [...]
`data_type`: logs, transactions, sensitive, analyzes [...]
`cost_center`: administrativo, dados, plataforma [...]

Referencia: 

[Introduction to labels](https://cloud.google.com/bigquery/docs/labels-intro)
[Organize resources using labels](https://cloud.google.com/compute/docs/labeling-resources)

**Comment by mfagundes** [comment]
Excelente ideia. @lucascr91 e @laura-l-amaral acham que podemos designar alguém de dados para ir atualizando isso enquanto terminamos a migração? Acho que podem andar em paralelo sem problema algum.

**Comment by crislanealves** [comment]
Antes é preciso definir qual padrão é o ideal. @rdahis que é mestre nisso 👑
