### ISSUE TITLE
Error in UseMethod("tbl")  carregar tabela "br_me_rais.microdados_vinculos" em R

### ISSUE THREAD

**Issue by ligiainhan** [basedosdados/mais#1673]
**Descrição**
Não consigo carregar a tabela:
1. tabgen <- "br_me_rais.microdados_vinculos"
2. rais2_tab <- basedosdados::bdplyr(tabgen)

**já corrigi a versão dbplyr e já reautentiquei a conta no bigquery
4. utils::packageVersion("dbplyr") 
devtools::install_version("dbplyr", version = "2.1.1", repos = "http://cran.us.r-project.org")

**Reproduzir**
5. Error in UseMethod("tbl") : 
  no applicable method for 'tbl' applied to an object of class "BaseDosDadosConnection"

**Comportamento esperado**
6. depois da função glimpse, seria capaz de ver os cabeçalhos da tabela

**Desktop (preencha as seguintes informações):**
  - SO: [por exemplo iOS]: Windows 11
  - Navegador [por exemplo cromo, safari]: Chrome
  - Versão [por exemplo 22] 

**Smartphone (preencha as seguintes informações):**
  - Dispositivo: [por exemplo iPhone6]
  - SO: [por exemplo iOS8.1]
  - Navegador [por exemplo navegador de ações, safari]
  - Versão 114.0.5735.199 (Official Build) (64-bit)

**Contexto adicional**
Estou usando R Studio desktop versão 2023.06.0 Build 421

**Comment by ligiainhan** [comment]
Oi Gustavo, tudo bem e espero que com vc tb.
** apliquei rlang::last_error() e deu esta mensagem:
<html>
<body>


> rlang::last_error() <error/rlang_error> Error in `basedosdados::bd_collect()`: ! `.lazy_tbl' should be a lazy tibble. --- Backtrace:     ▆  1. └─basedosdados::bd_collect(.lazy_tbl = "br_me_rais.microdados_vinculos") Run rlang::last_trace(drop = FALSE) to see 1 hidden frame.
--
 
> | >
>


</body>
</html>

**Comment by ligiainhan** [comment]
** estou acompanhando esse vídeo de vcs e tentando fazer exatamente como mostra: https://www.youtube.com/watch?v=G78s_LXnwjY&t=786s e ainda estava tentando ver o cabeçalho da tabela

**Comment by gustavoalcantara** [comment]
rode o `rlang::last_error()` ou `rlang::last_trace()` depois do `bd_collect()`, por favor

**Comment by ligiainhan** [comment]
basedosdados::bd_collect(.lazy_tbl = tabrais)
Error in `basedosdados::bd_collect()`:
! `.lazy_tbl' should be a lazy tibble.
Run `rlang::last_trace()` to see where the error occurred.

**Comment by ligiainhan** [comment]
rlang::last_trace()
<error/rlang_error>
Error in `basedosdados::bd_collect()`:
! `.lazy_tbl' should be a lazy tibble.
---
Backtrace:
    ▆
 1. └─basedosdados::bd_collect(.lazy_tbl = tabrais)
Run rlang::last_trace(drop = FALSE) to see 1 hidden frame.

**Comment by gustavoalcantara** [comment]
@ligiainhan te aconselho a rodar o `basedosdados::read_sql("SELECT * FROM basedosdados.br_me_rais.microdados_vinculos LIMIT 100")` pra ver se tá trazendo o dataframe... 
Lembrando que nesse código vc vai baixar a RAIS inteira (por volta de 250gb +/-)... Por isso, acredito que seja melhor utilizar o read_sql(). 
Eu fiz no rcloud e o dataframe veio normal... Se quiser, entra no nosso discord... acredito que posso te ajudar melhor. 
Um adendo: esse vídeo não é nosso. É um vídeo utilizando nosso pacote numa versão anterior à essa que ele está hoje. Abraço!

**Comment by ligiainhan** [comment]
muito obrigada! Deu certo!

**Comment by ligiainhan** [comment]
onde está o discord?

**Comment by gustavoalcantara** [comment]
@ligiainhan aqui: https://discord.gg/Des93Zqh

**Comment by gustavoalcantara** [comment]
Fechando aqui porque está resolvido.
