### ISSUE TITLE
[dados]: `br_bd_diretorios_mundo.pais`, nome de países com `\xa0` (non-breaking space)

### ISSUE THREAD

**Issue by aspeddro** [basedosdados/mais#1674]
**Descrição**
O nome da Índia na coluna nome tem `\xa0`. Não verifiquei em outras colunas ou países.

**Reproduzir**
```python
df_dirs_mundo = bd.read_sql(
    "SELECT * from basedosdados.br_bd_diretorios_mundo.pais",
    billing_project_id="basedosdados-dev",
)

df_dirs_mundo[df_dirs_mundo["sigla_pais_iso2"] == "IN"].nome.unique()
```

```
array(['Índia\xa0'], dtype=object)
```

```
basedosdados --version
basedosdados, version 2.0.0b4
```

**Comment by gustavoalcantara** [comment]
Oi Pedro. Você testou no Bigquery? Por aqui está retornando corretamente. Será que não é problema de encode? Você tá fazendo no Colab/VScode/Jupyter? Abraços!

**Comment by tricktx** [comment]
Olá, Pedro. Tudo bem? 

Verifiquei através do `df_dirs_mundo.query("sigla_pais_iso2 == 'IN'")` para retornar toda a linha referente a linha e ela me retornou `Índia` de forma correta, segue o print: 

![Screenshot_35](https://github.com/basedosdados/mais/assets/105399231/c5c9b243-d780-40c7-afe9-6f4e6d8063e9)

Grande Abraço!

**Comment by aspeddro** [comment]
Oi, esse problema não é visível ao printar um dataframe.

```
>>> print('Índia\xa0')
Índia 
>>> 'Índia\xa0' == "Índia"
False
>>> len("Índia")
5
>>> len('Índia\xa0')
6
>>>
```

![image](https://github.com/basedosdados/mais/assets/16160544/c80d6c76-a2f1-44fa-adc7-6ff3a16dd803)

**Comment by gustavoalcantara** [comment]
acredito que isso subsidie https://sebhastian.com/remove-xa0-python/
Talvez tenha sido quando subiu a tabela pro BQ ou na publicação dos metadados...

**Comment by gustavoalcantara** [comment]
ou encode da tabela, também... acredito que tivemos situação semelhante quando trabalhamos com as tabelas do Cartão Corporativo

**Comment by gabrielle-carv** [comment]
Problema tava em espaços em brancos após as palavras, subi novamente sem eles. Acho que ta tudo certo agr!
