### ISSUE TITLE
NUMERIC vs FLOAT64

### ISSUE THREAD

**Issue by fernandascovino** [basedosdados/mais#168]
**Descrição**

O tipo `NUMERIC` não é nativo no pandas/numpy (aparece como `object` sendo `Decimal()`). Vale abrirmos a discussão se queremos manter esse tipo ou mudar para [`FLOAT64`](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#floating_point_types) entendendo melhor como eles são tratados.

Discutindo com o @polvoazul , possivelmente `NUMERIC` faça mais sentido com valores monetários em que queremos + precisão.

**Capturas de tela**
![image](https://user-images.githubusercontent.com/20743819/98468158-f0589100-21b7-11eb-8806-a36e0db52212.png)

**Comment by JoaoCarabetta** [comment]
Eu estava usando `NUMERIC` porque ele parecia abarcar todos os casos do `INT` e `FLOAT`. Mas, o problema de leitura para o pandas é um problema.

Também, podemos submeter um PR sugerindo a conversão de `NUMERIC` para `float` na biblioteca original.

Mas, me parece mais fácil só usar `FLOAT64` mesmo.

**Comment by rdahis** [comment]
Decidido então o tipo ser sempre `FLOAT64` daqui pra frente.
