### ISSUE TITLE
Template de PR com bases linkadas na descrição

### ISSUE THREAD

**Issue by fernandascovino** [basedosdados/mais#169]
Seria bom ter já linkado automaticamente as bases que estão subindo ahahah 

De qualquer forma, acho que vale termos uma descrição padrão com a lista das tabelas para facilitar na revisão - pois (1) são muitos arquivos adicionados no PR (2) hoje é mais simples porque subimos conjuntos inteiros e o nome do PR (por bom senso) é explicativo, mas depois poderão ser adicionados tabelas avulsas?

**Comment by rdahis** [comment]
Não sei se entendi. Dá um exemplo?

**Comment by rdahis** [comment]
Não sei criar template de PR :-D vou investigar aqui!

**Comment by fernandascovino** [comment]
desnecessário - vou fechar aqui
