### ISSUE TITLE
Implementar testes no pacote `basedosdados`

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/mais#1698]
**Link do Jira**: [EQP-118](https://equipeplataforma.atlassian.net/browse/EQP-118)

[EQP-118]: https://equipeplataforma.atlassian.net/browse/EQP-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by laura-l-amaral** [comment]
@d116626 e @gabriel-milan  posso fechar aqui? parece que está duplicado com issue #1691
