### ISSUE TITLE
[metadados] incluir 3 fontes externas

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/mais#1701]

**Comment by arthurfg** [comment]
- https://basedosdados.org/dataset/49280da5-06e2-48a5-9ffe-a14911ff0e87
- https://basedosdados.org/dataset/ddf50ea2-a802-4ce6-8a3b-201e73b47aae
- [APOD: Astronomy Picture of the Day](https://basedosdados.org/dataset/217b59c6-7865-432c-8976-dc9d988156c4)
