### ISSUE TITLE
[infra] Erro na conversão de formato DATE no download por pandas.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#181]
**Descrição**
Dá erro na conversão de formato DATE no download por pandas.

**Reproduzir**
Eu rodei:

```
import basedosdados as bd

test = "SELECT * FROM `basedosdados.br_tse_eleicoes.candidatos` WHERE ano = 2020"

df = bd.read_sql(test)
```

![WhatsApp Image 2020-11-25 at 23 09 27](https://user-images.githubusercontent.com/6617207/100383977-def2ef80-2fd3-11eb-819e-47a6a388be7e.jpeg)

**Comment by JoaoCarabetta** [comment]
Esse é o datetime que eles está tentando reconhecer:

`OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 972-01-30 00:00:00`

Temos dois jeitos de resolver isso:

1. Consertar a data na base. No caso o registro da Simone:
```
SELECT * FROM `basedosdados.br_tse_eleicoes.candidatos`
WHERE ano = 2020
and data_nasc =cast('0972-01-30' as date)
```

2. Modificar o código para não inferir datas automaticamente.

**Comment by JoaoCarabetta** [comment]
@rdahis não dá pra consertar essa tabela? Tem algumas datas que são erros óbvios, tipo '0972-01-30' que deveria '1972-01-30' e isso quebra o pandas.

**Comment by rdahis** [comment]
É mesmo? Sabia que dava esses erros por causa de datas assim. E se tivéssemos dados do ano 972?! Aí seria `972-01-30`?

**Comment by JoaoCarabetta** [comment]
nada, o timestamp do pandas que limita as datas. Ele acha inválido. Deve ter um bom motivo, mas por enquanto parece ser uma limitação
