### ISSUE TITLE
requirements.txt não inclui todos os pacotes necessários

### ISSUE THREAD

**Issue by hsxavier** [basedosdados/mais#183]
**Describe the bug**
Se você criar um environment novo e instalar os pacotes necessários de acordo com o requirements.txt, ficam faltando:
pandas-gbq
tqdm

**To Reproduce**

1. Entre no diretório raiz do projeto.
2. Use os comandos:
```
python -m venv env_teste
source env_teste/bin/activate
pip install -r requirements.txt
python
import basedosdados
```
**Expected behavior**
Deveria carregar sem erros.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser firefox
 - Version ?

**Comment by JoaoCarabetta** [comment]
Para subir um ambiente local tente usar o comando:

`make create-env`
