### ISSUE TITLE
Download no R da base ADH com erro nas linhas  

### ISSUE THREAD

**Issue by mariana-carvalho** [basedosdados/mais#189]
**Descrição**
Download no R da base ADH com erro nas linhas. Em vez de baixar 5565 obs por ano (1991, 2000 e 2010), aparecem vários zeros. Esse erro não ocorre no Python. 

**Reproduzir**
Passos para reproduzir o comportamento:
1. query = "SELECT * FROM `basedosdados.mundo_onu_adh.municipios`"
2. d = dbGetQuery(con, query)
3. table(d$ano)
0 1991 2000 2010 
5949 5565 1422 3759 

**Comportamento esperado**
table(d$ano) devia ter: 
1991 2000 2010 
5565 5565 5565

**Comment by JoaoCarabetta** [comment]
Olá Marina, aparentemente esse é um [bug do BigQuery](https://github.com/r-dbi/bigrquery/issues/311), mas tem uma maneira de resolver.

Precisamos paginar o resultado, `page_size`, em resultados menores. Tente usar esse código:

```
if (!require("bigrquery")) install.packages("bigrquery")
library("bigrquery")

projectid = "basedosdados"
sql = "SELECT * FROM basedosdados.mundo_onu_adh.municipios"

d <- bq_table_download(bq_project_query(projectid, sql), page_size=500)

table(d$ano)

1991 2000 2010 
5565 5565 5565 
```

Se puder, teste no seu computador. Se funcionar, teremos que atualizar a documentação @fernandascovino

**Comment by rdahis** [comment]
Testei aqui no meu computador, consegui reproduzir o erro, e a solução do @JoaoCarabetta funcionou.

**Comment by mariana-carvalho** [comment]
Ops. Desculpa pela falta de resposta e obrigada pela ajuda.

**Comment by fernandascovino** [comment]
boa galera! @mariana-carvalho sem problema algum! resolvido então, vou fechar aqui o issue e adicionar essa flag de `page_view` na documentação 😉
