### ISSUE TITLE
Tabelas que não estão funcionando

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/mais#191]
**Descrição**
Tabelas que não estão funcionando.

**Reproduzir**

Identifiquei essas tabelas que não estão funcionando quando fizemos a varredura do 1-click download.

- [x] 'select * from basedosdados.br_cgu_servidores_executivo_federal.servidores_civis_cadastro',
- [x] 'select * from basedosdados.br_tse_eleicoes.perfil_eleitorado',
- [x] 'select * from basedosdados.br_tse_eleicoes.resultados_partido_secao',
- [x] 'select * from basedosdados.br_tse_eleicoes.resultados_candidato_secao',
- [x] 'select * from basedosdados.br_sp_gov_orcamento.receita_prevista'

**Comment by rdahis** [comment]
Já sabemos o motivo das tabelas não funcionarem? É query do publish quebrada?

**Comment by JoaoCarabetta** [comment]
Cada uma tem um motivo diferente. Tem que fazer a query e ver o erro. Pode ser problema no csv, na query publish, etc

**Comment by rdahis** [comment]
Essas rodaram normal aqui:
`basedosdados.br_tse_eleicoes.resultados_partido_secao` (~9GB)
`basedosdados.br_tse_eleicoes.resultados_candidato_secao` (~25GB)

**Comment by rdahis** [comment]
Resolvido: `basedosdados.br_tse_eleicoes.perfil_eleitorado`

**Comment by JoaoCarabetta** [comment]
Perfil eleitorado funcionando no site

**Comment by rdahis** [comment]
Testei a tabela `br_tse_eleicoes.candidatos` no 1-click download e ainda veio sem header.

**Comment by d116626** [comment]
Tabela  `br_sp_gov_orcamento.receita_prevista` corrigida.

**Comment by fernandascovino** [comment]
a tabela do DOU está funcionando? não consigo fazer a query dela aqui

**Comment by fernandascovino** [comment]
pelo que entendi dos comentarios estão todas resolvidas? @JoaoCarabetta adicionei um check em cada tabela na sua descricao, ajustem como for necessario
