### ISSUE TITLE
Base: DOU

### ISSUE THREAD

**Issue by fernandascovino** [basedosdados/mais#197]
A serem organizados por @hsxavier 

- [ ] Separar PR #184 dos militares e DOU - já tem uma só dos militares em #182 
- [ ] Tentar otimizar a execução da query

Hoje funciona mas precisa atualizar a página e demora >2 minutos, não fica muito claro para quem não mexe no BQ de que está rodando. Como podemos melhorar aqui?

**Comment by rdahis** [comment]
Fechado no PR #303.
