### ISSUE TITLE
Pasta `code` faltando em multiplas bases

### ISSUE THREAD

**Issue by fernandascovino** [basedosdados/mais#201]
Diversas bases no repositório estão sem a pasta de códigos de tratamento, abrindo o issue para mapearmos.

- [ ] Verificar bases sem código
- [ ] Subir códigos em `bases/[dataset_id]/code`

**Comment by rdahis** [comment]
Isso acontece porque o Github ignora pastas vazias (quando não subimos nenhum código).

**Comment by JoaoCarabetta** [comment]
Mas todas os datasets deveriam ter um código não? Pelo menos um README dizendo o que foi feito, se for só o download

**Comment by rdahis** [comment]
Acaba que nem todas tem. Algumas são views de outros datasets, outras são super simples que nem tem código de limpeza, etc.

**Comment by d116626** [comment]
Também tinha entendido que era algo opcional

**Comment by JoaoCarabetta** [comment]
Eu acho que ou tem a pasta `code` ou tem um README explicando pq não tem a pasta `code`

**Comment by fernandascovino** [comment]
Sim, para deixar bem explícito e transparente o que foi feito, podemos deixar padronizado:

- pasta `code` sempre com no mínimo um arquivo `readme`
- caso não tenha código de tratamento, deixar explícito isso no `readme`
- caso tenha código, subir na pasta `code` e adicionar observações no `readme` caso necessário

O template já tem essa pasta, correto? Posso adicionar no `readme` do template essas instruções.

**Comment by rdahis** [comment]
No momento temos um `readme` na pasta do dataset, mas não nas pastas de tabelas. Acho que podemos fazer esse esquema padronizado no `readme` do dataset mesmo né. Tem que ficar no mesmo nível do código, que é a nível de dataset.

**Comment by fernandascovino** [comment]
Editei o template do `readme` de `dataset` aqui: https://github.com/basedosdados/mais/pull/210

Acho que isso já resolve os casos que efetivamente não tem código (subimos os dados brutos). Ainda assim, devemos verificar com todo mundo se tem algum código que não está sendo publicado com as tabelas.
