### ISSUE TITLE
Criar funcionalidade no CLI para mais de um repositório clonado localmente.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#213]
**Problema**
Hoje, o CLI depende do `config.toml` que tem a variável `metadata_path` para regular de onde puxar arquivos pro CLI. Isso não permite que eu clone o repositório `mais` em mais de um lugar localmente (para mexer em branches diferentes) e use o CLI para interagir com o BigQuery.

**Sugestão de solução**
Fazer o CLI reconhecer o working directory no terminal e usar esse como `metadata_path`.

**Comment by JoaoCarabetta** [comment]
Quando você entra numa branch `checkout <branch_name>` os arquivos são modificados automaticamente. Tu não precisa ter várias cópias do repositório.

**Comment by rdahis** [comment]
Sim sim eu sei. Mas ainda seria útil. Por exemplo, quando precisei fazer um clone do repositório do @hsxavier.

**Comment by JoaoCarabetta** [comment]
ué, só clonar o repo dele numa branch

**Comment by rdahis** [comment]
Dá pra fazer isso? Ops :-) Achei que dava pra clonar só uma branch numa branch.

**Comment by JoaoCarabetta** [comment]
Tu copia a `master` dele para uma branch sua
