### ISSUE TITLE
Erro no deploy do docs.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#214]
**Descrição**
Tá dando erro no deploy do docs no Github. Colando um screenshot da tela abaixo. É algum problema na função `set_config_file()` do `cli.py`.

![Screen Shot 2021-01-07 at 2 44 58 PM](https://user-images.githubusercontent.com/6617207/103953532-28684b80-50f7-11eb-8d94-7ab9bbb5e97c.png)

**Comment by fernandascovino** [comment]
@JoaoCarabetta não ta dando confusão com a instalação do `basedosdados`? Essas msgs são da configuração inicial do CLI:

`We need to finish setting up your basic environment!`

`What is your project_id? ...`

**Comment by JoaoCarabetta** [comment]
A gente precisa do basedosdados no `requirements-dev.txt`? Porque é ele que está dando pau

**Comment by fernandascovino** [comment]
@JoaoCarabetta você que me diz, tu que colocou neném KKKKKKKK

![image](https://user-images.githubusercontent.com/20743819/104033692-a0de1380-51ae-11eb-8458-9c528e71ac44.png)

**Comment by JoaoCarabetta** [comment]
jenio 🥇 

resolvido já
