### ISSUE TITLE
Criar Actions que automaticamente replica dados do proposal em produção

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/mais#218]
Quando 'Merge Pull Request' é acionado aciona um github Actions

1. Checa se tem mudanças na pasta `bases`
2. Copia todo o conteúdo do storage do proposal daquele `dataset_id` para bucket de produção
3. Recria ambiente em produção com `table create` e `table publish`

**Comment by d116626** [comment]
Resolvido no PR #269.
