### ISSUE TITLE
Dados ausentes na base do PIB municipal

### ISSUE THREAD

**Issue by wagfoliveira** [basedosdados/mais#222]
Alguns dados estão ausentes na base do PIB dos municípios em comparação à original disponibilizada pelo IBGE.
Este issue foi reportado inicialmente aqui: https://github.com/basedosdados/mais/issues/220

Um exemplo: baixando diretamente os dados em .csv [aqui](https://basedosdados.org/dataset/br-ibge-pib) e filtrando para o município de Porto Velho (RO) - código 1100205 - temos dados de PIB de 2002 a 2010 e depois células em branco de 2011 a 2018.

Ao gerar a tabela a partir do [SIDRA](https://sidra.ibge.gov.br/pesquisa/pib-munic/tabelas), pode-se observar que os dados de 2002 a 2010 coincidem e que os dados de 2011 a 2018 estão disponíveis.

Isso também acontece com outros municípios (total de 110). No caso da coluna PIB, há 970 células vazias de um total de 94616 (~1%).

**Comment by rdahis** [comment]
Ótimo achado, obrigado. Estava sendo causado por uma questão de formatação de dados no Stata que depois era lido como NULL no BigQuery.

Já subi o arquivo corrigido e atualizei os metadados.
