### ISSUE TITLE
Modificações faltantes com a versão 1.2.2

### ISSUE THREAD

**Issue by fernandascovino** [basedosdados/mais#224]
Esses abaixo devem ser mudados para `basedosdados-dev`?

https://github.com/basedosdados/mais/blob/6d457c8f68c5a55ab2b4c3dc4923fb4edf905e7c/basedosdados/base.py#L193

https://github.com/basedosdados/mais/blob/6d457c8f68c5a55ab2b4c3dc4923fb4edf905e7c/basedosdados/base.py#L214

**Comment by rdahis** [comment]
E também a primeira linha do publish.sql. Tem que aparecer "basedosdados-dev" ao invés de "basedosdados".

**Comment by fernandascovino** [comment]
hnmnm @rdahis essa parte vem de outro arquivo para escrita ne, acho que é aqui mas que herda esse `client` da classe `Base`, no mesmo .py dos anteriores https://github.com/basedosdados/mais/blob/6d457c8f68c5a55ab2b4c3dc4923fb4edf905e7c/basedosdados/table.py#L173

**Comment by d116626** [comment]
Mesmo problema do #236
