### ISSUE TITLE
Consertar path para rodar no Windows

### ISSUE THREAD

**Issue by fernandascovino** [basedosdados/mais#226]
Rever pontos com hardcode `/.basedosdados/templates` e demais que tenham `/`

https://github.com/basedosdados/mais/blob/6d457c8f68c5a55ab2b4c3dc4923fb4edf905e7c/basedosdados/base.py#L239

**Comment by kimjoaoun** [comment]
Acredito que isso possa ser resolvido usando a biblioteca `pathlib`. Ela já vem com o Python 3.4 (ou mais), e faz a conversao de UNIX-style Paths para os paths do MS-DOS/Windows.
