### ISSUE TITLE
Dados ausentes de população municipal para o ano 2000

### ISSUE THREAD

**Issue by wagfoliveira** [basedosdados/mais#230]
Olá,

Baixando os dados de população por aqui: https://basedosdados.org/dataset/br-ibge-populacao
Percebi que não vem a população municipal do ano de 2000, sendo que os dados estão disponíveis no link externo fornecido
(https://www.ibge.gov.br/estatisticas/sociais/populacao/9103-estimativas-de-populacao.html?=&t=downloads).

Como consta o ano nos metadados, pode ter sido só um deslize na hora de subir os dados. De todo modo, sinalizo aqui caso vocês ainda não tenham visto.

Abs,
Wagner

**Comment by rdahis** [comment]
Consertado. Valeu por achar o erro. Loucura ter dado isso, mas agora tá certo 1991-2019.
