### ISSUE TITLE
Inconsistência na tabela receita_candidato

### ISSUE THREAD

**Issue by d116626** [basedosdados/mais#235]
**Descrição**
Encontrei uma inconsistência na tabela `basedosdados.br_tse_eleicoes.receita_candidato`. Para o ano de 2020 os tipos de receita estão na coluna `origem_receita`, já para o ano de 2016 estão na coluna `tipo_fonte_receita`.

**Comment by rdahis** [comment]
Consertado em `basedosdados-dev.br_tse_eleicoes.receitas_candidato`. Esperando sair a infra de `release` pra entrar no `basedosdados` público.
