### ISSUE TITLE
Project_id hard coded no publish.sql

### ISSUE THREAD

**Issue by d116626** [basedosdados/mais#236]
**Descrição**
Quando o arquivo publish.sql é criado o projeto para onde a VIEW é criada está hard coded como basedosdados.

**Comment by JoaoCarabetta** [comment]
Deveria vir com o project_id do public

**Comment by d116626** [comment]
Acho que encontrei o problema, no arquivo `publish.sql` dentro da pasta `.basedosdados/template/table` tem essa linha de código:

```
{% set project = project_id.split('-') %}
CREATE VIEW {{ project[0] }}.{{ dataset_id }}.{{ table_id }} AS
SELECT 
{% for column in columns|list + partition_columns|list -%}
{%- if not loop.last -%}
    SAFE_CAST({{ column }} AS STRING) {{ column }},
{% else -%}
    SAFE_CAST({{ column }} AS STRING) {{ column }}
{% endif -%}{% endfor -%}
from {{ project_id }}.{{ dataset_id }}_staging.{{ table_id }} as t
```
Acho que o problema tá ali no `project_id.split('-')`, já que o projeto que to usando é `basedosdados-dev`

**Comment by d116626** [comment]
Fiz a mudança local no `publish.sql` da pasta `.basedosdados` mas não funcionou pq ela é substituída pelo arquivo da biblioteca, quando mudei em `path_to_lib/basedosdados/config/template/table` funcionou
