### ISSUE TITLE
Metadata_path diferente do original

### ISSUE THREAD

**Issue by d116626** [basedosdados/mais#237]
**Descrição**
Durante a configuração para upload o `metadata_path` está sendo convertido para .lower(). Se o meu caminho original tiver alguma maiúscula vai gerar erro.

**Comment by JoaoCarabetta** [comment]
Acho que podemos resolver isso passando um parametro para controlar se a string vai para `.lower()`. É só adicionar esse parametro em `_selection_yn` e carregar ele para `_input_validator`.

**Comment by d116626** [comment]
@JoaoCarabetta, tenho uma sugestão de solução, veja o que acha. Se fizermos a modificação de: 
https://github.com/basedosdados/mais/blob/d3ed6f9f49a23fe788daa53dfacaf3f144a07717/basedosdados/base.py#L70-L77 

Para:
```
def _input_validator(context, default=""):

    var = input(context)

    if "metadata path" in context:
        return var
    elif var:
        return var.lower().strip()
    else:
        return default.lower().strip()
```

**Comment by d116626** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bug metadata_path .lower( ) _________ Issue #237](https://trello.com/c/MtyphsyZ/39-bug-metadatapath-lower-issue-237)

**Comment by JoaoCarabetta** [comment]
```
def _input_validator(context, default="", with_lower=True):

    var = input(context)

    to_lower = lambda x: x.lower() if with_lower else x
 
    if var:
        return to_lower(var.strip())
    else:
        return  to_lower(default.strip())
 ```
 
 podemos fazer assim também. Aí mantemos o strip().
