### ISSUE TITLE
Preservar o table_config.yaml caso exista

### ISSUE THREAD

**Issue by d116626** [basedosdados/mais#240]
Adicionar uma opção parecida com o `force_dataset`  para preservar o `table_config.yaml`. talvez um `force_table`?

https://github.com/basedosdados/mais/blob/d3ed6f9f49a23fe788daa53dfacaf3f144a07717/basedosdados/table.py#L184-L191

**Comment by JoaoCarabetta** [comment]
Talvez um `use_existing_config` seja mais intuitivo. O `force_dataset` na real só cria o dataset se ele não existir.
