### ISSUE TITLE
Atualizar os templates no CLI

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#242]
**Descrição**
Mudei os templates de dataset e table aqui no Github mas não aparece ainda no CLI local. Mesmo depois de um `basedosdados config refresh_template`.

**Comment by JoaoCarabetta** [comment]
1. Pare de mudar as coisas no master
2. Versão de prerelease estão com as modificações `pip install basedosdados==1.3.0a3`

**Comment by rdahis** [comment]
=)
