### ISSUE TITLE
Criar ferramenta que avise quando tabelas devem ser atualizadas

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#245]
Como primeiro passo na direção de termos um pipeline de atualização automática de dados, seria legal já ter uma ferramenta que avise quando cada tabela precisa ser atualizada.

Inputs por tabela:

- Frequência de atualização
- Data de última atualização

Output: um calendário ou alertas para atualização. Já pode automaticamente ligar com um issue no Github com _assignees_.

**Comment by d116626** [comment]
Mesmo Issue do #309
