### ISSUE TITLE
Links quebrados/expirados na documentação

### ISSUE THREAD

**Issue by RodrigoATorres** [basedosdados/mais#246]
Link para grupo no discord em `docs/colab_data.md` aparentemente está expirado.
Link na seção Contriubua do `REAME.md` está apontando para uma página com referências quebradas.

  > Veja mais como contribuir [aqui](https://basedosdados.github.io/mais/github/).
  
  imagino que o link correto seja https://basedosdados.github.io/mais/support/ ou https://basedosdados.github.io/mais/colab_data/

 ps.: parabéns pelo trabalho, pessoal!

**Comment by rdahis** [comment]
Ótimo. Valeu @RodrigoATorres!

**Comment by fernandascovino** [comment]
valeu! vou endereçar amanhã ;)
