### ISSUE TITLE
Table().publish() executa mas não cria tabela em prod

### ISSUE THREAD

**Issue by d116626** [basedosdados/mais#276]
**Descrição**
Ao publicar uma tabela utilizando o método `publish()` do `Table()`, as vezes ele roda normalmente e a tabela não é publicada em prod. Sugiro fazer uma checagem apos a publicação e caso a VIEW não tenha sido criada printar uma mensagem de erro com possíveis causas, como por exemplo nome de variáveis erradas no `publish.sql` ou no `table_config.yalm`.

Incluir checagem apos a etapa de criação que ocorre nessa parte do código:

https://github.com/basedosdados/mais/blob/93444a39a4f34285716dbe905c9ae30c80cc01ca/basedosdados/table.py#L423-L425

**Comment by Hellcassius** [comment]
- Possivelmente adicionar um check no publish.sql para destacar erros 
- checar se a tabela foi realmente publicada
