### ISSUE TITLE
Lógica do table.create tem que ser aprimorada

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/mais#292]
**Descrição**
Nem todos os casos dos parametros `if_exists_...` estão sendo contemplados. Precisamos fazer testes mais robustos.

**Exemplos**

1. Caso 1
    Arquivos de configuração: não existe
    Chamado: `tb.create(file_path, if_table_config_exists='pass')`
    Reposta Atual: Retorna erro de que o arquivo não existe
    Reposta Esperada: Cria o arquivo sem erros

**Comment by d116626** [comment]
Caso 2
  Dado no storage: existe
  Chamado: tb.create( if_storage_data_exists='pass',if_table_config_exists='replace')
  Reposta Atual: Cria config que não tem relação com as colunas que já estão no storage
  Reposta Esperada: Retornar erro, avisar que precisa de um sample dos dados

**Comment by JoaoCarabetta** [comment]
https://docs.google.com/spreadsheets/d/1IPrcsPOlkGxdknwY1YMJah2tO0Hej5Fk9UI-TlGpQuU/edit#gid=0
