### ISSUE TITLE
Adicionar suporte para criar campos no publish.sql que não existem no staging

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/mais#294]
**Descrição**
Na descrição de cada coluna no `table_config` há um atribute chamado `is_in_staging`. Ele teoricamente serve para indicar se devemos esperar essa coluna no staging, ou não. Isso serviria para adicionar colunas extras no `publish.sql`.

Porém, não há menção no código `python` da variável `is_in_staging`. Portanto, ela não está sendo usada.

**Reproduzir**
Basta adicionar uma nova coluna no `publish.sql`, adicionar ela no `table_config.yaml` com `is_in_staging=False` e verá o erro:
```
Exception: Column {'name': 'geo_veiculo', 'description': 'Localização do veículo em tipo geométrico', 'is_in_staging': False, 'is_partition': False} was not found in schema. Are you sure that all your column names between table_config.yaml and publish.sql are the same?
```

**Comportamento esperado**
Agir normalmente e adicionar a nova coluna na tabela final

**Comment by d116626** [comment]
Provavelmente isso se relaciona com um outro problema. 
Quando chama o `Table().update()` pra uma tabela que já existe, com argumento `all` ou `staging` a configuração existente é sobrescrita. No caso em que a tabela é particionada as configurações de `Modo de particionamento do Hive` é perdida e a VIEW do `prod` vai dar erro porque não consegue achar as colunas que da partição.

**Comment by d116626** [comment]
Acho que quando rola o `tb.update('prod')` ele não da load da `external_config` 

https://github.com/basedosdados/mais/blob/0de07996d55c111bbbc7f8e9b1911090e49364a2/basedosdados/table.py#L371-L374

Provavelmente tem que dar load na `external_config` que está praticamente hardcoded no `tb.create`

https://github.com/basedosdados/mais/blob/0de07996d55c111bbbc7f8e9b1911090e49364a2/basedosdados/table.py#L311-L331
