### ISSUE TITLE
TypeError: init_table() got an unexpected keyword argument 'if_folder_exists'

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#298]
**Descrição**
Rodando um simples `basedosdados table init` ele retorna esse erro:

```TypeError: init_table() got an unexpected keyword argument 'if_folder_exists'```

Minha tela:
![Screen Shot 2021-02-25 at 10 17 47 AM](https://user-images.githubusercontent.com/6617207/109198270-e0f35880-7752-11eb-8548-e2db747e3b5c.png)

**Comment by d116626** [comment]
@Hellcassius, esse issue é o que foi resolvido aqui? Se sim então só precisa lançar uma versão nova.
https://github.com/basedosdados/mais/blob/b1eccbfbd8671a80713712ac2a86f11f44080e96/basedosdados/cli.py#L167-L181
