### ISSUE TITLE
Table.update(mode=all) sobrescreve as configs originais do Table.create()

### ISSUE THREAD

**Issue by d116626** [basedosdados/mais#302]
**Descrição**

Quando chama o `Table().update()` pra uma tabela que já existe, com argumento `all` ou `staging` a configuração existente é sobrescrita. No caso em que a tabela é particionada as configurações de `Modo de particionamento do Hive` é perdida e a VIEW do `prod` vai dar erro porque não consegue achar as colunas da partição. 

**Reproduzir**
Subir uma tabela particionada então fazer update com `mode=staging` ou `mode=all`

**Hint**
Acho que quando rola o `tb.update('prod')` ele não da load da `external_config`  e no `hive_partitioning`

https://github.com/basedosdados/mais/blob/0de07996d55c111bbbc7f8e9b1911090e49364a2/basedosdados/table.py#L371-L374

Provavelmente tem que dar load na `external_config` que está praticamente hardcoded no `tb.create()`

https://github.com/basedosdados/mais/blob/0de07996d55c111bbbc7f8e9b1911090e49364a2/basedosdados/table.py#L311-L331

**Comment by JoaoCarabetta** [comment]
Também tive esse problema
