### ISSUE TITLE
[dados] Base: Frota de Veículos (Ministério da Infraestrutura/DENATRAN)

### ISSUE THREAD

**Issue by pedrocastroo** [basedosdados/mais#318]
**Descrição do dataset**

Já está na [tabela de prioridades](https://docs.google.com/spreadsheets/d/1jnmmG4V6Ugh_-lhVSMIVu_EaL05y1dX9Y0YW8G8e_Wo/edit?usp=sharing)? Não

Dataset_id: `br_denatran_frota`

Table_id (1 ou mais): `frota_uf_tipo`, `frota_municipio_tipo`

Fonte de dados: https://www.gov.br/infraestrutura/pt-br/assuntos/transito/conteudo-denatran/estatisticas-frota-de-veiculos-denatran

Anos: de 2003 até 2020

**Como você pode contribuir?**

Limpeza e disponibilização dos dados.

**Comment by rdahis** [comment]
Ótimo. Sugiro as tabelas serem `uf_tipo` e `municipio_tipo` dado que frota já está no nome da base.

E por que só a partir de 2004 se há dados para anos anteriores?

**Comment by rdahis** [comment]
A partir de 2003 são em outra granularidade temporal?

Vamos começar só com a partir de 2003 mesmo.

**Comment by pedrocastroo** [comment]
Isso, são mensais.

**Comment by rdahis** [comment]
Legal, manda ver aí.

**Comment by rdahis** [comment]
@pedrocastroo algum avanço?

**Comment by pedrocastroo** [comment]
Sim, `frota_uf_tipo`está pronto. Fazendo alguns ajustes nos dados por município e melhorando o script. Logo em breve estará pronto.

**Comment by pedrocastroo** [comment]
#409 enviada
