### ISSUE TITLE
[infra] Storage.download

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/mais#345]
**Descreva a solução que você gostaria**
Implementar o download na classe Storage, `Storage().download()`

Isso é útil quando precisamos automatizar o tratamento do `raw` para o `staging`.

A Laura já implementou [aqui](https://github.com/RJ-SMTR/maestro/blob/9c645b72f6002e19d43035501b2c0a63b52ec5a2/repositories/capturas/br_rj_riodejaneiro_brt_rdo/registros.py#L158).

Sugestão de como funcionaria:

    def download(
        self,
        filename="*",
        savepath="",
        partitions=None,
        mode="raw",
        if_exists="raise"
    ):
        """ Download files from storage from <bucket_name>/<mode>/<dataset_id>/<table_id>/<partitions>/<filename> 
        
        There are 2 modes:
        * `raw`: download file from raw mode
        * `staging`: download file from staging mode 
        
        You can also use the `partitions` argument to choose files from a partition.

        Args:
            filename (str): File to download. "*" download all files. Defaults to "*".
            savepath (str,  pathlib.PosixPath): Where to save the file. Defaults to "".
            mode (str): Folder of which dataset to download [raw|staging]
            partitions (str, pathlib.PosixPath, or dict): Optional.
                    *If adding a single file*, use this to add it to a specific partition.
                    * str : `<key>=<value>/<key2>=<value2>`
                    * dict: `dict(key=value, key2=value2)`
            if_not_exists (str): Optional.
                What to do if data not exists
                * 'raise' : Raises NotFoundData exception
                * 'pass' : Do nothing
        """

**Comment by Hellcassius** [comment]
@JoaoCarabetta É uma boa ser pelo filename? A pessoa teria que ir até o Storage e ter permissão de leitura pra poder saber o esse filename. Pensei em alguma implementação parecida com a do copy_table, pegando os blobs via dataset_id e table_id, mas tudo depende de como serão os casos de uso

**Comment by JoaoCarabetta** [comment]
Então, por padrão o `"*"` permite pegar tudo. Mas, pode ser específica se for o caso.

**Comment by Hellcassius** [comment]
Já abri o PR #349 com um esqueleto funcional de como vai ficar
