### ISSUE TITLE
[infra] Criar infra para download de arquivos auxiliares a tabelas.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#348]
**Sua solicitação de recurso está relacionada a um problema? Por favor descreva.**
Atualmente não temos uma forma de guardar e disponibilizar arquivos auxiliares a tabelas. Exemplos: arquivos de formatos variados (txt, doc, pdf) com descrições, instrumentos de coleta, relatórios, etc.

**Descreva a solução que você gostaria**
Idealmente teríamos um bucket no Storage só para arquivos auxiliares. Cada tabela de dados teria uma pasta equivalente nesse bucket só para arquivos auxiliares. Desse bucket, seriam gerados arquivos zip automaticamente incluindo tudo que estiver lá. E seria gerada uma url para esse zip, que podemos sempre referenciar nas documentações, readmes, etc.

**Descreva alternativas que você considerou**
Uma alternativa é subir diretamente no Github. Mas isso é ruim porque arquivos assim muitas vezes são pesados e não mudam no tempo.

**Comment by Hellcassius** [comment]
Estou procurando um jeito de gerar o zip direto, mas pode ser que fique complicado. Existe a possibilidade de nesse bucket já subirmos os aqruivos `.zip` e gerar essa url?

**Comment by rdahis** [comment]
Pode ser também né? Se gerar esse `.zip` automaticamente for muito trabalho, vamos nessa outra solução.

**Comment by Hellcassius** [comment]
Gerar a URL é bem automático, mas acredito que gerar a url pro `.zip` se ele não está guardado lá fique estranho. Uma coisa fácil seria criar alguma função do tipo `download_auxilary_files` e quando a pessoa executar, baixa em zip pra máquina dela, mas pra que a URL pro `.zip` possa ser referenciada, acredito que faça mais sentido já upar em `zip` mesmo.

**Comment by JoaoCarabetta** [comment]
Vamos por partes.

1. Esses arquivos auxiliares precisam estar na metadata da tabela ou do dataset. Precisamos definir onde eles ficarão. Isso é importante para exibir os arquivos no futuro, para ter algum controle sobre eles e para gerar a descrição da tabela elencando esses arquivos de suporte.

2. Precisa de zip? Não faria mais sentido criar um link para cada arquivo? Assim dá bem menos trabalho para implementar.

3. Precisaríamos criar uma outra pasta  `auxilary_files` com a mesma estrutura de dataset_id e table_id

4. Também precisaríamos criar no CLI uma função `Storage().upload_auxilary_files()`  e outra `Download().get_auxiliary_files()`

**Comment by rdahis** [comment]
Como solução temporária para os microdados do Censo (PR #277), vou criar a pasta `basedosdados/basedosdados-public/auxiliary-files` no storage. Ok?

**Comment by JoaoCarabetta** [comment]
coloque no project_id `basedosdados-staging`.

E no bucket:
`basedosdados/auxiliary-files/<dataset_id>/<table_id>`

**Comment by rdahis** [comment]
A pasta no mesmo nível de `raw` e `staging`?

**Comment by d116626** [comment]
@JoaoCarabetta, acho que é melhor fazer o link com o dataset do que com a tabela, ai dentro do zip, organiza o que for de cada tabela, se necessário.

**Comment by rdahis** [comment]
Concordo com o @d116626.

**Comment by JoaoCarabetta** [comment]
Podemos adicionar o link para essas infos no template da descrição do dataset/tabela.
