### ISSUE TITLE
[infra] gcp timeout

### ISSUE THREAD

**Issue by aryvini** [basedosdados/mais#371]
**Descrição**
Ao realizar consultas utilizando o package para python um erro de timeout é retornado.  As autenticações já foram efetuadas e o parâmetro `billing_project_id` inserido

**Passos para reproduzir o comportamento:**
```
import basedosdados as bd

df = bd.read_table(
        dataset_id='br_ibge_populacao',
        table_id='municipios',
        billing_project_id='basedosdados-ary',
        limit=100)
```

**Comportamento esperado**
Download da consulta para um pandas dataframe.

**Log do erro**
O retorno da execução do código acima pode ser encontrado no arquivo:
[error.txt](https://github.com/basedosdados/mais/files/6217572/error.txt)

**Desktop (preencha as seguintes informações):**
  - SO: win10
  - Anaconda
  - Python 3.7.9
  - Jupyter lab
  - basedosdados 1.4.10

**Comment by JoaoCarabetta** [comment]
Resolvido com:

```
import google.cloud.bigquery_storage_v1.client
from functools import partialmethod

# Set a two hours timeout
google.cloud.bigquery_storage_v1.client.BigQueryReadClient.read_rows = partialmethod(google.cloud.bigquery_storage_v1.client.BigQueryReadClient.read_rows, timeout=3600*2) ```
