### ISSUE TITLE
[infra] colunas em comum de diferentes datasets

### ISSUE THREAD

**Issue by d116626** [basedosdados/mais#374]
- Hoje a forma como disponibilizamos o código e informações sobre a captura estão meio confusas. Esse diretório por exemplo https://github.com/basedosdados/mais/tree/master/bases/br_ibge_censo_demografico, tem tanto tabelas que eu subi quanto que o @rdahis subiu, não da pra saber quais arquivos se relacionam com quais tabelas. Temos que pensar em uma forma mais esperta de organizar isso.
 - Como mostrar quais tabelas tem colunas em comum com tabelas de outros datasets?

**Comment by rdahis** [comment]
No ponto 1, o que você quer dizer com "quais arquivos se relacionam com quais tabelas"?

No ponto 2, por enquanto minha solução tem sido manter uma lista das `foreign keys` na [documentação de análise](https://basedosdados.github.io/mais/analysis/). Mas de fato seria melhor ter algo mais perto dos dados.

**Comment by rdahis** [comment]
Fechando aqui pois agora vamos guardar o metadado `coluna_diretorio` para colunas. Isso será o suficiente para identificar as chaves primárias da BD+, que são as chaves primárias dos diretórios.
