### ISSUE TITLE
[dados] Criar infra para tabelas-dicionário.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#375]
**Problema atual**: há várias tabelas que precisam de dicionário (e.g. Censos, RAIS) e nós não temos ainda uma forma boa para disponibilizar essas informações.

As soluções temporárias até agora:

- Botar o dicionário na descrição da variável. Problemas: (1) não é prático para substituições, (2) pode ficar impraticável se dicionários são longos.
- Subir dicionários como arquivos auxiliares no storage. Problema: (1) não é solução automatizada para substituições.

**Proposta de solução**: Criar "tabelas-dicionário" para cada dataset. A tabela terá 4 colunas: `tabela`, `coluna`, `chave`, `valor`.

Com isso, para substituir chaves por valores na tabela original, basta dar um JOIN sub-selecionando a tabela e coluna.

**Comment by rdahis** [comment]
Algum comentário aqui @JoaoCarabetta @d116626? Acham que é isso mesmo?

**Comment by JoaoCarabetta** [comment]
Acho que isso está relacionado com o issue #383. Podemos pensar em uma solução conjunta de gestão dos metadados.
