### ISSUE TITLE
[infra] explicitar erro

### ISSUE THREAD

**Issue by d116626** [basedosdados/mais#379]
**Descrição**
Não sei qual a função desse `try` ao chamar o `datase.init()`. Tive esse erro e estava sendo jogado pro `dataset.create()`, mas na verdade o erro estava no `datase.init()`, quando removi o `try` ficou mais claro que o erro se resolvia deletando a pasta do dataset que já existia. Ou a gente tira esse `try`, ou faz um raise decente.

https://github.com/basedosdados/mais/blob/f1847ca3a0511241c4b192b676450f86c5f6d937/python-package/basedosdados/table.py#L360-L365

Como reproduzir:
Deletar o arquivo `dataset_config.yaml` em seguidar tentar executar o `Table().create()`

**Comment by rdahis** [comment]
Pode fechar?
