### ISSUE TITLE
[infra] Funções auxiliares para dados no R/Python.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#381]
Criar funções dentro da API `basedosdados` de R e Python para facilitar o dia a dia da equipe de dados com tarefas repetidas.

(adicionem mais ideias aí nos comentários)

## Funcionalidades

- [ ] #1394
    - Particionar um dataframe e salvar csvs correspondentes em estrutura de pastas.
    - Input: dataframe, lista de colunas da partição, atalho da pasta para salvar.
    - Observações:
        - Deletar as colunas das partições.
        - Salvar os csvs com o mesmo nome da tabela.

- [ ] #1395
    - Quebrar arquivo grande em arquivos menores baseado em colunas e salvar arquivos numa pasta.
    - Input: atalho para arquivo csv, lista de colunas, tamanho de bloco de linhas a ser processadas por vez.

- [ ] #1396
    - Ler a tabela-dicionário associada à tabela e fazer o JOIN para gerar um dataframe com labels.
    - Input: dataframe, dicionário (atalho ou table_id no BQ), lista do colunas (se quiser só um subconjunto de colunas).

**Comment by mavalentim** [comment]
Algumas que eu tava pensando 

Usando nossos dicionarios:
dictionary() - para abrir os dicionarios na sessao

Auxiliares mesmo, sem necessariamente usar nossos dados:
converte_moeda() - para converter valores de moedas brasileiras (i.e. cruzado para real)
id_cid10() - identifica e aglomera cid10 - gera dummy para dengue/para malária (essa pode usar no fundo o dicionario)
inflaciona() - inflacionar um valor para até dado ano

**Comment by lucascr91** [comment]
Issue foi dividida em três issues separadas: #1395 , #1396 e #1397
