### ISSUE TITLE
[infra] Storage Download em batch

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/mais#388]
Fazer o download rapidão

**Comment by Hellcassius** [comment]
Estou tentando implementar o batch(), porém o que acontece é, ele aparentemente faz o download ok, parece mais rápido, porém a cada execução ele dá um erro de `No requests deferred`.
Isso acontece mesmo fazendo a etapa de criar todos os diretórios e replicar a hierarquia da Cloud
