### ISSUE TITLE
Investigar se temos log de queries q involvam nossas tabelas

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/mais#40]
Aparentemente conseguimos saber o número de consultas por tabela. O logger não retorna a query para consultas externas.

**Comment by fernandascovino** [comment]
@JoaoCarabetta isso não ta no analytics já? pode fechar? 🙃

**Comment by rdahis** [comment]
Concluímos isso né? Vou fechar e qualquer coisa o @JoaoCarabetta abre.
