### ISSUE TITLE
[infra] "unused argument (file = path)" no R

### ISSUE THREAD

**Issue by mariana-carvalho** [basedosdados/mais#411]
Tentei rodar o comando `download` no pacote no R mas tive um erro com o `path`. A query é a abaixo, e o comando `write.csv` roda normalmente com o mesmo `path` utilizado.

`query = "SELECT * FROM basedosdados.mundo_onu_adh.municipios"`

<img width="937" alt="Screen Shot 2021-05-01 at 11 58 28 AM" src="https://user-images.githubusercontent.com/32002982/116792397-2a269800-aa75-11eb-9b30-151688da7353.png">

**Comment by pedrocastroo** [comment]
Qual a versão do `readr`? Se for <1.4.0 atualiza. `readr` v1.4.0 alterou os argumento das funções `write_*`, agora é `file`.

https://github.com/tidyverse/readr/releases/tag/v1.4.0

**Comment by pedrocava** [comment]
@mariana-carvalho acredito que o fix sugerido pelo @pedrocastroo funcione. Caso não resolva, continua documentando aqui por favor?
