### ISSUE TITLE
[dados] Problema nos dados da PAM.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#413]
**Descrição**
Ao fazer algumas checagens cruzadas dos nossos dados com os do SIDRA, deu várias inconsistências. Fotos abaixo para reprodução. Reportado pela @amandaajr.

BD:
![WhatsApp Image 2021-05-02 at 13 30 44](https://user-images.githubusercontent.com/6617207/116830443-e1e3a480-ab5e-11eb-8935-b982f9951cd2.jpeg)

SIDRA:
![WhatsApp Image 2021-05-02 at 13 31 49](https://user-images.githubusercontent.com/6617207/116830448-ec9e3980-ab5e-11eb-83e7-8aa45ead17ed.jpeg)
![WhatsApp Image 2021-05-02 at 13 31 13](https://user-images.githubusercontent.com/6617207/116830449-ed36d000-ab5e-11eb-9150-c409fa7b4568.jpeg)

Questões identificadas:
* Muitos valores nulos na BD.
* Variáveis de proporção as vezes de 0-1, e as vezes de 0-100.
* Número de observações não batem com o SIDRA.

**Comment by rdahis** [comment]
Exemplo de query:

```
SELECT * FROM `basedosdados.br_ibge_pam.municipio_lavouras_temporarias`
WHERE ano = 2018 AND id_municipio = 1100015 AND produto = "Amendoim (em casca)"
```

Era para retornar não-vazio para área plantada.

Tá com cara que é aquela coisa de ordem de colunas. E talvez algum erro no código de limpeza.

**Comment by mavalentim** [comment]
Já subi a nova base de temporárias no dev, vou mudar agora a base de permanentes e abrir um PR para consertar!

**Comment by fernandascovino** [comment]
Se quiserem testar para validação também, essas queries deveriam retornar 0:

```
SELECT COUNT(*) FROM `basedosdados.br_ibge_pam.municipio_lavouras_permanentes` 
WHERE prop_area_plantada IS NOT NULL AND area_plantada IS NULL;

SELECT COUNT(*) FROM `basedosdados.br_ibge_pam.municipio_lavouras_permanentes` 
WHERE prop_area_colhida IS NOT NULL AND area_colhida IS NULL;

SELECT COUNT(*) FROM `basedosdados.br_ibge_pam.municipio_lavouras_temporarias` 
WHERE prop_area_plantada IS NOT NULL AND area_plantada IS NULL;

SELECT COUNT(*) FROM `basedosdados.br_ibge_pam.municipio_lavouras_temporarias` 
WHERE prop_area_colhida IS NOT NULL AND area_colhida IS NULL;
```

**Comment by amandaajr** [comment]
> Já subi a nova base de temporárias no dev, vou mudar agora a base de permanentes e abrir um PR para consertar!

testei aqui e não funcionou não :(
usei esse query abaixo. Link para gerar a tabela no sidra [aqui](https://sidra.ibge.gov.br/tabela/1612) 

SELECT * FROM `basedosdados.br_ibge_pam.municipio_lavouras_temporarias`
WHERE ano = 2018 AND id_municipio = 1100015 AND produto = "Amendoim (em casca)"

**Comment by mavalentim** [comment]
> > Já subi a nova base de temporárias no dev, vou mudar agora a base de permanentes e abrir um PR para consertar!
> 
> testei aqui e não funcionou não :(
> usei esse query abaixo. Link para gerar a tabela no sidra [aqui](https://sidra.ibge.gov.br/tabela/1612)
> 
> SELECT * FROM `basedosdados.br_ibge_pam.municipio_lavouras_temporarias`
> WHERE ano = 2018 AND id_municipio = 1100015 AND produto = "Amendoim (em casca)"

Oi amanda! Eu e ricardo tinhamos falado de ja adaptar a tabela à nova arquitetura da Base dos Dados e por isso ela ainda não tá disponível para pessoas de fora da bd (não está em produção) mas eu já to acabando as mudanças, quando tiver pronta eu te dou um toque por aqui, até por que se funcionar (se deus quiser) fechamos o issue!! Qualquer duvida pode me mandar mensagem no discord, no twitter ou um email !

**Comment by mavalentim** [comment]
> Oi @mavalentim! Vc tem alguma previsão de qnd pretende subir a tabela nesse novo formato da BD? Sem pressão mas só pra eu saber se espero ou se vou de guerreira sola aqui pra pegar esses dados rsrs

Já linkei o PR que corrige! Perdão pela demora amanda e obrigado por achar os erros!

**Comment by rdahis** [comment]
@amandaajr e @fernandascovino publicamos as tabelas refeitas! Se acharem qualquer outro problema avisem.
