### ISSUE TITLE
[infra] Função download no R ter as opções do write.csv.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#420]
Gostaria de poder fazer o download com, por exemplo, `na.rm = TRUE`.

**Comment by rdahis** [comment]
Isso! Tirando as aspas só.

```
3,asd,NA,4 # atual
3,asd,,4   # desejado
```

**Comment by rdahis** [comment]
Isso tá rolando já @pedrocava? #nuncatepedinada

**Comment by pedrocava** [comment]
não, vou tentar implementar agora na versão de dev, no CRAN vai demorar um pouco ainda
