### ISSUE TITLE
[infra] Ler arquitetura e preencher o `table_config.yaml` e `publish.sql` automaticamente.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#427]
Input: tabela de arquitetura
    * No Google Drive (com ID próprio, nosso interno ou de colaboradores externos); ou
    * Arquivo CSV

Ter validações:
* Nomes de colunas
* Valores
    * Tipos sempre em `STRING`, `INT64`, `FLOAT64`, `DATE`, `TIME`, geo.
    * Colunas de diretório no formato `dataset_id.table_id:coluna`
    * Unidades de medida no formato ISO-8601 ou nossos extras (`ano`, `dia`, `R$`, etc)

Sugestão de comando no CLI: `basedosdados columns complete`.

**Comment by rdahis** [comment]
@d116626 podemos fechar esse issue?!

**Comment by d116626** [comment]
sim!
