### ISSUE TITLE
[dados] <Erro no nome do dataset id no site >

### ISSUE THREAD

**Issue by douglacardoso** [basedosdados/mais#428]
**Descrição**
Não é exatamente um bug, apenas um erro de digitação no site. O dataset é o Segurança no Estado de São Paulo.

**Capturas de tela**
![image](https://user-images.githubusercontent.com/63059291/118058590-e5e4a300-b364-11eb-96bf-721d9fd88c11.png)

O nome colocado está como 'br_sp_ssp_seguranca', porém na lista de datasets no Python, por exemplo, o dataset id na verdade é 'br_sp_gov_ssp ':
![image](https://user-images.githubusercontent.com/63059291/118058663-14fb1480-b365-11eb-907a-3f254cf9c55a.png)

**Comment by fernandascovino** [comment]
Obrigada, Douglas! @rdahis isso é uma questão para mudar no CKAN, retirar o `seguranca` do nome do conjunto para não ter discrepância: https://basedosdados.org/dataset/br-sp-ssp-seguranca 

Quando puder depois modificar lá ;)

**Comment by rdahis** [comment]
Resolvido! Obrigado @douglacardoso.
