### ISSUE TITLE
[dados] br_bd_diretorios_brasil.municipio

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/mais#429]
O município Augusto Severo (RN) voltou a se chamar Campo Grande (RN).

**Comment by rdahis** [comment]
Gosto do nosso detalhismo :-D

**Comment by crislanealves** [comment]
Então, vamos anotar outra:
Trocar ``Eldorado dos Carajás (PA)`` por ``Eldorado do Carajás``.

Essa é mais robusta kkkkkk

**Comment by gustavoairestiago** [comment]
Trocar Januário Cicco (RN) por Boa Saúde (RN)

**Comment by gustavoairestiago** [comment]
Alterar coluna regiao para nome_regiao
