### ISSUE TITLE
[infra] R: baixar colunas integer64 já como int

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#449]
Atualmente colunas vindo do BigQuery saem com tipo `integer64`. Aí na hora de exportar para outros formatos (exemplo Stata), não sei exatamente porque, os valores saem todos zuados.

Testei rodar essa query (`SELECT * FROM basedosdados.br_ibge_pam.municipio_lavouras_permanentes`) e converter para `dta` com o `foreign::write.dta()`.

Dá para já converter automaticamente todos os `integer64` para `int`?

**Comment by pedrocava** [comment]
Dá sim, mudança tranquila de implementar.

**Comment by pedrocava** [comment]
por enquanto o que tu precisa fazer é:

```
resultado_da_query %>%
mutate(across(where(bit64::is.integer64), as.integer)) %>%
write.data(...)
```

**Comment by rdahis** [comment]
Boa. Ia sugerir isso aqui, que funciona também:

```
w <- which( sapply( df, class ) == 'integer64' )
df[w] <- lapply( df[w], function(x) as.integer(as.character(x)) )
```

**Comment by pedrocava** [comment]
![assim das ideias](https://user-images.githubusercontent.com/25695874/118739346-29498080-b841-11eb-8b62-fd14296e75e8.png)

**Comment by rdahis** [comment]
Ainda não temos isso gente?

**Comment by pedrocava** [comment]
Não, converter cria perda de dados por integer overflow. O que exatamente você precisa fazer que não aceita 64bits?

**Comment by rdahis** [comment]
Quando eu exporto pra csv ele exporta qualquer coluna `INT64` totalmente errada. Não acho que o usuário final tem que se preocupar com isso de converter para `INT`. Deveria funcionar automaticamente.
