### ISSUE TITLE
[infra] Criar suporte para arquivos geojson

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#457]
Para arquivos espaciais, seria bom ter suporte para `geojson`. Hoje parece que temos suporte para `wkt`, mas pelo o que li existe perda de informação convertendo shapefiles para wkt.

**Comment by JoaoCarabetta** [comment]
Para esclarecer, 

shapefiles != geojson != wkt

são formatos diferentes.

Podemos dizer que a info do wkt está contida no geojson, mas contém o essencial, que é o formato da sua geometria. O BigQuery não tem suporte para geojson, mas tem suporte nativo para WKT. 

Não faz muito sentido adicionar suporte para geojson no basedosdados dado que já existem vários outros métodos para fazer isso, `geopandas` por exemplo. Adicionar uma tranformação automática para o basedosdados seria como implementar o pandas para converter um arquivo de json em csv. Isso deve ser feito na etapa de tratamento dos dados.

**Comment by rdahis** [comment]
O BigQuery tem suporte pra geojson também. Achei que seria uma forma de perder menos informação, ao invés de subir WKT.

**Comment by JoaoCarabetta** [comment]
Olha só, tem mesmo. Mas é uma estrutura diferente de CSV. O que daria um trabalho considerável. Acho que não perdemos muita informação com o wkt. Só metadados sobre o objeto que podemos adicionar na nossa estrutura de metadados.
