### ISSUE TITLE
[dados-revisao] datasets e inconsistencias

### ISSUE THREAD

**Issue by aspeddro** [basedosdados/mais#461]
O dataset `br_abrinq_oca` está sem descrição.

```python
>>> basedosdados.list_datasets(filter_by='br_abrinq_oca', with_description=True)

dataset_id:
	br_abrinq_oca
description:
	<descrição>
-----------------------------------------------------------------------------------------------

>>>
```

**Comment by pedrocastroo** [comment]
Outros sem descrição:

`br_camara_dados_abertos`
`br_inep_sinopse_estatistica_educacao_basica`
`br_mc_indicadores`
`br_mobilidados_indicadores`
`br_observatorio_crianca_indicadores`
`br_ponte_indicadores`

```sh
basedosdados list datasets --with_description=True | grep --color -E "<descrição>|$"
```

**Comment by d116626** [comment]
Tabela criada pela @hevsouza para mapear inconsistências 

https://docs.google.com/spreadsheets/d/1i7DZIdIJ3vAxUYOeWxxfAbnMQWJ1ZTUMucME7k8rf8w/edit#gid=0

**Comment by fernandascovino** [comment]
pode fechar esse issue @rdahis @d116626 ?
