### ISSUE TITLE
[dados] Adicionar coluna com latitude e longitude nas tabelas do diretório

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/mais#474]
Não seria interessante se as tabelas do diretório também viessem com uma coluna com o shape do objeto.

Por exemplo, a tabela município pode vir com o shape do municipio.

É só pegar os shapes do geobr.

**Comment by rdahis** [comment]
Acho ótimo. Vou botar na agenda aqui.

**Comment by gustavoalcantara** [comment]
galera, need some help aqui. Escrevi lá em #dúvidas no discord
