### ISSUE TITLE
[dados] br_inep_censo_escolar.dicionario

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#476]
Faltou criar a tabela `dicionario` para a base `br_inep_censo_escolar`.

**Comment by mavalentim** [comment]
eu tiro ela do drive (https://docs.google.com/spreadsheets/d/12sVMJ_hQiO2f2ymb4eFeYLofpnOfuYaqOjhNE1H8U0M/edit#gid=0)  abro um PR para ela no br_bd_diretorios?

**Comment by d116626** [comment]
> @rdahis
> eu tiro ela do drive (https://docs.google.com/spreadsheets/d/12sVMJ_hQiO2f2ymb4eFeYLofpnOfuYaqOjhNE1H8U0M/edit#gid=0) abro um PR para ela no br_bd_diretorios?

@mavalentim esse tipo de dicionarizo fica dentro do dataset, seria uma nova tabela com `dataset_id` = `br_inep_censo_escolar` e `table_id`=`dicionario`

**Comment by mavalentim** [comment]
https://github.com/basedosdados/mais/pull/485

**Comment by mavalentim** [comment]
Resolvido com o PR citado aqui dentro
