### ISSUE TITLE
[dados] br_rj_rio_de_janeiro_ipp_ips

### ISSUE THREAD

**Issue by aspeddro** [basedosdados/mais#481]
**Descrição do dataset**

Indice de Progresso Social do Rio de Janeiro

Já está na [tabela de prioridades](https://docs.google.com/spreadsheets/d/1jnmmG4V6Ugh_-lhVSMIVu_EaL05y1dX9Y0YW8G8e_Wo/edit?usp=sharing)? Sim

Dataset_id: `br_rj_rio_de_janeiro_ipp_ips`

Table_id: `dimensoes_componentes`
Table_id: `indicadores`

Fonte de dados: https://www.data.rio/documents/PCRJ::base-de-dados-do-%C3%ADndice-de-progresso-social-ips-por-regi%C3%B5es-administrativas-ra-munic%C3%ADpio-do-rio-de-janeiro-2016-2018-2020/about

Anos: 2016, 2018, 2020

**Como você pode contribuir?**
Limpeza e disponibilização

**Comment by rdahis** [comment]
O cara tá on fire!
