### ISSUE TITLE
[dados] br_dieese_cesta_basica

### ISSUE THREAD

**Issue by areias** [basedosdados/mais#482]
**Descrição do dataset**

Já está na [tabela de prioridades](https://docs.google.com/spreadsheets/d/1jnmmG4V6Ugh_-lhVSMIVu_EaL05y1dX9Y0YW8G8e_Wo/edit?usp=sharing)? Sim

Dataset_id: `br_dieese_cesta_basica`

Table_id: `valor`

Fonte de dados: https://www.dieese.org.br/cesta/

Anos: de 1959 até 2021 (depende da cidade)

**Como você pode contribuir?**

Vou pegar as duas séries (gasto mensal e tempo de trabalho) para todas as cidades e anos disponiveis e escrever código que baixe automaticamente.

**Comment by rdahis** [comment]
Alow @areias como está aqui? Precisa de ajuda?

**Comment by laura-l-amaral** [comment]
Fechando as 
issue
