### ISSUE TITLE
[infra]  upload de auxiliary_files e architecture para o storage

### ISSUE THREAD

**Issue by d116626** [basedosdados/mais#496]
Requisição de feature do @rdahis para @JoaoCarabetta e @d116626.

Queria que os comandos abaixo funcionassem:

`basedosdados dataset create [DATASET_ID] --raw_files_path '/[DATASET_ID]/input' --auxiliary_files_path '/[DATASET_ID]/extra/auxiliary_files'`

`basedosdados table create [DATASET_ID] [TABLE_ID] --data_path '/[DATASET_ID]/output/[TABLE_ID]' --architecture_path '/[DATASET_ID]/extra/architecture/[TABLE_ID]'`

E depois o `table approve` já copiar para o Storage de produção os arquivos `raw`, `auxiliary_files`, `architecture`.

**Comment by rdahis** [comment]
Issue mencionado na documentação no PR #617 para incentivar colaboração externa.
