### ISSUE TITLE
Dados do Caged indisponíveis no BigQuery apesar de site indicar existência

### ISSUE THREAD

**Issue by gabubell** [basedosdados/mais#505]
**Descrição**
O front aponta a existência da base de dados do Caged para acesso via BigQuery e até aponta qual a tabela. Porém ao clicar no link o mesmo é inexistente. Também não encontrei a tabela procurando diretamente no BigQuery. Por haver indicação de que a tabela já possui acesso via query, creio ser um bug

**Reproduzir**
Passos para reproduzir o comportamento:
1. Vá para https://basedosdados.org/dataset/br-me-caged
2. Clique em 'Explorar dados' depois em 'Consultar no Big Query'
3. Veja o erro:

"Access Denied: Table basedosdados:br_me_caged.microdados_antigos: Permission bigquery.tables.get denied on table basedosdados:br_me_caged.microdados_antigos (or it may not exist)."

**Comportamento esperado**
Esperava encontrar a tabela para acesso via query

**Desktop (preencha as seguintes informações):**
  - SO: [Windows 10]
  - Navegador [brave]
  - Versão [por exemplo 22]

**Smartphone (preencha as seguintes informações):**
  - Dispositivo: [por exemplo iPhone6]
  - SO: [por exemplo iOS8.1]
  - Navegador [por exemplo navegador de ações, safari]
  - Versão 1.25.73

**Comment by JoaoCarabetta** [comment]
@gabubell veja se funciona agora

**Comment by gabubell** [comment]
Funcionando!
Obrigado por todo o trabalho seu e do time!
