### ISSUE TITLE
[dados] br_depen_sisdepen

### ISSUE THREAD

**Issue by rfdornelles** [basedosdados/mais#514]
**Descrição do dataset**

Base de dados contendo as respostas dadas por todas as unidades prisionais do país ao formulário SISDEPEN do Departamento Penitenciário Nacional. Nela há informações sobre características do estabelecimento prisional, quantidade de pessoas presas, dados sobre gênero, raça, idade, nacionalidade, etc dessa população. Também, há informações sobre as incidências penais ("crimes cometidos"), informações sobre disponibilidade dos serviços assistenciais que a Lei de Execuções Penais impõe, etc.

Já está na [tabela de prioridades](https://docs.google.com/spreadsheets/d/1jnmmG4V6Ugh_-lhVSMIVu_EaL05y1dX9Y0YW8G8e_Wo/edit?usp=sharing)? <Não>

Dataset_id: `br_depen_sisdepen´ 

Table_id (1 ou mais):  Sugiro a divisão por temas e eventualmente a divisão por edição da pesquisa. Algo como: `<ano-edição>_dados`, `geral_estabelecimento´, `geral_populacao_prisional´, `geral_perfil_social`

Fonte de dados: https://www.gov.br/depen/pt-br/sisdepen/mais-informacoes/bases-de-dados

Anos: de 2014 até 2020-junho.

**Como você pode contribuir?**
Criei como trabalho para um curso que realizei um pacote com a parte inicial da limpeza, separando em 4 blocos que entendi mais importantes. O repositório está disponível aqui: https://github.com/rfdornelles/penitenciaR/

**Comment by rdahis** [comment]
Excelente, bora subir! Já conhece o fluxo de subida? Pode ir fazendo no teu bucket no GCP e abrir um PR.

**Comment by laura-l-amaral** [comment]
Fechando as issues que a princípio não vamos retomar tão cedo (issue reescrita em #1473)
