### ISSUE TITLE
[infra] make list_datasets() and list_dataset_tables() return a vector 

### ISSUE THREAD

**Issue by mavalentim** [basedosdados/mais#516]
Hoje em dia se eu uso o `list_datasets()` ou o `list_dataset_tables()` ele retorna um Non Type, o que dificulta usar esse output nas outras funcoes que realmente baixam as tabelas, por exemplo. 

Sugestão: a saida ser um vetor com cada elemento uma string que equivale ao nome das tabelas ou dos datasets.
Sugestão2: criar mais uma que da o nome de tudo que tá na BD (algo no formato dataset.tabela)

Essas modificações facilitam a identificação em massa de problemas nas tabelas, tal qual o `id_municipio` estar como INT

**Comment by vncsna** [comment]
@d116626 o que acha de alterar a saída dessas funções? Talvez adicionar um argumento `verbose` a assinatura?

**Comment by d116626** [comment]
@vncsna, acho uma boa.  Depois dos metadados vai ter uma rodada de mudanças na API ai podemos incluir essa modificação,

**Comment by vncsna** [comment]
Vou fechar essa issue, uma vez que esta englobada na issue #522
