### ISSUE TITLE
[infra] Traceback mais completo para bd.download()

### ISSUE THREAD

**Issue by Hellcassius** [basedosdados/mais#519]
**Descrição**
Em bd.download.read_sql(), o handling de erros em geral retorna todos os erros como de erros de autenticação. Ele levanta um BaseDosDadosException() com a mensagem:
` We are not sure which Google Cloud project should be billed.
   First, you should make sure that you have a Google Cloud project.[...]`

**Reproduzir**
Passos para reproduzir o comportamento:
1. Usar bd.download() numa tabela que não existe, i.e. `bd.download(savepath='non_existant.csv',dataset_id='br_rj_does_not_exist',table_id='does_not_exist')`

**Comportamento esperado**
Um traceback mais completo sobre a causa do erro, o que implica em alterar o try catch que acontecesse hoje

**Capturas de tela**
![Screenshot from 2021-06-29 14-41-09](https://user-images.githubusercontent.com/77297729/123843275-1c13bd00-d8e8-11eb-8dca-90208792ebc5.png)

**Desktop (preencha as seguintes informações):**
  - SO: Ubuntu 20.04

**Comment by JoaoCarabetta** [comment]
Casos possíveis:
1. Usuário não fez a configuração corretamente
2. Erro na query do BQ
3. Erro de associação do billing/projeto

preferir erro nativo do `pandas-gbq`

**Comment by rdahis** [comment]
Parece já ter sido fechado pelo #626.
