### ISSUE TITLE
[infra] Desafio Desenvolvedor Junior - 07/2021

### ISSUE THREAD

**Issue by d116626** [basedosdados/mais#522]
### Contexto
Uma das funcionalidades que a API em python do `basedosdados` fornece é a consulta dos `datasets` e das `tabelas` que estão no datalake sem utilizar o console do BigQuery. Essa consulta é realizada utilizando as funções `list_datasets()` e `list_dataset_tables()`.

**Código para consulta**

```python
#importa pacote do basedosdados
import basedosdados as bd

#lista os datasets
bd.list_datasets()

#lista as tabelas de um determinado dataset
bd.list_dataset_tables('br_sp_alesp')

```
### Issue

Hoje as funções `list_datasets()` e `list_dataset_tables()` não possuem retorno, elas apenas fazem um `print`, dificultando o uso das informações para automatizações. Para resolvermos esse problema é necessário algumas modificações na API.

### Guide

O que é necessário para resolver o problema?

1. Fazer um fork do repositório do [basedosdados/mais](https://github.com/basedosdados/mais)
2. Executar os comando `pip install -r requirements-dev.txt` e `python setup.py develop` dentro da pasta `mais/python-package`
3. Localizar as funções `list_datasets()` e `list_dataset_tables()` no arquivo [download.py](https://github.com/basedosdados/mais/blob/master/python-package/basedosdados/download/download.py) em `mais/python-package/basedosdados/download/download.py`
4. Editar a função `list_datasets()` adicionando um novo parâmetro `return_data`, que faça com que a função retorne  uma lista de datasets quando `return_data = True`
5. Editar a função `list_dataset_tables()` adicionando um novo parâmetro `return_data`, que faça com que a função retorne  uma lista dos tabelas quando `return_data = True`
6. Atualzar docstring da função indicando a nova funcionalidade
7. Abrir um  Pull Request no seu próprio fork e enviar o link por email

**Desafio opcional**. Esse item será considerado um diferencial;

8. Atualizar os testes destas funções para receber uma nova saída. Todos os testes estão em `mais/python-package/tests/test_download.py` e utilizam o framework [pytest](https://docs.pytest.org/en/6.2.x/). Tenha certeza que todos os testes estão passando!

----

**Divirtam-se**!

**Comment by JoaoCarabetta** [comment]
Implementar output_type

bd.list_datasets(
    query_project_id='basedosdados',
    output_type=['print', 'list'],     <--
    filter_by=None,
    with_description=False,
    from_file=False,
)
