### ISSUE TITLE
[infra] `id_municipio` está tipado de forma diferente em algumas tabelas

### ISSUE THREAD

**Issue by vmussa** [basedosdados/mais#536]
**Descrição**
Lendo a [documentação sobre como acessar os dados localmente](https://basedosdados.github.io/mais/access_data_local/), fui testar a query de exemplo e vi que estava quebrada: o `JOIN` não funcionava porque o `id_municipio` da tabela `basedosdados:br_ibge_populacao.municipio` é uma `STRING` enquanto que o da tabela `basedosdados:br_ibge_pib.municipios` é um `INTEGER` - não sei se estou perdendo algo de vista. Propus uma solução apenas para a query da documentação em #535, mas me parece que seria interessante caso o `id_municipio` fosse idêntico quanto ao tipo de dado em todas as tabelas. Isso é possível?

**Reproduzir**
Passos para reproduzir o comportamento:
1. Vá para o projeto `basedosdados` no BigQuery: https://console.cloud.google.com/bigquery?p=basedosdados&page=project
2. Crie uma nova consulta com o seguinte conteúdo:
```sql
SELECT 
    pib.id_municipio ,
    pop.ano, 
    pib.PIB / pop.populacao * 1000 as pib_per_capita
FROM `basedosdados.br_ibge_pib.municipios` as pib
INNER JOIN `basedosdados.br_ibge_populacao.municipio` as pop
ON pib.id_municipio = pop.id_municipio AND pib.ano = pop.ano
```
3. O seguinte erro aparecerá numa caixa de diálogo: `No matching signature for operator = for argument types: INT64, STRING. Supported signature: ANY = ANY at [7:4]`

4. Verifique a diferença do tipo de dado de cada coluna `id_municipio` em cada uma das duas tabelas.

**Comportamento esperado**
Esperava-se que o `JOIN` funcionasse sem precisar converter os tipos do `id_municipio`.

**Desktop (preencha as seguintes informações):**
  - SO: Ubuntu 20.04
  - Google Chrome 91.0.4472.114 (Official Build) (64-bit)

**Comment by JoaoCarabetta** [comment]
Opa @vmussa, a gente tá refazendo a tipagem dos ids já. o @mavalentim que está tocando isso.

**Comment by mavalentim** [comment]
Oi @vmussa ! Que nem o @JoaoCarabetta falou, terminei ontem um código que mapeia todas as bases onde `id_municipio` está com tipagem equivocada. Vou abrir um PR para anexar esse código ao nosso repositório, depois coloco o link dele aqui :)

**Comment by fernandascovino** [comment]
me marcar por favor @mavalentim para corrigir na documentação depois

**Comment by mavalentim** [comment]
Oi gente! Aqui está o código que usei para mapear. Ainda estou melhorando ele - é uma versão bem inicial. Ele cria tabelas que mostram as bases que tem erro no `id_municipio`, erro no `id_escola` e erro ao ter `estado_abrev`.

PR do código: https://github.com/basedosdados/mais/pull/542

**Comment by rdahis** [comment]
Solução pra esse issue será mudar toda a documentação de tabela `br_ibge_pib.municipios` para `br_ibge_pib.municipio`.

**Comment by fernandascovino** [comment]
@vmussa corrigido na documentação pelo #547 , as demais tabelas estão sendo tratadas conforme estamos documentando na planilha: https://docs.google.com/spreadsheets/d/1i7DZIdIJ3vAxUYOeWxxfAbnMQWJ1ZTUMucME7k8rf8w/edit#gid=0

**Comment by mavalentim** [comment]
@vmussa só para complementar a fernanda: a sheet "mapeando os erros: tudo" é gerada automaticamente e mostra quais `id_municipio` e `id_escola` estão tipados erroneamente! ela também mostra quais tabelas estão com `estado_abrev`ao invés de `sigla_uf`. Em breve concluiremos a revisão, como dá pra ver pela tabela :)
