### ISSUE TITLE
[infra] Data check de chaves únicas dar erro diferente quando o campo `primary_keys` estiver vazio.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#550]
Hoje ele dá um erro como se o campo `primary_keys` não identificasse linhas unicamente. Mas se esse campo está vazio, faz mais sentido mudar o erro.

**Comment by d116626** [comment]
Quando vc diz vazio é vazio mesmo? 
Ou tá assim?
```yaml
primary_keys:
    - <primeira coluna>
    - <segunda coluna>

```

**Comment by vncsna** [comment]
Vou dar uma olhada daqui 1hr

**Comment by rdahis** [comment]
Não sei se tá vazio ou com `<>`. Mas o check deveria tratar o `<>` como vazio né.

**Comment by vncsna** [comment]
@rdahis seria possível passar a tabela/query que esta dando erro?

**Comment by vncsna** [comment]
@d116626 acha que precisamos fazer algo aqui ou da pra fechar a issue? O caso se `<>` acho que deveria ser tratado como um não nada.

**Comment by d116626** [comment]
> @d116626 acha que precisamos fazer algo aqui ou da pra fechar a issue? O caso se `<>` acho que deveria ser tratado como um não nada.

se o caso do `<>` já foi tratado, faz o link do PR e pode fechar
