### ISSUE TITLE
[dados] br_inep_enem

### ISSUE THREAD

**Issue by eduardobonet** [basedosdados/mais#596]
**Descrição do dataset**

1. A base já está na [tabela de prioridades](https://docs.google.com/spreadsheets/d/1jnmmG4V6Ugh_-lhVSMIVu_EaL05y1dX9Y0YW8G8e_Wo/edit?usp=sharing)? 

Sim

2. Qual o nome do conjunto?  br_inep_enem

3. Qual o nome da(s) tabela(s)? Várias tabelas diferentes

4. Fonte de dados: https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/enem

5. Cobertura temporal: 1998 a 2019, novos dados lançados anualmente

**Como você pode contribuir?**

Download e pipeline de transformação dos dados, particionar os dados para acelerar queries.

**Comment by eduardobonet** [comment]
[Na documentação](https://basedosdados.github.io/mais/colab_data/#2-baixar-nossa-pasta-template-para-dados), fala-se para adicionar os csv's diretamente no repositório. Mas cada um dos arquivos podem ter mais de 4GB de tamanho, não é muito boa ideia adiciona-los diretamente. Mesmo usando o formato zip, cada um tem uns 500mb. Algumas opções: 

1) git-lfs
2) adicionar o download como parte do pipeline
3) salvar os dados em um S3 da vida

**Comment by rdahis** [comment]
Opa @eduardobonet! Excelente que quer subir os dados do Enem.

Sobre os csvs, você não vai subir eles no repositório no Github não. Os arquivos pesados vão direto para o GCP (passo 7). A pasta local `br_inep_enem` é onde você vai fazer a limpeza dos dados. Aqui no Github você sobe só os arquivos de metadados.

**Comment by eduardobonet** [comment]
Algumas considerações. Cada ano é um dataset separado, com um dicionário diferente, e possivelmente definições diferentes. Sendo boa prática disponibilizar os dados crus, minha inteção é criar uma tabela para cada um dos anos (br_inep_enem.microdados_20XX). Após, adicionar scripts ETL (SQL, Apache Beam ou Spark) para criar um dataset com o conjunto de todos os anos. Isso é recomendando/possível na infra do BD+?

**Comment by rdahis** [comment]
Pode ser sim. Mas nossa prática tem sido de já compatibilizar o máximo de anos possível e disponibilizar uma tabela só. Nesse caso se chamaria algo como `br_inep_enem.microdados_20XX_2019` dados que voltaríamos para trás.

A @hevsouza fez algo parecido para o Saeb e @mavalentim fez para o Censo Escolar.

@eduardobonet chega na nossa reunião de dados hoje (segunda) 18h que discutimos a questão da tabela de arquitetura, ETL, etc.

**Comment by eduardobonet** [comment]
> br_inep_enem.microdados_20XX_2019 

Todo ano são liberados microdados novos, que podem ou não seguir as mesma colunas ou formato. Isso faria com que o numero de colunas (que já é grande) explodisse, assim como a necessidade de recriar o dataset com um novo nome, o que quebraria a compatibilidade com usuários existentes.

**Comment by eduardobonet** [comment]
> reunião de dados hoje (segunda) 18h

Posso tentar, mas estou 5h a frente e fica num horário difícil.

**Comment by rdahis** [comment]
> > br_inep_enem.microdados_20XX_2019
> 
> Todo ano são liberados microdados novos, que podem ou não seguir as mesma colunas ou formato. Isso faria com que o numero de colunas (que já é grande) explodisse, assim como a necessidade de recriar o dataset com um novo nome, o que quebraria a compatibilidade com usuários existentes.

Verdade bom ponto! Deixaríamos só `br_inep_enem.microdados` para essa tabela compatibilizada e guardaríamos a cobertura temporal nos metadados.

**Comment by rdahis** [comment]
@eduardobonet como tá aqui? Podemos ajudar de algum jeito?

**Comment by lucasnascm** [comment]
**Metadados da base**

1. Descrição: Dados sobre o Exame Nacional do Ensino Médio



2. Qual o nome do conjunto? `br_inep_enem`

3. Qual o nome da(s) tabela(s)? `escola`, `microdados`

4. Fonte original dos dados: 
<[Microdados ENEM](https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/enem)>
<[Microdados por Escola](https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/enem-por-escola)>

5. Cobertura espacial: brasil

6. Cobertura temporal: de 1998 a 2019

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [ ] Baixar a pasta template
- [ ] Preencher as tabelas de arquitetura
- [ ] Escrever código de captura e limpeza de dados.
- [ ] Organizar arquivos auxiliares, se necessário.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by lucasnascm** [comment]
Enem por escola (2005 - 2015)
Tabela de arquitetura: https://docs.google.com/spreadsheets/d/12VL3bsjtpi78VGoX2BKY2N1Cy_vBH6_rS1KtVrrdkWw/edit#gid=0

**Comment by lucasnascm** [comment]
Microdados do ENEM (1998-2019)
Tabela de arquitetura: https://docs.google.com/spreadsheets/d/1zxV1h7i3FfijjC5a_qz0LuN4vahy8m26VcLmBpS4oTg/edit#gid=0

**Comment by crislanealves** [comment]
Retomar depois.
