### ISSUE TITLE
[infra] Criar diretorio para nova base de dados usando CLI em vez de download do Drive

### ISSUE THREAD

**Issue by eduardobonet** [basedosdados/mais#603]
**Sua solicitação de recurso está relacionada a um problema? Por favor descreva.**

Seguindo o guia e contribuição, para criar um novo database é necessário baixar os dados do Google Drive, que adiciona uma ferramenta a mais e outros passos. Porém, o basededados já possui um CLI que poderia ser usado para isso.

**Descreva a solução que você gostaria**

Operação para criar o template através da ferramenta cli que já existe:

```
basedosdados scafold <database_id>
```

Para adicionar uma nova tabela:

```
basedosdados scafold <database_id.table_id>
```

A estrutura da pasta e um exemplo completo da modificações necessárias poderiam ser colocados no proprio repositorio, junto com o template que já existe para inicialização do dataset.

**Descreva alternativas que você considerou**

Subir o zip para o github e usar o link no github em vez do drive: Diminui uma dependência, mas ainda sim requer download, unzip, mover para pasta desejada, renomear, e não é versionado.

**Comment by HenriqueAJNB** [comment]
A proposta via CLI já foi desenvolvida?

**Comment by vncsna** [comment]
A CLI foi deprecada
