### ISSUE TITLE
[infra] adicionar `data-check` depois do `table-approve`

### ISSUE THREAD

**Issue by d116626** [basedosdados/mais#611]
Em alguns casos o `data-ckeck` passa para a tabela em `dev` mas alguns erros podem ocorrer em produção, sugiro colocar um `data-ckeck` após a execução do `table-approve` para pegar esses problemas.

**Comment by vncsna** [comment]
Daí o `billing_project_id` é outro? Qual?

**Comment by d116626** [comment]
> @d116626 daí o `billing_project_id` é outro? Qual?

na verdade o `billing_project_id` pode ser o mesmo mesmo, o que teria que trocar é o `project_id`. Ai as querys que antes estavam apontando pro `basedosdados-dev`apontariam pro `basedosdados`
