### ISSUE TITLE
[dados] inconsistências em `br_bd_diretorios_brasil.escola`

### ISSUE THREAD

**Issue by d116626** [basedosdados/mais#615]
A escola [`Bairro Bom Sucesso`](https://www.escol.as/213328-bairro-bom-sucesso) de São José dos Campos não consta no diretório de escolas da bd

**Comment by d116626** [comment]
[`Bairro Turvo de Baixo`](https://www.escol.as/218904-bairro-turvo-de-baixo)

**Comment by d116626** [comment]
[Bairro Bengala](https://www.qedu.org.br/escola/193937-bairro-bengalar/sobre)

**Comment by d116626** [comment]
[`Cicero de Alvarenga Monsenhor`](https://www.escol.as/222753-cicero-de-alvarenga-monsenhor)

**Comment by d116626** [comment]
Escola repetida

```sql
SELECT * FROM `basedosdados.br_bd_diretorios_brasil.escola`
where id_escola ='35013134'
```

**Comment by d116626** [comment]
Acabei escrevendo a query 🙃 

```sql
with escolas as (
  SELECT 
    id_escola,
    nome_escola,
    sum(1) as count
  FROM `basedosdados.br_bd_diretorios_brasil.escola`
  GROUP BY 1, 2
)

SELECT * 
FROM escolas
WHERE count>1
```

**Comment by d116626** [comment]
Descobri o erro de escolas duplicadas, no [`storage`](https://console.cloud.google.com/storage/browser/basedosdados/staging/br_bd_diretorios_brasil/escola?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=basedosdados-staging&prefix=&forceOnObjectsSortingFiltering=false) tem dos arquivos, um `escola.csv` e outro `diretorio.csv`. Como os dois estão com a mesma data de upload n sei qual deletar. 

@mavalentim preciso de um help pra saber qual o arquivo certo

**Comment by d116626** [comment]
,

**Comment by rdahis** [comment]
@d116626 pode por favor listar as escolas que não encontrou em um novo issue?
