### ISSUE TITLE
[infra] Ter uma tabela de instituições para preenchimento de configs.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#62]
Ideia seria cada instituição ter um ID, e incluirmos informações sobre (nome, website, email, etc). Na hora de criar tabelas, não precisaríamos repetir o preenchimento toda vez.

Será útil para instituições grandes, como IBGE, Ipea, TSE, etc.

**Comment by fernandascovino** [comment]
@rdahis ja temos aqui?

**Comment by rdahis** [comment]
Ainda não mas podemos fechar a issue por enquanto porque não é prioridade. O que acha?

**Comment by fernandascovino** [comment]
pode deixar aqui como backlog, só comentei para recuperar discussões que pdoem ser relevantes :)

**Comment by rdahis** [comment]
Fechando dado que estamos migrando os metadados para o CKAN. Lá eventualmente teremos metadados de organização.
