### ISSUE TITLE
[dados] bug - diretorios_brasil.setor_censitario

### ISSUE THREAD

**Issue by filipemsc** [basedosdados/mais#620]
**Descrição**
Fui tentar fazer uma query simples em `br_bd_diretorios_brasil.setor_censitario e obtive o seguinte erro:

Error while reading table: basedosdados-staging.br_bd_diretorios_brasil_staging.setor_censitario, error message: Incompatible partition schemas. Expected schema ([ano:TYPE_INT64, sigla_uf:TYPE_STRING]) has 2 columns. Observed schema ([]) has 0 columns.  

**Reproduzir**
Passos para reproduzir o comportamento:
1. Rodar a query: SELECT DISTINCT ano FROM `basedosdados.br_bd_diretorios_brasil.setor_censitario`

**Comment by rdahis** [comment]
Consertado, obrigado! Era causado por um arquivo fora da estrutura de partições no Storage após a revisão da @hevsouza.
