### ISSUE TITLE
[dados] br_ms_sinan."violência doméstica"

### ISSUE THREAD

**Issue by filipemsc** [basedosdados/mais#637]
**Descrição do dataset**

1. A base já está na [tabela de prioridades](https://docs.google.com/spreadsheets/d/1jnmmG4V6Ugh_-lhVSMIVu_EaL05y1dX9Y0YW8G8e_Wo/edit?usp=sharing)? Sim

2. Qual o nome do conjunto? `br_ms_sinan`

3. Qual o nome da(s) tabela(s)? violência doméstica

4. Fonte de dados:
- http://www2.datasus.gov.br/DATASUS/index.php?area=0901

5. Cobertura temporal: de 2005-2019

**Como você pode contribuir?**
Pensei em subir a base de violência interpessoal primeiro, depois subir dados de doenças monitoradas pelo SINAN.

**Comment by filipemsc** [comment]
Será que vocês podem dar uma revisada no nome das colunas antes de eu preencher a documentação? @rdahis @lucasnascm @crislanealves 
https://docs.google.com/spreadsheets/d/1_1X1Oqka91mXBK6C7QLAKx8A-2_I-EFaJ5K2Ul_55w0/edit?usp=sharing

**Comment by rdahis** [comment]
Botei vários comentários lá.

**Comment by crislanealves** [comment]
Comentei lá.
