### ISSUE TITLE
Criar padrão de nomeação para tables.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#64]
Precisamos de um padrão para tabelas que se repetem entre níveis de observação.

Sugestão: <nível>_<descrição>

Exemplo: dados de PIB do IBGE para municípios, estados e país. Dentro do dataset `br_economia_IBGE`, as tables poderiam ser `municipio_PIB`, `estado_PIB`, `pais_PIB`?

**Comment by JoaoCarabetta** [comment]
Acho que funciona para casos específicos, mas muitos datasets não teriam a esses níveis, certo?

Pode entrar como uma sugestão no caso de existir níveis.

**Comment by rdahis** [comment]
Resolvemos botar um padrão fixo para datasets e deixar tables mais livre de acordo com o contexto.
