### ISSUE TITLE
[dados] br_ms_cnes

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#643]
**Descrição do dataset**

1. A base já está na [tabela de prioridades](https://docs.google.com/spreadsheets/d/1jnmmG4V6Ugh_-lhVSMIVu_EaL05y1dX9Y0YW8G8e_Wo/edit?usp=sharing)? Sim

2. Qual o nome do conjunto? `br_ms_cnes`

3. Qual o nome da(s) tabela(s)?

- [x] `estabelecimento`
- [x] `profissional`
- [ ] `leito`
- [x] `equipe`
- [ ] `equipamento`
- [ ] `habilitacao`
- [ ] `dados_complementares`
- [ ] `servico_especializado`
- [ ] `regras_contratuais`
- [ ] `gestão_metas`
- [ ] `estabelecimento_ensino`
- [x] `estabelecimento_filantropico`
- [ ] `integra_sus`

4. Fonte original dos dados: http://cnes.datasus.gov.br/pages/downloads/arquivosBaseDados.jsp

5. Cobertura espacial: Brasil

6. Cobertura temporal: de 2005 a 2021

**Tarefas** (seguindo os passos [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template
- [x] Preencher as tabelas de arquitetura
- [x] Escrever código de captura e limpeza de dados.
- [x] Organizar arquivos auxiliares, se necessário.
- [x] Criar tabela dicionário, se necessário.
- [x] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by rdahis** [comment]
Instruções e código já feito pela FioCruz para ETL desses dados: https://bigdata-metadados.icict.fiocruz.br/en/dataset/cadastro-nacional-de-estabelecimentos-de-saude-cnes/resource/8bc4a229-2882-4c55-8fd7-82d290c577f4

**Comment by rdahis** [comment]
Link para tabelas de arquitetura no Drive: https://drive.google.com/drive/folders/15s9DHVjAp_ZmLyeWCvUQAKkoEmNmt3Ep?usp=sharing

**Comment by laura-l-amaral** [comment]
closed by basedosdados/pipelines#420
