### ISSUE TITLE
[infra] bug br_sp_gov_ssp.produtividade_policial

### ISSUE THREAD

**Issue by rfdornelles** [basedosdados/mais#653]
**Descrição**
Ao rodar qualquer query na base de produtividade policial da SSP/SP retorna isso:
Error while reading table: basedosdados-staging.br_sp_gov_ssp_staging.produtividade_policial, error message: Too many values in row starting at position: 527. Found 17 column(s) while expected 16.

**Reproduzir**
Passos para reproduzir o comportamento:
A query, tanto no pacote R quanto direto no Google BQ:
> SELECT *
> FROM basedosdados.br_sp_gov_ssp.produtividade_policial
> LIMIT 100

**Contexto adicional**
Parece que algo semelhante ocorreu também com a tabela de ocorrências do mesmo dataset.

**Comment by d116626** [comment]
Fix in PR #684
