### ISSUE TITLE
[infra] Dados errados em queries pelo R

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#658]
**Descrição**
Tabelas baixadas pela API do R vem errados. A tabela `br_tse_eleicoes.candidatos` vem com a coluna `ano` cheia de zeros e um número de linhas completamente errado.

Screenshot:
![Screen Shot 2021-08-02 at 1 16 26 PM](https://user-images.githubusercontent.com/6617207/127892502-04326fa8-77e5-45c9-8aa3-7e550374132f.png)

**Reproduzir**
No R, rodar:
```
basedosdados::download("SELECT * FROM `basedosdados.br_tse_eleicoes.candidatos`",
                       "~/Downloads/candidatos.csv", page_size = 1000000)
```

**Comportamento esperado**
Deveria baixar a tabela como está no BigQuery. Lá tem 2858297 linhas.

**Comment by JoaoCarabetta** [comment]
Qual a query que você usou?

**Comment by rdahis** [comment]
Acho que resolvi. Tava com pagesize grande demais.

**Comment by JoaoCarabetta** [comment]
@pedrocava esse pagesize grande não pode dar problema no novo release do pacote?

**Comment by pedrocava** [comment]
Na v 0.1.0 temos 100k linhas como padrão. Os testes devolvem dados com sentido. Vale investigar em que condições o page_size corrompe a query, mas acho que esse problema não pega o release atual.

**Comment by rfdornelles** [comment]
Será que tem relação com essa issue do bigrquery https://github.com/r-dbi/bigrquery/issues/412 ? 

Testei aqui com a versão de desenvolvimento e acabou dando o mesmo problema. Ao baixar com o page_size de 1000000 indicado, baixou um .csv de 126 MB e 2,761,492 linhas com ano == 0. Ao baixar sem o parâmetro page_size (ou seja, com o padrão de 100.000), baixou 300.4 MB com 1,970,702 linhas com ano == 0 (esse mesmo comportamento ocorreu com read_sql).

Rodando bdplyr + bd_write_csv retornou um arquivo com 747.3MB e, a principio, nenhuma linha com ano == 0.

**Comment by rdahis** [comment]
Pera, qual é a solução então?

**Comment by pedrocava** [comment]
Baixar com um `page_size` de 100k serve para o que tu precisa. 

Esse bug é do [`bigrquery como o Hadley notou aqui`](https://github.com/r-dbi/bigrquery/issues/412#issuecomment-831560681) e não temos o que resolver. Por segurança vou adicionar uma validação desse parametro no pacote e indicar essa issue que documenta o bug como referência.

**Comment by rdahis** [comment]
Com 100k não resolveu aqui. Rodei:

```
query = "SELECT * FROM `basedosdados.br_tse_eleicoes.candidatos`"
df.candidatos = read_sql(query, page_size = 100000)
table(df.candidatos$ano)
```

E deu isso aqui:
<img width="761" alt="Screen Shot 2021-08-02 at 10 20 31 PM" src="https://user-images.githubusercontent.com/6617207/127942877-e80c83ea-ea9a-4231-98d6-a8d7160bf4d3.png">

**Comment by pedrocava** [comment]
Tenta a solução do Rodrigo, com o pacote de desenvolvimento, que escapa a implementação com problema de paginação em `bq_tables`

**Comment by rdahis** [comment]
Para registro, a solução com o pacote em dev por enquanto:

```
devtools::install_github("basedosdados/mais", subdir = "r-package")
candidatos <- basedosdados::bdplyr("br_tse_eleicoes.candidatos")
basedosdados::bd_write_csv(candidatos, "candidatos.csv")
```

**Comment by rfdornelles** [comment]
Com a mudança do {bigrquery}, fiz alguns testes. Deixar o page_size em branco - que é o recomendado por eles - deu errado. O que funcionou foi:

basedosdados::download("SELECT * FROM `basedosdados.br_tse_eleicoes.candidatos`",
                       path = "candidatos2.csv", 
                       page_size = 10000)

**Comment by pedrocava** [comment]
Isso cria um problemaço para a 0.1.0, que sobe o page_size para 100k por padrão. Acho que vamos ter que manter as queries mais lentas para garantir integridade de dados até resolverem esse bug no {bigrquery}.

**Comment by pedrocava** [comment]
Update sobre a situação: resolvemos esse bug upando a versão mínima requerida do `bigrquery` para 1.4.0 no próxima versão. A solução até lá é atualizar a sua versão local dessa dependência com `install.packages('bigrquery', version = '1.4.0')`
