### ISSUE TITLE
Pasta /code sendo criada na branch master quando rodamos o table create ou publish em outra branch.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#66]
Reparei que quando crio uma nova branch a partir do master e faço o pipeline create-publish nessa branch, é criada uma pasta /code dentro da branch master.

Por exemplo, o CLI criou a pasta `br_economia_IBGE/code` dentro de `master` mesmo comigo editando tudo de dentro da branch `add_municipio_PIB`.

**Comment by JoaoCarabetta** [comment]
Vou testar isso, pq se tu tá numa branch, não tem como adicionar nada no `master`. Só se eu voltar pro master.

**Comment by rdahis** [comment]
Eu sei.. Testa local e me diz. Aqui ainda acontece.

**Comment by rdahis** [comment]
Fechando por enquanto.
