### ISSUE TITLE
[dados] tabelas em produção que não funcionam 

### ISSUE THREAD

**Issue by d116626** [basedosdados/mais#666]
Passei por todas as tabelas em produção e encontrei 3 com problemas

- [ ] br_ms_srag2020 

```sql
SELECT * 
FROM `basedosdados.br_ms_srag2020.microdados` 
LIMIT 1000
```
- [x] br_sp_gov_ssp

```sql
SELECT * 
FROM `basedosdados.br_sp_gov_ssp.ocorrencias_registradas` 
LIMIT 1000
```

- [x] br_sp_gov_ssp

```sql
SELECT * 
FROM `basedosdados.br_sp_gov_ssp.produtividade_policial` 
LIMIT 1000
```

**Comment by d116626** [comment]
Tabelas do `br_sp_gov_ssp`corrigidas no PR #684

**Comment by lucasnascm** [comment]
Podemos fechar essa issue já que `basedosdados.br_ms_srag2020.microdados` não tá mais em prod nem em dev
