### ISSUE TITLE
Arquivos csv de download vindo com casas decimais pra números inteiros.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#67]
Exemplo: baixei o `br_populacao_IBGE.populacao_municipios` e a coluna populacao vem com valores como 31981.0, 83684.0, etc.

**Comment by JoaoCarabetta** [comment]
Acho que isso é problema do pandas. Mas tu acha que isso é algo a ser resolvido?

**Comment by rdahis** [comment]
Não é urgente mas seria bom em algum momento. Porque pode confundir o que é a variável. Ver em .0 pode te fazer achar que há municípios com população, por exemplo, 10000.4, ou algo do tipo.
