### ISSUE TITLE
[dados] Erro na tabela `br_sp_gov_ssp.ocorrencias_registradas`

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#678]
**Descrição**
Erro na query para `br_sp_gov_ssp.ocorrencias_registradas`

**Reproduzir**
Rodar `SELECT * FROM basedosdados.br_sp_gov_ssp.ocorrencias_registradas`

**Comment by d116626** [comment]
Já existe uma issue para esse dataset #666
