### ISSUE TITLE
[dados] `br_bd_diretorios_brasil.ente_publico`

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#679]
**Metadados da base**

1. Descrição: Diretório de entidades públicas da Receita Federal incluindo CNPJ. Dados tratados pelo Ipea.

2. Qual o nome do conjunto? `br_bd_diretorios_brasil`

3. Qual o nome da(s) tabela(s)? `ente_publico`

4. Fonte original dos dados: <link>

5. Cobertura espacial: Brasil

6. Cobertura temporal: atual

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [ ] Baixar a pasta template
- [ ] Preencher as tabelas de arquitetura
- [ ] Escrever código de captura e limpeza de dados.
- [ ] Organizar arquivos auxiliares, se necessário.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by laura-l-amaral** [comment]
Quando for ser feita verificar se é possível unir com #856
