### ISSUE TITLE
[infra] Padrão da função download ser não ter index.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#68]
Agora está baixando coisas com uma primeira coluna sem nome e com valores 0, 1, 2, 3, 4, 5...

**Comment by JoaoCarabetta** [comment]
@Hellcassius pode ver isso? Acho que seria só adicionar `index=False` no `**pandas_kwargs` do `download`

**Comment by fernandascovino** [comment]
ta fechado ja aqui en @Hellcassius ?
