### ISSUE TITLE
[infra] table_description.txt não sendo criado 

### ISSUE THREAD

**Issue by filipemsc** [basedosdados/mais#687]
**Descrição**
Tentei dar um publish, mas tô obtendo um erro dizendo que o table_description.txt não foi criado

**Reproduzir**
(não tá reprodutível, mas fiz isso)
```
import basedosdados as bd
violencia = bd.Table('microdados-violencia', 'br_ms_sinan')
violencia.create('C:/Users/filip/Documents/.projetos-git/br_ms_sinan/output/microdados-violencia',
                if_table_exists='replace',
                if_storage_data_exists='replace', 
                if_table_config_exists='replace')
violencia.update_columns("https://docs.google.com/spreadsheets/d/1_1X1Oqka91mXBK6C7QLAKx8A-2_I-EFaJ5K2Ul_55w0/")
violencia.publish(if_exists = 'replace')
```

**Capturas de tela**
![print-erro](https://user-images.githubusercontent.com/11773789/128779425-85eadd65-4b10-4839-88e6-eda3a8e5247d.png)

**Contexto adicional**
O problema começou a rolar depois que instalei o `basedosdados` em um PC com Linux para rodar a função de update_columns, e daí tive que criar outro staging.json e prod.json no Cloud para este respectivo PC. Depois disso começou a dar esse erro tanto o Linux quanto Windows.

**Comment by filipemsc** [comment]
Aparentemente já teve esse erro antes, vide issue #511

**Comment by d116626** [comment]
Problema identificado, o nome da tabela tinha um `-` ao invés do `_`, era o mesmo problema do issue #511. Vale colocar uma etapa de checagem na grafia do `dataset_id` e do `table_id`.

@JoaoCarabetta @vmussa

**Comment by d116626** [comment]
Resolvido no PR #723
