### ISSUE TITLE
[dados] Suporte SQL para equipe de comunicação

### ISSUE THREAD

**Issue by giovanecarusoredacao** [basedosdados/mais#688]
Uma demanda que surgiu na nossa  equipe de comunicação  é uma ajuda para tirarmos algumas dúvidas sobre como acessar e cruzar algumas bases usando o SQL, para conseguir produzir algumas visualizações mais simples ou extrair insights e infos das bases do nosso datalake público. 

Alguém da equipe de dados teria disponibilidade para fazermos um bate papo sobre isso? De preferência no período tarde/noite

**Comment by rdahis** [comment]
Rolou aqui? Pode fechar?

**Comment by crislanealves** [comment]
Não, não. Foi remarcado para terça-feira.
