### ISSUE TITLE
[dados] br_ms_sia

### ISSUE THREAD

**Issue by filipemsc** [basedosdados/mais#690]
**Metadados da base**

1. Descrição:  Sistema de informação para o registro padronizado, em nível nacional, dos atendimentos ambulatoriais

2. Qual o nome do conjunto? `br_ms_sia`

3. Qual o nome da(s) tabela(s)? Várias

4. Fonte original dos dados: https://datasus.saude.gov.br/transferencia-de-arquivos/

5. Cobertura espacial: Brasil

6. Cobertura temporal: de Jul/1994 a Dez/2007 - Jan/2008 até atualmente

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template
- [ ] Organizar arquivos auxiliares, se necessário.
- [ ] Preencher as tabelas de arquitetura
- [ ] Escrever código de captura e limpeza de dados.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by rdahis** [comment]
Como ficou aqui? Bora subir esses dados @filipemsc? :-)
