### ISSUE TITLE
[dados] Inconsistência no total de registros na tabela br_tse_eleicoes.receitas_candidatos

### ISSUE THREAD

**Issue by josircg** [basedosdados/mais#704]
**Descrição**
O total de registros da tabela de receitas_candidatos está incorreta para o ano de 2018. "receitas_candidatos_2018"

**Reproduzir**

     SELECT count(*) FROM `basedosdados.br_tse_eleicoes.receitas_candidato` where ano = 2018

A query retorna 310.522 só que existem registros 321.387 ao somarmos os registros dos CSV dos TSE.

Evidência:

https://colab.research.google.com/drive/1hS2gJA8BpeAMyojcYXmkLl8GkKSJIqoI?usp=sharing

O script que faz o upload está disponível?
Pergunto pois eu posso ajudar se a carga for feita em python.

**Comment by d116626** [comment]
Opa @josircg, valeu pelo report, essa é uma base recorrente nos nossos issues. Foi o @rdahis que tratou esses dados, o [código de tratamento](https://github.com/basedosdados/mais/tree/master/bases/br_tse_eleicoes) está em Stat.

**Comment by d116626** [comment]
Testei [aqui](https://colab.research.google.com/drive/1IHt7RBZt-yniVsnNdnogvKa8iSKeqqNv?usp=sharing) e deu diferente também. 
- TSE: 326.746
- BD: 310.522
