### ISSUE TITLE
Criar padrão para nomeação de variáveis.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#71]
Exemplos:

- Variáveis de porcentagem/proporção.
prefixo: prop_
valor máximo: 100

- Variáveis de log/ln.
prefixo: ln_

**Comment by fernandascovino** [comment]
queremos fechar um padrao aqui? acho audacioso hahaha

nessa linha tambem, os códigos seriam `id_[...]` correto? vale estipularmos como o Censo Escolar por exemplo prefixos para tipos de variáveis: 

- `in_[...]` --> indicador, 0/1
- `tp_[...]` --> tipo, dado categórico
- `qt_[...]` --> quantidades, dado numerico
- `no_[...]` --> nomes, dados textuais

Quais outras aqui?

**Comment by rdahis** [comment]
Minha preferência inicial é por nomes mais auto-explicativos e completos. Tipo "nome_", "numero_", "tipo_", etc. Acho ok ter tamanho de nome mais longo para garantir clareza. O que acha?

**Comment by rdahis** [comment]
Certas variáveis aparecem em diversas tabelas e, por isso, vale ter nomes padrão. Mesmo coisas sem prefixos ou sufixos.

Além disso, certas variáveis tem uma semântica clara que não precisaria incluir prefixos. Exemplo: a coluna de nome de município (eg. "Rio de Janeiro") pode se chamar só "municipio" ao invés de "nome_municipio". O mesmo vale para "estado", "pais", etc.

Temos que começar essa lista de nomes padrão na documentação e ir iterando nela com o tempo. Vamos criar?

Exemplos:
- ano
- estado
- estado_abrev
- id_municipio
- municipio
- raca
- genero
- idade
- naturalidade
- instrucao
- ocupacao

**Comment by rdahis** [comment]
Ver #154.
