### ISSUE TITLE
[dados] br_ms_sinan (Helpdesck)

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/mais#710]
**Tarefa**: Ajudar o @filipemsc a subir os dados do SINAN. 
**Responsável**: @crislanealves

- [x] Carregamento no BQ.
- [x] Preencher documentação.
- [x] Abrir PR.

**Comment by crislanealves** [comment]
@rdahis podemos fechar aqui e deixar só o[ #637](https://github.com/basedosdados/mais/issues/637) aberto?

**Comment by rdahis** [comment]
Yup!
