### ISSUE TITLE
[infra] Desabilitar data checks pós-merge para tabelas atualizadas frequentemente

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#715]
Os data checks diários da base `br_ms_vacinacao_covid19` estão custando caro. Podemos criar uma lista de tabelas nas quais desabilitamos essa action pós-merge?

**Comment by vncsna** [comment]
Ok

**Comment by vncsna** [comment]
Imagino que seja a mesma ideia continua na issue #685, daí vou fechar aquela e atualizo aqui quando terminar.
