### ISSUE TITLE
[docs] credenciais em .Renviron

### ISSUE THREAD

**Issue by aspeddro** [basedosdados/mais#717]
**Sua solicitação de recurso está relacionada a um problema? Por favor descreva.**
Cada projeto requer um `.env` com as credenciais. Essa abordagem é o padrão para credenciais. Ficar criando arquivo ou setando pela função é :disappointed:

**Descreva a solução que você gostaria**
Atualiza `README.md` e `docs` para colocar o `billing_project_id` no `.Renviron`. `billing_project_id` será definido toda vez que o usuário inicia o R.

**Contexto adicional**
Linux flavors: `$HOME/.Renviron`
Windows: `c:\Users\<username>\Documents\.Renviron`

`.Renviron`:
```sh
billing_project_id="your-id"
```

**Comment by pedrocava** [comment]
Acho que não é uma boa ideia. Se você *não* quiser manter um .env por projeto sempre pode definir a var ambiental no seu próprio computador e usar `base::Sys.getenv` para encontrar. Assim o pacote força uma maneira de lidar com credenciais, a API atual é agnóstica e aceita esse tipo de fluxo que você gostaria bem como vários outros. 

Estou aberto a argumentos, mas por enquanto acho que é melhor não.
