### ISSUE TITLE
Eleições - Detalhes Votação: Por que % votos válidos está >100 para senadores?

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#72]

**Comment by rdahis** [comment]
Acontece tanto a nível de município-zona como seção.

**Comment by fernandascovino** [comment]
algum update aqui @rdahis ?

**Comment by rdahis** [comment]
Não consegui olhar ainda. Posso estar não percebendo algo óbvio mas ainda não sei (i) se tem explicação ou (ii) tem um bug mesmo.

**Comment by fernandascovino** [comment]
estranho, não consigo fazer a query na base:

![image](https://user-images.githubusercontent.com/20743819/97091137-f115f280-160f-11eb-83eb-9e62afccc7cc.png)

**Comment by JoaoCarabetta** [comment]
@rdahis @fernandascovino isso está fechado?

**Comment by rdahis** [comment]
Não =O mas vou fechar o issue porque é questão dos dados originais. Vou tentar descobrir por fora e ajusto se tiver como.
