### ISSUE TITLE
Criar padrão para strings.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#73]
Proposta:
- Nomes (pessoas, bairros, cidades, estados, país, etc): Primeira letra maiúscula, com acentos.
- Todo o resto: tudo minúsculo, sem acentos.

**Comment by JoaoCarabetta** [comment]
Eu acho que devemos manter as strings originais. Nunca sabemos como a formatação original pode nos trazer informações relevantes. Muitas vezes dá pra usar a formatação para parsear algo, por exemplo.

Para mim, faria sentido somente mudar o nome das colunas.
