### ISSUE TITLE
[infra] <CI/R> Criaçao de um CI para o package de R.

### ISSUE THREAD

**Issue by kimjoaoun** [basedosdados/mais#739]
**Sua solicitação de recurso está relacionada a um problema? Por favor descreva.**

Durante o setup do CI para R, percebi que o package usa a sessao interativa para capturar um Billing ID (veja a linha 2 - https://github.com/basedosdados/mais/blob/master/r-package/tests/testthat/test-download.R).
Isso torna o processo de Setup de CI para R muito mais complexo, uma vez que seria necessário fazer o actions escrever no R - o que eu nem sei se é possível. 

**Descreva a solução que você gostaria**

Uma sugestão que dou é adicionar um Billing ID de testes no Github Secrets (https://docs.github.com/pt/actions/reference/encrypted-secrets), usar o `Sys.getenv()` para capturar esse Secret/Segredo com o Billing ID, e fazer as querys de testes usando ele. Se já existir esse secret, favor disponibilizar o nome dele. Também será necessário alterar os testes automatizados do package, para que estes passem a chamar o Billing ID.

**Comment by pedrocava** [comment]
Tá assim hoje porque não temos CI e os testes são feitos interativamente. A tarefa de configurar o CI inclui também mudar como as credenciais de um projeto são passadas para os testes.
