### ISSUE TITLE
[R] Integração com APIs de metadados do CKAN

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/mais#743]
APIs: https://basedosdados.org/openapi

api python: https://basedosdados.github.io/mais/reference_api_py/

- [x] ver funcionalidades do python de metadados
- [x] search == barra busca https://basedosdados.org/api/3/action/bd_dataset_search?resource_type=bdm_table

**Comment by d116626** [comment]
Provavelmente os dois endpoints mais relevantes
- retorna os metadados do dataset com as tabelas sendo o campo resource, usando o `dataset_id`: https://staging.basedosdados.org/api/3/action/bd_bdm_dataset_show?dataset_id=br_sp_alesp
- retorna os metadados das tabelas , usando o `dataset_id` e `table_id`: https://staging.basedosdados.org/api/3/action/bd_bdm_table_show?dataset_id=br_sp_alesp&table_id=deputado
