### ISSUE TITLE
[infra] Rollout convenções de código ao longo das semanas

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/mais#744]

**Comment by vncsna** [comment]
Progressão

- [ ] isort
- [ ] black
- [ ] pylint
- [ ] test

**Comment by vncsna** [comment]
Funcionando com https://github.com/basedosdados/mais/pull/786 e https://github.com/basedosdados/website/pull/97. Resta pro futuro ir melhorando a qualidade de código baseado nos hints dos linters.
