### ISSUE TITLE
[dados] br_bcb_selic

### ISSUE THREAD

**Issue by gustavoairestiago** [basedosdados/mais#745]
**Metadados da base**

1. Descrição: Taxa de juros que representa a taxa média ajustada das operações compromissadas com prazo de um dia útil lastreadas com títulos públicos federais custodiados no Sistema Especial de Liquidação e de Custódia (Selic).

2. Qual o nome do conjunto?  `br_bcb_selic`

3. Qual o nome da(s) tabela(s)? microdados / meta_selic

4. Fonte original dos dados: https://dadosabertos.bcb.gov.br/dataset/11-taxa-de-juros---selic

5. Cobertura espacial: brasil

6. Cobertura temporal: de 04-06-1986 a 2021

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [ ] Baixar a pasta template
- [ ] Preencher as tabelas de arquitetura
- [ ] Escrever código de captura e limpeza de dados.
- [ ] Organizar arquivos auxiliares, se necessário.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by laura-l-amaral** [comment]
Feito como pipeline
