### ISSUE TITLE
[infra] data-check checar chaves primárias contra diretórios

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#747]
Adicionar um novo data check que checa se as chaves primárias da tabela batem com as chaves primárias do diretório equivalente.

Exemplo 1: tabela nova tem coluna `id_municipio`. Nós checaríamos se todos os valores nessa coluna estão em `br_bd_diretorios_brasil.municipio:id_municipio`.

Exemplo 2: tabela nova tem coluna `ano`. Nós checaríamos se todos os valores nessa coluna estão em `br_bd_diretorios_data_tempo.ano:ano`.

**Comment by d116626** [comment]
Pra fazer isso, é bom já ter o metadado de `directory_column` do `columns` no `yaml`. Esse campo é do tipo:

```python

class DirectoryColumn(BaseModel):

    dataset_id : Optional[DirectoryEnum] = Field(title="ID Conjunto",user_input_hint=["<dataset_id>"])
    table_id   : Optional[Str]           = Field(title="ID Tabela",user_input_hint=["<table_id>"])
    column_name: Optional[Str]           = Field(title="Nome Coluna",user_input_hint=["<column_name>"])

```

Quando essas informações forem preenchidas a gente ataca esse novo `data-check`
