### ISSUE TITLE
[infra] Download poder baixar todas as tabelas do dataset

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#75]
Implementar bd.download(path, dataset_id='example').

**Comment by fernandascovino** [comment]
pode ser facilitado aqui com a função de listar as tabelas que o @aguiarandre estava desenvolvendo, seria bom colocar algum aviso tipo "You need to have XX GB available, do you wish to proceed? [y/N]"

**Comment by JoaoCarabetta** [comment]
@rdahis Queremos isso? me parece que a pessoa pode dar um list_tables e ir baixando.

**Comment by rdahis** [comment]
Eu ainda acho útil por completude. Mas entendo não ser prioridade agora.
