### ISSUE TITLE
[infra] Gamificar a contribuição/federalização.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#76]
- Ter uma página de exibição de contribuidores.
    Pode ser no README atualizando automaticamente quando a pessoa der um pull request.
- Desenhar estrutura de badges.

**Comment by JoaoCarabetta** [comment]
Acho que seria um bom momento de estruturar isso agora que temos contribuidores estáveis.

CC Equipe de dados:
@crislanealves @mavalentim @rdahis @Hevilyn @fernandascovino @d116626 

A gente já cogitou em ter uma estrutura de `badges` ou `achivements` que a pessoa que contribui para o BD pode ir ganhando. E assim, ganhando mais poder de edição. 

Por exemplo, na contribuição de dados, a estrutura seria a seguinte.

Level 0: 
 - 0 contribuições
 - Pode somente subir dados novos

Level 1:
 - 1 contribuição
 - Tudo do Level 0
 - Pode comentar na revisão de outros dados, mas não tem poder de aprovar os dados

Level 2: 
 - \>5 contribuições
 - Tudo do Level 1
 - Pode aprovar dados

Level 3:
 - \>5 contribuições
 - \>5 revisões
 - Tudo do Level 2
 - (?) Mais alguma coisa 

O que acham? Alguma ideia de como estruturar cada Level?
