### ISSUE TITLE
[infra] data-check mostrar dez linhas de cada tabela

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#767]
Adicionar um novo data check que mostra o header e primeiras dez linhas de cada tabela.

**Comment by d116626** [comment]
Não entendi a necessidade desse novo `data-check`, qual o objetivo?

**Comment by rdahis** [comment]
Tem coisas dos dados que só dá pra entender rodando uma query. Coisas que o data check em si não pega, tipo como estão as strings, se uma coluna devia ser INT ou FLOAT, etc.

Ter esses dados aparecendo no PR permitiria não precisar abrir o BQ.

**Comment by d116626** [comment]
> Tem coisas dos dados que só dá pra entender rodando uma query. Coisas que o data check em si não pega, tipo como estão as strings, se uma coluna devia ser INT ou FLOAT, etc.
> 
> Ter esses dados aparecendo no PR permitiria não precisar abrir o BQ.

Mas pow é tão simples ir no BQ e fz uma query com limit. Pra mim esse fluxo n faz muito sentido, vc tem que verificar o dado antes de acionar o `data-check`.

**Comment by d116626** [comment]
@rdahis considero essa feature desnecessária, vou fechar o issue blz?
