### ISSUE TITLE
[infra] Comando create já automaticamente jogar a pessoa para uma branch nova.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#77]
Valeria tanto para o 'dataset create' quanto pro 'table create'.

Nome da branch já poderia ser 'add_<dataset_id>_<table_id>'.

**Comment by JoaoCarabetta** [comment]
Acha que de fato vale a pena? O que podemos fazer é estruturar um comando de `setup` antes de tudo para fazer tal coisa. Não acho que isso deveria ficar a cargo do `table create`. Vai criar mta confusão na cabeça do usuário.

**Comment by rdahis** [comment]
Concordo. Vai ficar confuso mesmo. Melhor ter esse comando `setup` ou talvez nada e só deixar a documentação bem clara nesse sentido.
