### ISSUE TITLE
[dados] br_me_empresas_exportadoras_importadoras

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#771]
**Metadados da base**

1. Descrição: <A base apresenta um catálogo de estabelecimentos que exportaram, importaram ou realizaram ambas atividades no ano de referência>

2. Qual o nome do conjunto? `br_me_exportadoras_importadoras`

3. Qual o nome da(s) tabela(s)? `estabelecimentos`

4. Fonte original dos dados: https://www.gov.br/produtividade-e-comercio-exterior/pt-br/assuntos/comercio-exterior/estatisticas/empresas-brasileiras-exportadoras-e-importadoras

5. Cobertura espacial: Brasil

6. Cobertura temporal: de 1997 a 2021

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template
- [x] Preencher as tabelas de arquitetura
- [x] Escrever código de captura e limpeza de dados.
- [x] Organizar arquivos auxiliares, se necessário.
- [x] Criar tabela dicionário, se necessário.
- [x] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [x] Enviar tudo para revisão.

**Comment by folhesgabriel** [comment]
Sugiro que o nome do conjunto seja alterado para  `br_me_estabelecimentos_exportadores_importadores`. Nesta base, é apresentado o CNPJ completo que identifica empresas e suas filiais (estabelecimentos). Dessa forma o nome do conjunto estara alinhado com a tabela `estabelecimentos` do conjunto `br_me_cnpj`, que elenca o CNPJ completo, identificando empresas e seus estabelecimentos - diferente do tabela `empresas` do conjunto  `br_me_cnpj` que possui somente  o CNPJ básico.
