### ISSUE TITLE
[dados] br_sp_od

### ISSUE THREAD

**Issue by lucasccdias** [basedosdados/mais#772]
**Metadados da base**

1. Descrição: Pesquisa Origem e Destino 2017 (RMSP)

2. Qual o nome do conjunto? `br_sp_od`

3. Qual o nome da(s) tabela(s)? -

4. Fonte original dos dados: http://www.metro.sp.gov.br/pesquisa-od/

5. Cobertura espacial: Região Metropolitana de SP

6. Cobertura temporal: 2017

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template
- [ ] Preencher as tabelas de arquitetura
- [ ] Escrever código de captura e limpeza de dados.
- [ ] Organizar arquivos auxiliares, se necessário.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by Blackbel** [comment]
> **Metadados da base**
> 
>     1. Descrição: Pesquisa Origem e Destino 2017 (RMSP)
> 
> 
>     1. Qual o nome do conjunto? `br_sp_od`
> 
>     2. Qual o nome da(s) tabela(s)? -
> 
>     3. Fonte original dos dados: http://www.metro.sp.gov.br/pesquisa-od/
> 
>     4. Cobertura espacial: Região Metropolitana de SP
> 
>     5. Cobertura temporal: 2017
> 
> 
> **Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))
> 
>     * [x]  Baixar a pasta template
> 
>     * [ ]  Preencher as tabelas de arquitetura
> 
>     * [ ]  Escrever código de captura e limpeza de dados.
> 
>     * [ ]  Organizar arquivos auxiliares, se necessário.
> 
>     * [ ]  Criar tabela dicionário, se necessário.
> 
>     * [ ]  Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
> 
>     * [ ]  Enviar tudo para revisão.

**Comment by Blackbel** [comment]
> **Metadados da base**
> 
>     1. Descrição: Pesquisa Origem e Destino 2017 (RMSP)
> 
> 
>     1. Qual o nome do conjunto? `br_sp_od`
> 
>     2. Qual o nome da(s) tabela(s)? -
> 
>     3. Fonte original dos dados: http://www.metro.sp.gov.br/pesquisa-od/
> 
>     4. Cobertura espacial: Região Metropolitana de SP
> 
>     5. Cobertura temporal: 2017
> 
> 
> **Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))
> 
>     * []  Baixar a pasta template
> 
>     * [ ]  Preencher as tabelas de arquitetura
> 
>     * [ ]  Escrever código de captura e limpeza de dados.
> 
>     * [ ]  Organizar arquivos auxiliares, se necessário.
> 
>     * [ ]  Criar tabela dicionário, se necessário.
> 
>     * [ ]  Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
> 
>     * [ ]  Enviar tudo para revisão.
