### ISSUE TITLE
[infra] implementar o data-check com great expectations

### ISSUE THREAD

**Issue by vncsna** [basedosdados/mais#782]
**Sua solicitação de recurso está relacionada a um problema? Por favor descreva.**
O data check esta muito complexo.

**Descreva a solução que você gostaria**
Gostaria que o data check seja implementado como great expectations se possível.

**Descreva alternativas que você considerou**
Por enquanto não conheço um outro framework além do great expectations.

**Contexto adicional**
É necessário analisar a viabilidade desta solução, então implementar as checagens atuais. E depois solucionar as issues #747 e #767 no novo ambiente.

**Comment by HenriqueAJNB** [comment]
@vncsna essa issue está aberta ainda?
