### ISSUE TITLE
[dados] Processar e priorizar a lista de tabelas do Legislativo.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#784]
camara_v1                                  ----------
  aguardo_designacao_relator_ce            (EXTERNAL)
  deputados_blocos                         (EXTERNAL)
  deputados_comissionados                  (EXTERNAL)
  deputados_detalhes                       (EXTERNAL)
  liderancas                               (EXTERNAL)
  proposicao_votacao_bancada               (EXTERNAL)
  proposicao_votacao_deputado              (EXTERNAL)
  proposicoes_tramitadas_periodo           (EXTERNAL)
  proposicoes_votadas_plenario             (EXTERNAL)

camara_v2                                  ----------
  blocos                                   (EXTERNAL)
  **[deputados                                (EXTERNAL)](https://basedosdados.org/dataset/br-camara-atividade-legislativa)**
  deputados_despesas                       (EXTERNAL)
  deputados_detalhes                       (EXTERNAL)
  deputados_discursos                      (EXTERNAL)
  deputados_eventos                        (EXTERNAL)
  deputados_mesa                           (EXTERNAL)
  deputados_orgaos                         (EXTERNAL)
  **eventos                                  (EXTERNAL)**
  eventos_orgaos                           (EXTERNAL)
  eventos_pauta                            (EXTERNAL)
  legislaturas                             (EXTERNAL)
  [orgaos                                   (EXTERNAL)](https://basedosdados.org/dataset/br-camara-atividade-legislativa)
  partidos                                 (EXTERNAL)
  partidos_detalhes                        (EXTERNAL)
  proposicoes                              (EXTERNAL)
  proposicoes_autores                      (EXTERNAL)
  proposicoes_live                         (EXTERNAL)
  proposicoes_temas                        (EXTERNAL)
  tramitacoes                              (EXTERNAL)
  votacoes                                 (EXTERNAL)
  votacoes_detalhes                        (EXTERNAL)
  votacoes_orientacoes                     (EXTERNAL)
  votacoes_votos                           (EXTERNAL)

senado                                     ----------
  lider_governo_senado                     (EXTERNAL)
  pessoas_comissionados                    (EXTERNAL)
  pessoas_servidores                       (EXTERNAL)
  proposicoes                              (EXTERNAL)
  proposicoes_lista                        (EXTERNAL)
  proposicoes_tramitadas_periodo           (EXTERNAL)
  senador_liderancas                       (EXTERNAL)
  senador_lista_atual                      (EXTERNAL)
  senador_mandatos                         (EXTERNAL)
  senador_relatorias                       (EXTERNAL)
  senador_votacoes                         (EXTERNAL)
  **senadores                                (EXTERNAL)**
  senadores_em_exercicio                   (TABLE)
  tramitacoes                              (EXTERNAL)
  **votacoes_plenario                        (EXTERNAL)**

**Comment by laura-l-amaral** [comment]
Consultar a API da câmara legislativa ao invés das tabelas
