### ISSUE TITLE
[dados] br_bd_diretorios_brasil.natureza_juridica

### ISSUE THREAD

**Issue by gustavoairestiago** [basedosdados/mais#789]
**Metadados da base**

1. Descrição: br_bd_diretorios_brasil

2. Qual o nome do conjunto? `br_bd_diretorios_brasil.`

3. Qual o nome da(s) tabela(s)? `natureza_juridica`

4. Fonte original dos dados: https://concla.ibge.gov.br/estrutura/natjur-estrutura

5. Cobertura espacial: br

6. Cobertura temporal: de 1995 a 2018

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [ ] Baixar a pasta template
- [ ] Preencher as tabelas de arquitetura
- [ ] Escrever código de captura e limpeza de dados.
- [ ] Organizar arquivos auxiliares, se necessário.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by rdahis** [comment]
Estamos subindo uma versão simplificada em #858, mas ainda falta subir uma que contemple a variação entre anos.
