### ISSUE TITLE
[dados] Problemas em `br_tse_eleicoes`

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#798]
- [ ] "Esses municípios aparecem com eleito na tabela de resultado_candidato, mas o candidato não está na tabela de candidatos. Isso so pra prefeito, nem cheguei a ver no caso de vereador."

```
ano     id_municipio
2016    2701506
2016    2706406
2016    2313401
2016    5204656
2016    2110401
2016    5100607
2016    3305802
2016    2400901
2016    2404507
2016    3519303
2016    3523008
2016    3524006
2016    3527108
2016    3533403
2020    2922755
2020    2314102
2020    3147600
2020    4128559
2020    4302105
2020    4317707
2020    2807006
2020    3517406
2020    3519253
```

Query exemplo:
```sql
SELECT 
  t1.*
FROM `basedosdados.br_tse_eleicoes.candidatos`  t1
WHERE (t1.ano=2016) 
  AND (t1.cargo='prefeito')
  AND t1.id_municipio = '2701506'
```

- [ ] Na tabela de despesas, o `numero_candidato` ta invertido com `cpf_candidato`.
```
SELECT *
FROM `basedosdados.br_tse_eleicoes.despesas_candidato` 
WHERE (ano=2020 or ano=2016) AND sigla_uf='AC'
```

Reportado pelo @d116626 (o herói das eleições).

**Comment by d116626** [comment]
tem esse outro bug aqui na tabela de `receita_candidato`, onde a query n retorna nada porem esse candidato possui [dados](https://divulgacandcontas.tse.jus.br/divulga/#/candidato/2016/2/01104/10000003074) na prestação de contas do tse

```sql
WITH receita_candidato as (
    SELECT
      ano,
      sigla_uf,
      sigla_partido,
      numero_candidato,
      cargo,
      id_municipio,
      origem_receita,
      fonte_receita,
      valor_receita
    FROM `basedosdados.br_tse_eleicoes.receitas_candidato`
    WHERE ano=2016
      AND sigla_uf = 'AC'
      AND id_municipio='1200328'
      AND numero_candidato = '45'
  )
  
SELECT * FROM receita_candidato
```

**Comment by rdahis** [comment]
- [ ] Incluir `sequencial_candidato` em `resultados_candidato`.

**Comment by d116626** [comment]
>     * [ ]  Incluir `sequencial_candidato` em `resultados_candidato`.

eu incluiria em todas as tabelas de `resultado_*`
