### ISSUE TITLE
[dados] Dados de populacao incorretos

### ISSUE THREAD

**Issue by joaovgranja** [basedosdados/mais#808]
**Descrição**
Dados de população incorretos para município 1503754.

**Reproduzir**
Código em `R`.
```
library( dplyr )
library( magrittr )
library( bigrquery )
library( basedosdados )

# Faca sua conexao com o BigQuery antes de rodar o codigo abaixo.
query <- "SELECT * FROM `basedosdados.br_ibge_populacao.municipio`"
dt_pop <- read_sql(query)
dt_pop %>% 
  filter(
    id_municipio == "1503754",
    ano >= 2011
    )
```

**Comportamento esperado**
Dados consistentes com [IBGE](https://www.ibge.gov.br/estatisticas/sociais/populacao/9103-estimativas-de-populacao.html?=&t=downloads). Os dados na imagem abaixo são diferentes dos dados no link. 

**Capturas de tela**
O código acima retorna:
![Screenshot from 2021-09-23 19-20-39](https://user-images.githubusercontent.com/35388471/134562659-90c0d472-0009-41b0-9300-5a47c4ef8608.png)

**Contexto adicional**
Esse município específico é um dos casos em que as tabelas originais possuem notas de rodapé e separadores numéricos distintos (vide a imagem abaixo -- o ponto em 10,351 é explícito). Essa talvez seja a origem dos dados omitidos e das discrepâncias (contudo, casos similares foram tratados corretamente)
![Screenshot from 2021-09-23 19-31-01](https://user-images.githubusercontent.com/35388471/134564088-1b173924-fa5a-4563-b48b-d39c2666e4b1.png)
.

**Comment by rdahis** [comment]
Dúvida aqui @joaovgranja. Em 2017, para esse município a população na tabela está `8059`, enquanto na nota de rodapé está `41287`. O número correto para estar nos nossos dados é qual?

**Comment by rdahis** [comment]
A query
```
SELECT * FROM `basedosdados-dev.br_ibge_populacao.municipio`
WHERE id_municipio = '1503754' AND ano >= 2011
```
agora retorna:
![Screen Shot 2021-09-27 at 1 32 58 PM](https://user-images.githubusercontent.com/6617207/134949220-77bd276e-5f9d-4c78-9bd8-b91338506d64.png)

**Comment by joaovgranja** [comment]
Acho que nesse caso faz mais sentido retornar os números da tabela e não os números da nota de rodapé, não? Essa série usando os número de rodapé não me parece fazer muito sentido (de 14k pra 41k pra 8k), enquanto a série que resulta dos dados da tabela me parece bastante razoável. A nota de rodapé também retifica a estimativa da população "para efeito de distribuição do Fundo de Participação dos Municípios". Acho que isso também sugere usar os valores da tabela e não do rodapé.

**Comment by rdahis** [comment]
> Acho que nesse caso faz mais sentido retornar os números da tabela e não os números da nota de rodapé, não? Essa série usando os número de rodapé não me parece fazer muito sentido (de 14k pra 41k pra 8k), enquanto a série que resulta dos dados da tabela me parece bastante razoável. A nota de rodapé também retifica a estimativa da população "para efeito de distribuição do Fundo de Participação dos Municípios". Acho que isso também sugere usar os valores da tabela e não do rodapé.

Acho que não deixei claro antes. Esse exemplo todas os dados aí estão vindo da tabela mesmo, e não do rodapé. E por exemplo, em 2012, a população aqui aparece `41487` e nem tem rodapé na tabela original para substituir o valor =/

**Comment by joaovgranja** [comment]
Acho que a gente tá olhando pra fontes diferentes. Na página tem dois arquivos (entre outros) pra 2012: estimativa_2012_DOU_28_08_2012_xls.zip e estimativa_2012_TCU_20170614.xls. O primeiro de fato mostra 41487 na tabela com uma nota de rodapé que diz "em decorrência de decisão judicial". O segundo arquivo mostra 14339 como o valor da população, com uma nota de rodapé sobre o valor alternativo 41487.

Me parece que os arquivos DOU vão refletir essas decisões judiciais, enquanto os arquivos TCU parecem ser de fato a estimativa obtida pelo IBGE. Talvez faça mais sentido usar os arquivos TCU.

Obrigado!

**Comment by rdahis** [comment]
Eu estava com arquivos errados mesmo, desatualizados aqui =O. Mas tudo certo agora! Valeu por apontar @joaovgranja.

**Comment by joaovgranja** [comment]
Maravilha, valeu!
