### ISSUE TITLE
[infra] Data check gerando concatenações nulas

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#813]
Para discutirmos: devemos mudar o comportamento do data check que agora retorna concatenações nulas quando qualquer uma das colunas é nula?

Exemplo mostrando comportamento:
``` sql
WITH teste AS (
  SELECT *
  FROM `basedosdados-dev.br_ms_cnes.profissional` t
  LIMIT 1000
)

SELECT 
  CONCAT(cns, "&", id_estabelecimento_cnes),
  cns, id_estabelecimento_cnes
FROM teste
```

**Comment by d116626** [comment]
Não! Pode fechar o issue kkkkk

Brincadeiras a parte meu ponto é que se uma coluna tem `null` então não é `primary_key`. Suponha que troquemos o `null` por `" "`, então poderão surgir combinações que não são únicas como no exemplo abaixo;

|  ano 	| genero 	| idade 	|
|:----:	|:------:	|:-----:	|
| 2020 	|    F   	|   10  	|
| 2020 	|    F   	|   11  	|
| 2020 	|    M   	|  " "  	|
| 2020 	|    M   	|  " "  	|

**Comment by filipemsc** [comment]
Um (leve) contraponto é que acho que teoricamente isso pode rolar. Ex: se você tem colunas disjuntas que geram uma identificação.

|  ano 	| city  | state	|
|:----:	|:------:	|:-----:	|
| 2020 	|    1   	|   a 	|
| 2020 	|    2   	|   b |
| 2020 	|    null |   a |
| 2020 	|    null 	|  b 	|

Acho que já vi isso rolar fora da BD, numa base de covid. As colunas com cidade nulas eram as que indicavam observações de um estado todo. Essas três colunas seriam uma primary key, não? 

(Mas acho que, na BD, esse exemplo não tem muita relevância anyway)

**Comment by vncsna** [comment]
Eu fui marcado, mas parece ser um tipo de questão que deve ser decidida pelo pessoal que trabalha com os dados no dia a dia. O que eu acho é que o valor nulo em chaves primárias não é aceitável, talvez seja válido criar uma convenção pra isso (um valor padrão de substituição, ou valores padrões para cada caso) com a devida explicação na descrição da base.

**Comment by rdahis** [comment]
Então, mas aí entra a questão que tava pensando aqui. Em dados públicos tem colunas que **deveriam** ser chaves primárias mas não são na prática (typos, nulos, duplicados, etc). Tipo CPF. E nos dados em produção não podemos simplesmente excluir linhas não identificadas unicamente, ou preencher o que está nulo arbitrariamente.

Simplesmente excluir elas é drástico demais, porque a maior parte das tabelas tem esses problemas. E nós ainda queremos saber a porcentagem identificada unicamente por essas chaves "semi-"primárias. E queremos indicar para usuários quais são essas colunas.

**Proposta**: o campo `identifying_columns` virar complexo, com dois subcampos: (1) lista de colunas chaves "semi-"primárias, e (2) a % identificada unicamente.

**Comment by d116626** [comment]
Se é assim então é só deixar como tá e mudar o critério de aprovação desso check de primary key. Não acho que seja necessário ter um campo falando a porcentagem

**Comment by rdahis** [comment]
> Se é assim então é só deixar como tá e mudar o critério de aprovação desse check de primary key. Não acho que seja necessário ter um campo falando a porcentagem

Beleza, e atualizar a descrição do campo no schema para avisar que ele não é necessariamente uma primary key.

@vncsna pode fazer o seguinte nesse data check:
1. Fazer os nulos não serem jogados fora. Pode ser substituindo por um white space na query.
2. Fazer o check só reportar a % identificada unicamente, sem dar erro caso não seja 100%.
