### ISSUE TITLE
R Version

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/mais#82]
- [x] Procurar uma pessoa Rzeira pra cuidar do R

**Comment by rdahis** [comment]
Marcando o @pedrocava, que começou a desenvolver.

**Comment by JoaoCarabetta** [comment]
Amém!

Vamos alinhar as funções de R e Python para que elas sejam as mesmas @pedrocava

**Comment by rdahis** [comment]
@pedrocava avisa se pudermos ajudar com alguma coisa no desenvolvimento!
