### ISSUE TITLE
[dados] br_bd_diretorios_brasil.unidade_gestora

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#856]
**Metadados da base**

1. Descrição: Informações sobre Unidades Gestoras do SIASG.

2. Qual o nome do conjunto? `br_bd_diretorios_brasil`

3. Qual o nome da(s) tabela(s)? `unidade_gestora`

4. Fonte original dos dados: Portal da Transparência

5. Cobertura espacial: Brasil

6. Cobertura temporal: 

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [ ] Baixar a pasta template
- [ ] Preencher as tabelas de arquitetura
- [ ] Escrever código de captura e limpeza de dados.
- [ ] Organizar arquivos auxiliares, se necessário.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by laura-l-amaral** [comment]
Quando for ser feita verificar se é possível unir com #679
