### ISSUE TITLE
[infra] Partições com valor nulo

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#859]
**Problema**

Dá um erro no `Table.create()` quando existem partições com valor vazio. Por exemplo, na RAIS há linhas com `id_municipio=''`. Na estrutura do Hive isso apareceria como `/id_municipio=/`. Como o BQ está tipando a coluna `id_municipio` como `INT64` em staging, ele dá erro.

**Solução**

Se partições fossem sempre tipadas como `STRING` acho que daria certo.

**Comment by d116626** [comment]
Ref: https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#HivePartitioningOptions

Onde a mudança deve ser implementada: 
https://github.com/basedosdados/mais/blob/3c7bf1786f36cd1028b38409fb95546db7a9ebb8/python-package/basedosdados/upload/datatypes.py#L29-L39

----

Tipei como string e ficaria assim: 
<img width="347" alt="image" src="https://user-images.githubusercontent.com/8954716/137164408-2582aaed-973e-4da3-9cf1-6a7d2aca740b.png">

No caso de `/id_municipio=/`, mesmo tipado como string da erro: 

BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/basedosdados-dev/datasets/test_dataset_staging/tables?prettyPrint=false: Partition keys should be invariant from table creation across all partitions, with the number of partition keys held constant with invariant names.  Expected 4 partition keys ([ano, mes, sigla_uf, id_municipio]), but 3 ([ano, mes, sigla_uf]) were encountered for partition ano=2021/mes=2/sigla_uf=SP/id_municipio=.

Mesmo forçando `STRINGS` no `hive_partitioning.mode` ainda n tem a possibilidade de um `id_municipio=null`
