### ISSUE TITLE
[dados] br_bd_diretorios_brasil.distrito

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#877]
Problema: hoje o diretório de `distrito` é identificado por `ano` e `id_distrito`.

Soluções possíveis:
* Transformar `distrito` em `distrito_1991`, `distrito_2000`, `distrito_2010`, etc?
* Manter só o mais recente e criar um conjunto separado `br_bd_distrito` (?) para manter o histórico ao longo do tempo.
* Mudar o metadado `directory_column` para ser 1+ coluna. (no caso `ano` e `id_distrito`). Se for isso, adicionar ao issue https://github.com/basedosdados/website/issues/55.

**Comment by laura-l-amaral** [comment]
duplicated
