### ISSUE TITLE
[dados] atualiza info de dados novos no site

### ISSUE THREAD

**Issue by lucasnascm** [basedosdados/mais#882]
**Bases a serem incluídas**

- [x] br_ms_populacao: https://basedosdados.org/dataset/7b662d66-4526-4e02-86bf-e67fb852ed07
- [x] br_ms_sinasc: https://basedosdados.org/dataset/71251b38-7662-4c6a-8210-3d1046bd87aa
- [x] br_ms_sinan.microdados_violencia: https://basedosdados.org/dataset/4ad583d5-60cc-4e34-9118-515763810272
- [x] br_inep_ana: https://basedosdados.org/dataset/1132dd1d-5c72-41d9-b436-2422774b4911
- [x] br_anp_precos_combustiveis
- [x] br_ibge_ipca
- [x] br_ibge_ipca15
- [x] br_ibge_inpc
- [x] br_mme_energia_eletrica
- [x] br_ons_energia_armazenada
- [x] br_ms_imunizacoes

**Mudança na organização**

- [x] Dados Meteorológicos de Temperatura e Precipitação -  INMET
- [x] Estatísticas de Segurança Pública do Rio de Janeiro - ISSP
- [x] Indicadores de Programas do Ministério da Cidadania - Ministério da Cidadania
- [x] Dados do Observatório da Criança e do Adolescente - Abrinq
- [x] Pesquisa Online Sobre a Comunidade LGBT - Fundamental Rights Agency
- [x] Dados históricos das Olimpíadas - Kaggle
- [x] Transrespect x Transphobia - Transrespect x Transphobia
- [x] Registros de Servidores Públicos do Executivo Federal - CGU
- [x] Classificação Brasileira de Ocupações 2002 - IBGE
- [x] Standardized World Income Inequality Database (SWIID) - Havard
- [x] Comprehensive Universe of U.S. Patents (CUSP) - Enrico Berkes
- [x] Linchamentos - Beck and Tolnay (1995) - CSDE Lynching Database
- [x] Dados abertos do Condado de Suffolk, Nova York - OpenData Sufolk, NY
- [x] GitHub Typo Corpus - Github
- [x] Terremotos no México - SpringerNature
- [x] Autocratic Ruling Parties Dataset (ARPD) - Michael Miller
- [x] Atlas Etnográfico (Murdock) - Devecondata
- [x] Indicadores criminais de SP - SSPSP
- [x] Database of British and Irish Hills (DoBIH) - Database of British and Irish Hills
- [x] Barro-Lee Education Attainment Dataset - BarroLeeDataSet
- [x] National Elections Across Democracy and Autocracy - Nelda

**Comment by rdahis** [comment]
@crislanealves pode preencher o resto da informações por favor? https://basedosdados.org/dataset/br-mme-consumo-energia-eletrica

**Comment by rdahis** [comment]
@lucasnascm pode preencher o resto por favor?
https://basedosdados.org/dataset/br-ms-imunizacoes
