### ISSUE TITLE
[dados] Atualização de metadados de colunas de `br_ibge_censo_demografico` pedindo tudo preenchido.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#886]
Conjunto: https://basedosdados.org/dataset/30dfff98-0bad-4d03-9aa4-8213ad94e947

O formulário pede todos os campos de colunas preenchidos como se fossem campos obrigatórios.

Só acontece nas tabelas `microdados_domicilio_2010` e `microdados_pessoa_2010`. Para todas as outras (1970, 1980, 1991, 2000) a edição via formulário deu certo.

Quando conseguir editar, atualizar:
* Mover url de `auxiliary_files` para campo.
* Subir `sigla_uf` para a posição certa em colunas.

**Comment by crislanealves** [comment]
consertado!
