### ISSUE TITLE
[infra] Criar testes para os entrypoints da CLI

### ISSUE THREAD

**Issue by vmussa** [basedosdados/mais#903]
**Descrição**
Ao fazer alterações no código, precisamos, por vezes, testar manualmente a CLI, já que os testes não capturam sua dinâmica e seu contexto. Isso pode resultar na publicação de um cliente quebrado no PyPI, como aconteceu no PR #898. 

**Reproduzir**
Basta fazer alguma alteração em uma função que a CLI use, mudando os nomes dos argumentos, por exemplo, e consertar os testes. A CLI vai quebrar e os testes estarão passando.

**Comportamento esperado**
Ao alterar funções de modo a quebrar a CLI, os testes deveriam acusar a inconsistência.

**Comment by HenriqueAJNB** [comment]
Esse issue está aberto ainda? @vmussa @vncsna

**Comment by laura-l-amaral** [comment]
Cli foi descontinuada na v2 do pacote
