### ISSUE TITLE
[infra] Colunas invertidas e id com ponto decimal `br_geobr_mapas.setor_censitario_2010`

### ISSUE THREAD

**Issue by d116626** [basedosdados/mais#915]
A tabela de shape files do setor censitário está com ponto decimal nas colunas `id_município`  e ` id_vizinhanca`, além das colunas `nome_vizinhanca` e  `id_vizinhanca` estarem trocadas.

```sql
SELECT 
  * 
FROM `basedosdados-staging.br_geobr_mapas_staging.setor_censitario_2010`  
WHERE estado_abrev = 'SP'
LIMIT 1000
```

Da pra já renomear a partição de `estado_abrev`  pra `sigla_uf` tbm

Vou consertar usando query do `publish.sql` nesse PR #914 , mas seria melhor arrumar nos dados que estão no [storage](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_geobr_mapas/setor_censitario_2010;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=basedosdados-dev&prefix=&forceOnObjectsSortingFiltering=false).

**Comment by crislanealves** [comment]
Já foi resolvido.
