### ISSUE TITLE
[infra] `table create` não criando `publish.sql` novo a partir de csv

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#924]
Rodei `basedosdados table create br_bd_diretorios_brasil escola --if_table_exists replace --if_storage_data_exists replace --if_table_config_exists replace --path 'path/file.csv'`

Isso gera:
* `table_config.yaml` atualizado com os metadados novos no CKAN
* mas não gera um `publish.sql` novo.

Rodando no 1.6.0 beta 3.

**Comment by d116626** [comment]
> Rodei `basedosdados table create br_bd_diretorios_brasil escola --if_table_exists replace --if_storage_data_exists replace --if_table_config_exists replace --path 'path/file.csv'`
> 
> Isso gera:
> 
>     * `table_config.yaml` atualizado com os metadados novos no CKAN
> 
>     * mas não gera um `publish.sql` novo.
> 
> 
> Rodando no 1.6.0 beta 3.

Fiz algumas modificações agora pouco, testa usando o 1.6.0 beta 6
