### ISSUE TITLE
[dados] br_bd_indicadores_economicos

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#938]
**Metadados da base**

1. Descrição: Criar VIEW com lista de indicadores. Pensar já nos metadados.

2. Qual o nome do conjunto? `br_bd_indicadores_economicos`

3. Qual o nome da(s) tabela(s)? `ano`, `mes`

4. Fonte original dos dados: <link>

5. Cobertura espacial: Brasil

6. Cobertura temporal: de XXXX a YYYY

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [ ] Baixar a pasta template
- [ ] Preencher as tabelas de arquitetura
- [ ] Escrever código de captura e limpeza de dados.
- [ ] Organizar arquivos auxiliares, se necessário.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by laura-l-amaral** [comment]
Despriorizado
