### ISSUE TITLE
[dados] Informações repetidas em `br_me_socios.empresa`

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#939]
**Descrição**
A coluna `descricao_tipo_logradouro` está igual a `razao_social` na tabela `br_me_socios.empresa`. É isso mesmo?

**Comment by athossampayo** [comment]
Como comentado, @crislanealves, pode ser útil usar os dados do [cuducos/minhareceita](https://github.com/cuducos/minha-receita), inclusive eles disponibilizam todas as bases da Receita para além de somente sócios.

**Comment by crislanealves** [comment]
@rdahis

**Comment by rdahis** [comment]
@kalinest já pode resolver esse issue também conforme tratar os dados na versão nova.

**Comment by rdahis** [comment]
Fechando pois está deprecado.
