### ISSUE TITLE
[dados-atualizacao] br_me_comex_stat

### ISSUE THREAD

**Issue by lucasnascm** [basedosdados/mais#957]
**Descrição do dataset**

Qual o nome do conjunto? `br_me_comex_stat`

Qual o nome da(s) tabela(s)? `municipio_exportacao, `municipio_importacao`, `ncm_exportacao`, `ncm_importacao`

URL Código: https://github.com/basedosdados/mais/tree/master/bases/br_me_comex_stat/code

Cobertura espacial: Brasil

Cobertura temporal: 1997 a 2021

Frequência de atualização: mes

Última atualização feita pela BD: 01/04/2021

**Comment by rdahis** [comment]
Aproveita e já fecha o #486 e #871. Tem que refazer a parte de IDs virarem tipo STRING.
