### ISSUE TITLE
[dados] br_inep_censo_magisterio

### ISSUE THREAD

**Issue by lucasnascm** [basedosdados/mais#961]
**Metadados da base**

1. Descrição: O Censo dos Profissionais do Magistério da Educação Básica 2003 apresenta informações sobre o perfil dos docentes atuantes na Educação Infantil, no Ensino Fundamental, no Ensino Médio, na Educação de Jovens e Adultos (EJA) e na Educação Especial. A publicação aborda características que compõem a identidade desses educadores como cor ou raça, sexo, idade, estado civil e número de filhos. Reúne, ainda, elementos facilitadores da condução de estudos transversais sobre a formação acadêmica, o salário, a experiência profissional e as condições socioeconômicas desses professores.

2. Qual o nome do conjunto? `br_inep_censo_magisterio`

3. Qual o nome da(s) tabela(s)? `microdados`

4. Fonte original dos dados:
https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/censo-dos-profissionais-do-magisterio

5. Cobertura espacial: brasil

6. Cobertura temporal: 2003

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [ ] Baixar a pasta template
- [ ] Preencher as tabelas de arquitetura
- [ ] Escrever código de captura e limpeza de dados.
- [ ] Organizar arquivos auxiliares, se necessário.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by crislanealves** [comment]
Retomar depois.
