### ISSUE TITLE
[dados] br_inep_censo_escolar

### ISSUE THREAD

**Issue by lucasnascm** [basedosdados/mais#962]
**Metadados da base**

1. Descrição: Trata-se do principal instrumento de coleta de informações da educação básica, que abrange as suas diferentes etapas e modalidades: ensino regular (educação Infantil e ensinos fundamental e médio), educação especial e educação de jovens e adultos (EJA). O Censo Escolar coleta dados sobre estabelecimentos, matrículas, funções docentes, movimento e rendimento escolar.

2. Qual o nome do conjunto? `br_inep_censo_escolar`

3. Qual o nome da(s) tabela(s)? `docente`, `escola`, `matricula`, `turma`

4. Fonte original dos dados: 
https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/censo-escolar

5. Cobertura espacial: brasil

6. Cobertura temporal: de 1995 a 2008

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [ ] Baixar a pasta template
- [ ] Preencher as tabelas de arquitetura
- [ ] Escrever código de captura e limpeza de dados.
- [ ] Organizar arquivos auxiliares, se necessário.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by crislanealves** [comment]
Retomar depois.
