### ISSUE TITLE
[dados] br_inep_encceja

### ISSUE THREAD

**Issue by lucasnascm** [basedosdados/mais#964]
**Metadados da base**

1. Descrição: O Exame Nacional para Certificação de Competências de Jovens e Adultos (Encceja) tem por objetivo construir uma referência nacional de autoavaliação para jovens e adultos por meio de avaliação de competências, habilidades e saberes adquiridos em processo escolar ou extraescolar; estruturar uma avaliação direcionada a jovens e adultos que sirva às Secretarias de Educação para que estabeleçam o processo de certificação dos participantes, em nível de conclusão do Ensino Fundamental ou Ensino Médio, por meio da utilização dos resultados do Exame; oferecer uma avaliação para fins de correção do fluxo escolar; construir, consolidar e divulgar seus resultados para que possam ser utilizados na melhoria da qualidade na oferta da Educação de Jovens e Adultos e no processo de certificação; construir parâmetros para a autoavaliação do participante, visando a continuidade de sua formação e sua inserção no mundo do trabalho; possibilitar o desenvolvimento de estudos e indicadores sobre educação brasileira

2. Qual o nome do conjunto? `br_inep_encceja`

3. Qual o nome da(s) tabela(s)? `internacional_regular`, `nacional_regular`, `nacional_ppl`, `nacional_ppl_qse`

4. Fonte original dos dados:
https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/encceja

5. Cobertura espacial: brasil

6. Cobertura temporal: de 2014 a 2019

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [ ] Baixar a pasta template
- [ ] Preencher as tabelas de arquitetura
- [ ] Escrever código de captura e limpeza de dados.
- [ ] Organizar arquivos auxiliares, se necessário.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by crislanealves** [comment]
Retomar depois.
