### ISSUE TITLE
[dados] br_inep_provao

### ISSUE THREAD

**Issue by lucasnascm** [basedosdados/mais#967]
**Metadados da base**

1. Descrição: O provão - Exame Nacional de Cursos -  foi implementado em 1996, avaliando cursos de três áreas do conhecimento — administração, direito e engenharia civil —, e ampliou sua abrangência gradualmente. Em sua última edição, em 2003, a aplicação do Provão alcançou 30 áreas do conhecimento

2. Qual o nome do conjunto? `br_inep_provao`

3. Qual o nome da(s) tabela(s)? `aluno`, `ies`

4. Fonte original dos dados:
https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/provao

5. Cobertura espacial: brasil

6. Cobertura temporal: de 1997 a 2003

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [ ] Baixar a pasta template
- [ ] Preencher as tabelas de arquitetura
- [ ] Escrever código de captura e limpeza de dados.
- [ ] Organizar arquivos auxiliares, se necessário.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by crislanealves** [comment]
Retomar depois.
