### ISSUE TITLE
[dados] br_inep_pnera

### ISSUE THREAD

**Issue by lucasnascm** [basedosdados/mais#969]
**Metadados da base**

1. Descrição: Dentre as informações educacionais produzidas pelo Inep, destaca-se a Pesquisa Nacional da Educação na Reforma Agrária – PNERA/2004, realizada pela Diretoria de Tratamento e Disseminação de Informações Educacionais em parceria com INCRA/PRONERA – Programa Nacional da Educação na Reforma Agrária, com o objetivo de caracterizar a demanda educacional e diagnosticar a situação do ensino ofertado nos assentamentos do INCRA criados a partir de 1985. Nesse levantamento foram pesquisados três públicos - Líderes Comunitários, Famílias Assentadas e Dirigentes de Escolas - , em 5.595 assentamentos localizados em 1.651 municípios.

2. Qual o nome do conjunto? `br_inep_pnera`

3. Qual o nome da(s) tabela(s)? `escola`, `familia`, `lider`

4. Fonte original dos dados:
https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/pnera

5. Cobertura espacial: brasil

6. Cobertura temporal: 2004

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [ ] Baixar a pasta template
- [ ] Preencher as tabelas de arquitetura
- [ ] Escrever código de captura e limpeza de dados.
- [ ] Organizar arquivos auxiliares, se necessário.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by crislanealves** [comment]
Retomar depois.
