### ISSUE TITLE
[dados] br_inep_talis

### ISSUE THREAD

**Issue by lucasnascm** [basedosdados/mais#970]
**Metadados da base**

1. Descrição: A Talis é uma pesquisa direta, baseada na percepção do entrevistado. Por meio de questionários específicos para professores e diretores, ela busca saber as percepções desses dois atores sobre alguns temas relacionados ao ambiente educacional: clima escolar, desenvolvimento profissional, liderança escolar, gestão, entre outros.

2. Qual o nome do conjunto? `br_inep_talis`

3. Qual o nome da(s) tabela(s)?

4. Fonte original dos dados:
https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/talis

5. Cobertura espacial: brasil

6. Cobertura temporal: 2018

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [ ] Baixar a pasta template
- [ ] Preencher as tabelas de arquitetura
- [ ] Escrever código de captura e limpeza de dados.
- [ ] Organizar arquivos auxiliares, se necessário.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by crislanealves** [comment]
Retomar depois.
