### ISSUE TITLE
[infra] Adicionar opção de `if_columns_exist` via `Table` e `Metadata`

### ISSUE THREAD

**Issue by vmussa** [basedosdados/mais#984]
# Descrição
- integrar leitura automatica de schema entre table e metadata
- criar argumento `if_columns_exist` [pass|replace|raise]
    - precisa ser usado junto com `path` para CSV
- consertar `--columns` do `Metadata` (não está sobrescrevendo dados do CKAN)

**Comment by laura-l-amaral** [comment]
com novo formato de subida a issue perdeu o sentido
