### ISSUE TITLE
[dados] `mundo_ocde_pisa`

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#985]
**Metadados da base**

1. Descrição: Microdados dos exames do PISA para todos os anos disponíveis.

2. Qual o nome do conjunto? `mundo_ocde_pisa`

3. Qual o nome da(s) tabela(s)? `microdados`

4. Fonte original dos dados: https://www.oecd.org/pisa/data/

5. Cobertura espacial: Mundo

6. Cobertura temporal: 2000, 2003, 2006, 2009, 2012, 2015, 2018

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Exportar os arquivos SPSS para CSV
- [ ] Preencher as tabelas de arquitetura
- [ ] Escrever código de captura e limpeza de dados.
- [ ] Organizar arquivos auxiliares, se necessário.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by crislanealves** [comment]
fechando porque já foi contemplado em #1226
