### ISSUE TITLE
[dados] Substituir fonte do `br_ms_sim`.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#992]
Fonte nova do OpenDataSUS: https://opendatasus.saude.gov.br/dataset/sistema-de-informacao-sobre-mortalidade-sim-1979-a-2019

Vantagem: Já vem em arquivos csv únicos de 1979-2019.

**Comment by fabiooshiro** [comment]
Aproveitando a issue, vcs possuem os dados do ano passado?

**Comment by fabiooshiro** [comment]
obs: para mim deu 404
![image](https://user-images.githubusercontent.com/218768/149655406-f053de3c-0b85-4d3b-ad09-12eb59c97972.png)

mas está no waybackmachine

**Comment by lucasnascm** [comment]
@fabiooshiro nós não disponibilizamos ainda os dados tratados por justamente não tá oficial. No TabNet só tem até 2019. [Aqui ](http://svs.aids.gov.br/dantps/centrais-de-conteudos/dados-abertos/sim/) encontrei os dados preliminares com um arquivo zip pra download, acho que pode te ajudar!

**Comment by fabiooshiro** [comment]
Obrigado @lucasnascm !!!

demorei para entender onde se tem que clicar. 
Para outros interessados e talvez eu do futuro, segue o link direto
http://svs.aids.gov.br/dantps/centrais-de-conteudos/dados-abertos/sim/DO21OPEN.zip

**Comment by laura-l-amaral** [comment]
Feito no PR basedosdados/queries-basedosdados#132
