### ISSUE TITLE
[infra] Isolar dependências da documentação em um arquivo `requirements.txt` e usá-lo em actions

### ISSUE THREAD

**Issue by vmussa** [basedosdados/mais#994]
# Descrição
Atualmente a action `build-docs` usa o `requirements-dev.txt` para criar seu ambiente e gerar a nova documentação. Isso é ruim porque, ao fazer isso, a action instala desnecessariamente inúmeras dependências não utilizadas e, além disso, abre espaço para bugs.

# Solução proposta
- Criar um arquivo `requirements-docs.txt` apenas com as dependências da documentação
    - manter essas dependências também no `requirements-dev.txt` para evitar complicar o workflow de desenvolvimento
- Alterar a action `build-docs` para usar esse novo arquivo de dependências

**Comment by fernandascovino** [comment]
Closes with https://github.com/basedosdados/mais/pull/1036/commits/dc13ced7226c3313c465ca01d547af4e43db9633

**Comment by fernandascovino** [comment]
@vmussa hoje infelizmente nao da para separar porque o `mkdocs-click` (que gera a documentacao automatica da API Python) ple todo os arquivos `.py` que constrtoem o pacote, então tem que instalar tudo mesmo :/
