### ISSUE TITLE
[dados] br_ibge_censo_demografico

### ISSUE THREAD

**Issue by lucasnascm** [basedosdados/mais#999]
Correção dos dados da base do censo que possuem população total diferente dos dados originais devido a pesos diferentes

**Comment by lucasnascm** [comment]
Descrição das variáveis em `br_ibge_censo_demografico.microdados_domicilios_2010`

**Comment by crislanealves** [comment]
Verificar: 

- [ ] Microdados 1980 apontado por sgoldbaum.
- [ ] Valores em 1970 não cobertos por dicionários do IBGE.
